### ISSUE TITLE
jsonata.functions ??

### ISSUE THREAD

**Issue by kristianmandrup** [jsonata-js/jsonata#104]
I've been trying to work on node-red project but running into problems trying to understand this piece of code from [editor.js](https://github.com/node-red/node-red/blob/master/editor/js/ui/editor.js#L1719)

```js
Object.keys(jsonata.functions).forEach(function(f) {
     funcSelect.append($("<option></option>").val(f).text(f));
})
```

I've been looking at the [jsonata.json](https://github.com/jsonata-js/jsonata/blob/20e04942ec78fc0b8ada1d6caf22ad3936466d7d/jsonata.js
) for version 1.3 being reference in the `package.json` 

Any idea what it could be?

**Comment by knolleary** [comment]
This isn't an issue for the jsonata project. Please ask on the Node-RED mailing list for help with Node-RED specific internal code.

**Comment by kristianmandrup** [comment]
Sorry, I thought it was related to.an earlier version of jsonata or a different fork or sth.
Now I've discovered they have their own jsonata in a vendor lib, why it was quite confusing.
