### ISSUE TITLE
Promises

### ISSUE THREAD

**Issue by xogeny** [jsonata-js/jsonata#108]
In many packages where callbacks are optional (*e.g.,* `mongodb`), a function called without a callback returns a *promise*.  `jsonata` seems to buck this trend and reverts to a purely synchronous invocation scheme (as discussed in #77) when invoked without a callback.

In order to activate async processing and return a `Promise` to the result, one needs to wrap the call to evaluate in a `new Promise(...)` call (as seen [in the tests](https://github.com/jsonata-js/jsonata/blob/766ca57f09d16a138fb6c568b251860b0cc9175b/test/async-function.js)).

I realize that you have an established API, but you might wish to consider changing the semantics of `evaluate` to return a promise when invoked without a callback or, alternatively, add an additional `evaluateAsync` method that returns a promise (*i.e.,* implements the wrapping once inside the library sparing users the burden to do this themselves).

I would be happy to submit a PR if either of these if they would be accepted...

**Comment by andrew-coleman** [comment]
Yes, the `evaluate` function pre-dates the support for asynchronous extension functions.  However, your proposal for an additional `evaluateAsync` is a good one, and I'd happily accept a PR for that.
Thanks!
