### ISSUE TITLE
$merge function documented by not implemented

### ISSUE THREAD

**Issue by DeanCording** [jsonata-js/jsonata#110]
The documentation includes a description of a $merge function

http://docs.jsonata.org/object-functions.html#mergearrayobject

> $merge(array<object>)
> Merges an array of objects into a single object containing all the key/value pairs from each of the 
> objects in the input array. If any of the input objects contain the same key, then the returned object 
> will contain the value of the last one in the array. It is an error if the input array contains an item 
> that is not an object.

but using it returns a "Invalid JSONata expression: Attempted to invoke a non-function" error.

Looking through the code, it does not appear to have been implemented.

**Comment by mattbaileyuk** [comment]
What version of JSONata are you using? That function was introduced in 1.3.0 so I suspect you have an old version (old node-red deployment, maybe?). The function is certainly present in the latest, 1.4.1, as seen in http://try.jsonata.org/r1ahh28VM

**Comment by DeanCording** [comment]
Sorry, yes.  The problem is that Node Red specifies version 1.3.0
