### ISSUE TITLE
Issue with `isNumeric`

### ISSUE THREAD

**Issue by xogeny** [jsonata-js/jsonata#127]
I'm not sure what is going on in this function:

```
/**
 * Check if value is a finite number
 * @param {float} n - number to evaluate
 * @returns {boolean} True if n is a finite number
 */
export function isNumeric(n) {
    var isNum = false;
    if (typeof n === "number") {
        var num = parseFloat(n);
        isNum = !isNaN(num);
        if (isNum && !isFinite(num)) {
            throw {
                code: "D1001",
                value: n,
                stack: new Error().stack,
            };
        }
    }
    return isNum;
}
```

According to the JSDoc, `n` is presumed to be a number (not a string?).  This is substantiated by the `typeof n === "number"` conditional.  While `parseFloat` can take a number as an argument, what is the point if we **know** that `n` is already a number (which we know is the case because of the type check)?

**Comment by andrew-coleman** [comment]
The JSDoc is wrong here, `n` could be a value of any type, this function is testing to see if it is a number and in the value space of a JSON number - i.e. not infinity or NaN.

**Comment by xogeny** [comment]
Sorry, I perhaps buried the lede here.  That call to `parseFloat` seems completely superfluous here.  We know (because of the `typeof` that `n` is a number.  Calling `parseFloat` with a number just returns the argument (as far as I can tell).  So you don't need the variable `num` here...you could just use `n` since they should be identical.  Or am I missing something?

**Comment by andrew-coleman** [comment]
Ah yes, good point.  I'll remove that.
