### ISSUE TITLE
Missing field

### ISSUE THREAD

**Issue by xogeny** [jsonata-js/jsonata#133]
On [this line](https://github.com/jsonata-js/jsonata/blob/master/jsonata.js#L1262), the field `expr.name` is reference.  After create AST node types, I see that this field is never set for `function` or `partial` nodes but yet it is referenced at this point.  I ran the test suite and confirmed that it appears that `expr.name` is always `undefined`.  So this reference should simply be removed.  Given that it is undefined, it seems that it must never be used in any downstream processing.

**Comment by andrew-coleman** [comment]
Sounds like it can be removed.  Thanks.

**Comment by xogeny** [comment]
Great.  Thanks!
