### ISSUE TITLE
Convert a string containing JSON to JSON object

### ISSUE THREAD

**Issue by nabeelz6** [jsonata-js/jsonata#134]
Hi,

Is there a way to change the following string field `special` to a JSON object? I can do this in Javascript of course but was wondering if there's a way to do it using jsonata.

Input data:
```
{
  "special": "{\"field1\":\"abc\",\"field2\":321}"
}
```

Expected output:
```
{
  "special": {
    "field1": "abc",
    "field2": 321
  }
}
```

Thanks!

**Comment by andrew-coleman** [comment]
Not really.  JSONata is mostly about querying and transforming JSON structures.  What you are looking for is the ability to parse the contents of a string (albeit a string representing a JSON structure).  

Having said that, if this is something that is deemed a common use-case by multiple users, then we could add `$parseJSON()` as a built-in function

**Comment by nabeelz6** [comment]
Sounds good. Thanks for the reply!

**Comment by shrickus** [comment]
+1  That sounds like a useful function to have -- otherwise, one needs to get creative with some regex processing:
```
(
  $fromString := function($s) {
    $match($s, /\"(\w+)\":\"?([\w\d.]+)\"?/).[groups] {
      $[0]: $[1]
    }
  };
  $fromString(special)
)
```
which seems much more fraught with danger... 

And since we already have a function to turn an object or array into a string, the reverse function would make sense to have.

**Comment by andrew-coleman** [comment]
My current thinking here is to have an `$eval` function which takes a JSONata expression as its argument (in a string) and evaluates it on the current context.  Since JSONata is a superset of JSON, then this would satisfy this requirement (+ much more)
