### ISSUE TITLE
Non-optimization of arguments?

### ISSUE THREAD

**Issue by xogeny** [jsonata-js/jsonata#135]
This [line passes](https://github.com/jsonata-js/jsonata/blob/master/jsonata.js#L1269) the `arguments` field of a `lambda` node through without running `ast_optimize`.  Is this intentional?

I checked and the test suite still passes if you run the arguments through `ast_optimize`.  For now, I'm going to assume that `ast_optimize` should be run on the arguments but it would be good to get some official word on this.

**Comment by andrew-coleman** [comment]
No, a `lambda` represents a function definition, and the arguments to this have to be `variable` tokens (the parser [enforces this](https://github.com/jsonata-js/jsonata/blob/master/jsonata.js#L887)).  The `ast_optimize` would be a no-op on this.

**Comment by xogeny** [comment]
OK, I've noted this in my code.
