### ISSUE TITLE
Simplification

### ISSUE THREAD

**Issue by xogeny** [jsonata-js/jsonata#136]
On [this line](https://github.com/jsonata-js/jsonata/blob/master/jsonata.js#L1130), the following statement can be found:

```
Array.prototype.push.apply(result.steps, lstep.steps);
```

But at this point, the value of result.steps is `[]`.  So couldn't that simply be replaced with:

```
result.steps = lstep.steps
```

(or `result.steps = [...lstep.steps]` for es6, just to make sure we don't inadvertently mutate `lstep.steps`?)

I made the change myself and all tests pass.  I just want to make sure I'm not missing anything here.

**Comment by andrew-coleman** [comment]
I can't remember why I ended up with that line, I can only assume it was down to paranoia about mutating the steps array.  Anyway, if all the tests pass, then we should assume that your change is safe.  Thanks.

**Comment by xogeny** [comment]
I ended up doing the paranoid thing as well, *e.g.,* `result.steps = [...lstep.steps]`.
