### ISSUE TITLE
Lambda nodes

### ISSUE THREAD

**Issue by xogeny** [jsonata-js/jsonata#137]
I see that a node that may eventually be tagged as a `lambda` node has the `procedure` field set [here](https://github.com/jsonata-js/jsonata/blob/master/jsonata.js#L867).  However, that field doesn't seem to be needed [when evaluating a `lambda` node](https://github.com/jsonata-js/jsonata/blob/master/jsonata.js#L2767).  On the other hand, `signature` does appear to be used during evaluation.  But I notice that in `tail_call_optimize`, a thunk node is created with lacks both `procedure` and `signature`.  As mentioned above, `procedure` doesn't seem to be used, so I can see why that is dropped.  But that doesn't seem to be the case for `signature`.  So shouldn't a value for `signature` be provided [here](https://github.com/jsonata-js/jsonata/blob/master/jsonata.js#L1094)?

The code works without it.  But it also works if you provide the result of calling `parseSignature('')` as a value for `signature`.  Are they equivalent in this case?

**Comment by andrew-coleman** [comment]
The `procedure` field is not needed for lambda evaluation because it will always contain the name `function` (or `λ`).  But I see your point about `signature` being lost.  It would be good to create a test case that showed this up - I guess a tail recursive function that called itself with the wrong argument type would highlight this.

**Comment by xogeny** [comment]
A test case would be good, but I'm not sure I really understand how to synthesize it.  For now, I've generated a placeholder signature from running `parseSignature('')`.  If you do come up with a test case, let me know and I'll incorporate it into my branch.

**Comment by andrew-coleman** [comment]
Whilst the thunk itself has no signature, the function inside it (the original recursive function with the tail call eliminated) still has its signature attached and gets validated on each invocation.  I've added a test case which I believe shows this.

**Comment by andrew-coleman** [comment]
Closing as resolved.  If I've misunderstood the issue, please feel free to re-open.  Thanks!
