### ISSUE TITLE
Missing check for errors

### ISSUE THREAD

**Issue by xogeny** [jsonata-js/jsonata#138]
I notice that the parser is calls [here](https://github.com/jsonata-js/jsonata/blob/master/jsonata.js#L2912) and that there is no check for errors.

I'm guessing this is because you know with certainty that there won't be any by construction.  But
I just wanted to confirm that...?

**Comment by andrew-coleman** [comment]
I acknowledge that there is no check for a parse error for this function wrapper.  Before fixing anything like this I always try to write a test case that demonstrates the issue (I'd need one anyway to maintain 100% test coverage).  However, I was unable to contrive a test that would trigger a parse error here.  So I am going to close this issue with no further action.  If you can come up with a test case that triggers a parse error, feel free to reopen this.  Thanks.
