### ISSUE TITLE
Odd string result...?

### ISSUE THREAD

**Issue by xogeny** [jsonata-js/jsonata#155]
I'm not even sure what this *should* evaluate to, but the result I got didn't seem right.  Note, I got this "by accident" so I really didn't investigate what semantics should apply here:

Input: `{"x": [1,2], "y": [2,3]}`
Expr: `$./x|y/`
Result: `"<native function>#1"`

Note, this is a string result, but it seems like an inadvertent serialization of a function.  But even then, I wasn't sure it was possible to return a native function as a result from a JSONata expression...

**Comment by andrew-coleman** [comment]
In the exerciser, functions get displayed in the output using this format.  This doesn't happen when converted to a string using the $string() function.   Note that the regex syntax `/.../` generates a 'matching' function which can be applied to the 'pattern' arguments of `$contains()`, `$replace()`, etc., or could also be invoked directly on a string using syntax like `foo.bar[description ~> /baz*/]`.  The expression you have evaluates to a matching function, and in the exerciser will be displayed as this string (for debug purposes).

**Comment by xogeny** [comment]
Ah, ok.  If it is being done for display purposes only and doesn't represent the actual result, then that is fine.  I'll close this.
