### ISSUE TITLE
3 conundrums (might be my own naivety)!

### ISSUE THREAD

**Issue by skavan** [jsonata-js/jsonata#157]
Hi,

jsonata is quite incredible. Am trying to use it to manipulate a fairly complex json document, and for the most part, everything is working well. Am stuck on a few challenges. See Exerciser example here:  [http://try.jsonata.org/HJuY13OPf](http://try.jsonata.org/HJuY13OPf).

1. I am passed the name of the object in a variable ($jaCommand). I wish to use this variable to access the child object. If I hard type the request: `commands."input format"`, it works fine. But I can't figure out the equivalent syntax using the variable. I have tried every combo I can think of and am stuck. `commands.$jaCommand` just returns the label. It feels like I need to enter `commands[xxx = $jaCommand]`, but what is xxx? Anyway - I'm probably missing something quite basic. Help!

2. Sticking with variables,  wish to iterate (map) through the valueMap array to find the element whose regex property matches another input variable: $jaTestString. $contains looks like it would do the trick...but I can't get it to work with a variable providing the regex string. i.e. let's say my regex is in a variable : `$r = "(02)"`, $contains("02", /$r/) doesn't work. Nor does any combo I can think of. How do I solve this conundrum. I am working around it, by having my own regex function in javascript passed to jsonata...but would still like to know the jsonata way.

3. A more mundane question. If I copy and paste a multi-line jsonata pattern into my Javascript editor, it needs a lot of line terminating "\" to be usable, and even then, is a bit of an eyesore. Is there a different, more sensible approach? Here's an example:

```
expression = jsonata('$map($spread(advanced)[*.command="audio signal"],function($v,$i,$a){ \
                                    $map(($v.*.valueMap), function($v2, $i2,$a2){ \
                                        $v.*.type="target" ? ( \
                                            $jaRegexMatch($jaValue, $v2.regex) ? \
                                                {"category":$v.*.category, "value":$v.*.values.match, "topic": $v.*.topic & $jaDelimiter & $v2.topic, "clear": $v.*.clear} :\
                                                {"category":$v.*.category, "value":$v.*.values.nomatch, "topic": $v.*.topic & $jaDelimiter & $v2.topic, "clear": $v.*.clear}\
                                        ) : ( \
                                            $jaRegexMatch($jaValue, $v2.regex) ? \
                                                {"category":$v.*.category, "value":$v2.displayValue, "topic": $v.*.topic, "clear": $v.*.clear}\
                                        )\
                                    })})');
```
Oh - one more question - is there a looping function that one could break out of. In the regex example above, once I hit a match, I don't need to continue. Is there anyway to skip the redundant loops?

Hope that all makes sense. Thanks.

**Comment by shrickus** [comment]
You are right -- I'm constantly amazed how much I can accomplish with jsonata expressions...

1. The function you are looking for is `$lookup(...)`, which essentially de-references the variable and searches for a field with that name.

2. I think this expression does what you are looking for:

```
(
    $jaCommand := "input format";
    $jaTestString := "02";
    $lookup(commands, $jaCommand).valueMap[regex~>$contains($jaTestString)]
)
```

3. If you are using ES6, you can now surround a multi-line string in back-tics (but I'm not sure how to show that here inside markdown content)

As for looping -- well, I don't think that really fits in with a lambda expression processor, but that's more a question for Andrew (the author).

-- Steve

_P.S. if you join the slack site, we can discuss these types of syntax questions more easily._

**Comment by skavan** [comment]
Thx - I would never in a million years figured out #2! Would love to join the slack site but it requires me to have an ibm domain and I don't. Perhaps someone cd invite me!

**Comment by shrickus** [comment]
Andrew knows about the IBM domain limitation, but I just asked him and he added my email.

Try this:  andrew_coleman@uk.ibm.com

--

Steve

**Comment by andrew-coleman** [comment]
@skavan Slack invitation sent.
Thanks @shrickus for answering this.  I'll close this as resolved.
