### ISSUE TITLE
JSONATA undefined in Internet explorer

### ISSUE THREAD

**Issue by hufedebe** [jsonata-js/jsonata#158]
Hello everyone,

I just did a project heavily using JSONata, and it works perfectly well in Mozilla, Chrome, and Edge. But it doesnt work in Internet Explorer, it just shows the following error:

"SCRIPT5009: 'jsonata' is undefined", please help.

I'm just using it like this:

jsonata('string').evaluate(data);

**Comment by andrew-coleman** [comment]
I suspect this is an ES6 issue.  Have you tried using the babel transpiled version `jsonata-es5.js`?

**Comment by hufedebe** [comment]
Thank you Andrew, it almost works. In one part of the code i'm extracting properties normally with jsonata: info = jsonata('[xml.resume.{"date" : date, "field2": field2}]').evaluate(data); and then I want to add a counter, because its several objects, so I have this code: info = jsonata('$ ~> $map(function($v, $i) {$merge([{\'count\': $i+1}, $v])})').evaluate(info);. But that changes info into an Object Generator (according to Internet Explorer): [object Generator]. before I merge it with the count, it does output a correct object though, do I have to change the merge function? @andrew-coleman

**Comment by andrew-coleman** [comment]
Does this same code evaluate correctly in other browsers?  I don't have Internet Explorer (or Windows) so there will be a lack of testing on my part here.

**Comment by hufedebe** [comment]
Yes, in all other browsers it works fine, its having problems in Internet Explorer - it creates the [object Generator] instead of adding the "count" attribute to the existing object. Other than that, the other jsonata parts work well. its just the adding a "count" attribute to the existing object that works incorrectly, is there another way of obtaining the same result without using "$ ~> $map(function($v, $i) {$merge([{'count': $i+1}, $v])})"?

**Comment by s100** [comment]
@hufedebe Can you provide minimal reproduction steps for this issue? At minimum please can you show us your HTML, what version of JSONata you are using, and what version of Internet Explorer you are using.

**Comment by s100** [comment]
A minimal reproduction is:

```html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>JSONata test</title>
        <script src="jsonata-es5.js"></script>
        <script>
            const output = jsonata("$map([1..5], $string)").evaluate({});
            console.log(output)
        </script>
    </head>
    <body></body>
</html>
```

In Chrome, this outputs an array `["1", "2", "3", "4", "5"]`. IE11, this outputs the `[object Generator]` which was mentioned. Still working on why...

**Comment by s100** [comment]
It seems that the problem here is in how we detect whether a value returned from a JSONata function is iterable or not. This heuristic works fine on e.g. Chrome but fails on IE11. I have worked out a fix.
