### ISSUE TITLE
Is it possible to filter the object based on property value?

### ISSUE THREAD

**Issue by Muthu2020** [jsonata-js/jsonata#162]
For example:

var sampleJSON = {
           properties:{
                  type:'binary'
                  operator:'instanceof'
           }
};

Need to filter the object based on operator value of instanceof.

Can someone help me out?

**Comment by shrickus** [comment]
I don't think there is enough information here to answer your question -- you have a single object with an object for the "properties" field. What do you mean by "filter" the object? If this is your input, what outputs do you expect for a matching object? What output if there is no match?

**Comment by andrew-coleman** [comment]
Closing.  Feel free to re-open if you have more details to add to the question.
