### ISSUE TITLE
Wrong Argument?

### ISSUE THREAD

**Issue by xogeny** [jsonata-js/jsonata#164]
From [this line](https://github.com/jsonata-js/jsonata/blob/master/jsonata.js#L2700), it appears that the arguments to the `apply` function are a procedure object, an array of arguments, and an input value.  That input value is referred to in the `apply` function as `self`, so that doesn't she that much light on what it is supposed to be.  So the question is...what is that third argument to `apply` used for?

If we trace it all the way down to `applyInner`, we see that `self` is used [here](https://github.com/jsonata-js/jsonata/blob/master/jsonata.js#L2752) and [here](https://github.com/jsonata-js/jsonata/blob/master/jsonata.js#L2759) are passed as the first argument to a call to the `apply` **method** on a (presumably) `Function`.  So this is essentially injecting the `this` value to be used in the context of the function's evaluation.

As such, I'm a bit confused by what the point of that value is.  [In some cases](https://github.com/jsonata-js/jsonata/blob/master/jsonata.js#L2700), we see an `input` value being passed in as the third argument to `apply` but in [other cases](https://github.com/jsonata-js/jsonata/blob/master/jsonata.js#L2511) we see `environment` being passed in?!

I'm pretty confused as to why either of these would be passed in because ultimately they will be assigned to `this` during function invocation and it seems like what should really be assigned to `this` is the actual `function` itself?!?

**Comment by xogeny** [comment]
After digging further, it appears that the main use of the `self` argument is in the call to `validateArguments` which (by using the signature) can determine if the first argument is missing and, if so, prepend the value of `self` to the arguments.  But it seems to me that it is being misused in the other contexts where it appears.  Or am I missing something?  I can see the `this` value having these "odd" (?) values when the functions are invoked.  Not sure of the utility of it?

**Comment by andrew-coleman** [comment]
I experimented with plugging in the [moment](http://momentjs.com/) library as an extension function.  It is a function which returns an object containing more functions.  It is available plugged into the exerciser, although it's not part of JSONata itself.  An example [here](http://try.jsonata.org/r1hxMqEOz).  The `self` argument is required in order for the member function to be invoked correctly (`format` in this example).

Another example that relies on this is discussed [here](https://github.com/jsonata-js/jsonata/issues/77#issuecomment-337585080).

**Comment by xogeny** [comment]
That part makes sense.  You are essentially doing a `.bind`.  But what I don't understand is why sometimes the `environment` is passed and other times `input`.  More specifically, how can `environment` ever be a valid thing to pass?

**Comment by andrew-coleman** [comment]
Hmm, fair point.  At the moment I can't see why I pass `environment`.  I guess I need to take it out and see if anything breaks.
