### ISSUE TITLE
$formatNumber function returns NaN.00 when null in input

### ISSUE THREAD

**Issue by raj-work** [jsonata-js/jsonata#165]
Hi,

We are using formatNumber to return an amount field properly formatted. But instead we are getting a "-NaN.00". 

Example:
$formatNumber($number(Account.Order[0].Product[2].Price), "#0.00")
returns "-NaN.00"
in the Account example of TryJSONata.

The expected behavior is it should return a null since the inside evaluation will return a null.

**Comment by andrew-coleman** [comment]
Yep, that's a bug - thanks for reporting.

**Comment by raj-work** [comment]
@andrew-coleman - thanks for the reply. I think you are missing the following check:
// undefined inputs always return undefined
        if (typeof value === 'undefined') {
            return undefined;
        }

**Comment by mattbaileyuk** [comment]
@raj-work Good spot! As you may have already seen, we're certainly open to taking pull requests.
