### ISSUE TITLE
Issues with path processing

### ISSUE THREAD

**Issue by xogeny** [jsonata-js/jsonata#170]
Another issue I see with evaluation semantics.  Consider the following expression (input doesn't matter): `[1, 2, 3].$`.  The result of evaluating this is `[1, 2, 3]`.  The idea here is that because `.` is a map operation, we are simply mapping over each element in `[1, 2, 3]` and then for each successive value (*i.e.,* `1`, `2`, and `3`) we are evaluating the expression `$`.

Now this construction is useful because we see that adding `.$` to any expression that evaluates to an array should have no impact.  In a sense, this is (or at least one would certainly expect) that this would be an identity transformation in the same what that surrounding an atomic expression with a block (*i.e.,* `(...)`) shouldn't change the value (assuming the block doesn't impact the precedence of operators, of course).

The issue I see in `v1.5.x` is that it there are special cases in the evaluation code and these special cases generally lead to surprising results because they lead to inconsistencies in evaluation.  The following is an example...

Consider we evaluate the expression `[1, 2, 3]`.  Of course, our result will be `[1, 2, 3]`.  In the same way, if we evaluate:

```
($v := [1,2,3]; $v)
```

...we also get `[1, 2, 3]`.  This is no surprise because we have just effectively wrapped a block around our original expression.  But the problem is with these special cases.  In particular, the current evaluation code actually handles the first step in a path in a special way.

Conceptually speaking, the evaluation code needs to determine if the first step in the path is effectively independent of the input value (*i.e.,* evaluates to a constant).  This is important because (as far as I can tell), if the path *does* depend on the input, then there is an implicit map operation applied by the first expression (*i.e.,*, you could conceptually speaking prepend a `$.` to the start of your expression).  But if it *doesn't* depend on the input, then the first step isn't an expression we map over but instead **amounts to the effective input for the remainder of the path**.

There are two issues here.  First, these semantics are inconsistent (i.e., the role of the first step changes depending on context in complex and hard to describe ways).  But the bigger problem, in some sense, is the fact that it doesn't actually handle all cases correctly.

To demonstrate this, consider the following table:

|  Expression | Result |
| ----------- | ------ |
| `[1, 2, 3]` | `[1, 2, 3]` |
| `[1, 2, 3].$` | `[1, 2, 3]` |
| `($v := [1,2,3]; $v)` | `[1, 2, 3]` |
| `($v := [1,2,3]; $v).$` | `[1, 2, 3]` |

Remember that the semantics should be such that if the first step is independent of the input, then it should be evaluated as the effective input for the remainder of the path and that adding `.$` on the end shouldn't impact the result.  We see this is the case for a simple array, but it isn't for the case with a block.  But it really should be since these things evaluate to the same exact value.  This is because the current code handles the case of a literal array, but not one constructed by other means.

You can look at this as two different problems with potentially two different solutions.  If you see the problem as the fact that the table above is inconsistent, you could add some kind of function to traverse the tree and determine if any of the nodes in the first step actually reference the input.  If they don't, then you simply evaluate the first step as an expression in and of itself and then use that as the effective input for the remainder of the path.  This is what it seems `v1.5.x` is trying to do, but doesn't truly evaluate this but instead tries to use heuristics to determine if there is any dependence on the input value (hence the inconsistency in the table above).

If you see the problem as the inherent inconsistency in path processing (*i.e.,* that evaluation depends **at all** on whether the first step references the input), then the solution would be to simply evaluate the first step the same, independent of any dependence on the input.

My opinion is the former (that evaluation shouldn't depend on a special property of the first expression).  My solution would be as follows.  **Always evaluate the first step as an initial expression** and the remaining steps as mapping operations over the initial expressions value.  The reason I prefer this solution is not just that it is simpler and more consistent, it is because it is very easy to achieve the `v1.5.x` behavior by simply preprending `$.` to *explicitly* introduce a dependence on the input value.

Comments?

**Comment by jhorbulyk** [comment]
What is the Expression <-> Result table trying to show?  Currently, I see four identity operations on `[1, 2, 3]` which match the result column.  Where does the evaluated result differ from your expectations?

**Comment by xogeny** [comment]
My mistake, thanks for pointing that out.  I forgot to adjust that.  The correct able is as follows:

| Case |  Expression | Result | Input | 
| ---- | ----------- | ------ | ----- |
| 1 | `[1, 2, 3]` | `[1, 2, 3]` | N/A |
| 2 | `[1, 2, 3].$` | `[1, 2, 3]` | N/A |
| 3 | `($v := [1,2,3]; $v)` | `[1, 2, 3]` | N/A |
| 4 | `($v := [1,2,3]; $v).$` | `[1, 2, 3, 1, 2, 3]` | `[1, 2]` |
| 5 | `($v := [1,2,3]; $v).$` | `[1, 2, 3, 1, 2, 3, 1, 2, 3]` | `[1, 2, 3]` |

But note that the last entry depends on the input value.

The reason, to reiterate, is that cases 2 and 4 are paths and so they are evaluated as steps.  The second step, in each case, is `$`.  But it is the first step that is problematic.  If the first step is an array, `jsonata` treats the value of the first step as the input that is mapped over in the second step (case 2).  But if it doesn't recognize the first step as an array, then it maps the first step expression over every value of the input (hence the repetition in case 4).

**Comment by xogeny** [comment]
I just realized that the situation is a bit worse than I thought.  In order to achieve consistency, it would be good to have a foolproof way of determining whether to evaluate the first step "normally" or whether to map the input over it.

The current policy is to [check if the node for the first expression is a literal array](https://github.com/jsonata-js/jsonata/blob/master/jsonata.js#L1641).  However, that policy only considers one special case so you can construct cases, as I have done above, that evaluate to an identical value and yet yield a different result for the path.

In my first comment, the policy I proposed an alternative which was to check to see if there were any references to the input value and, if so, treat the first step as a mapping over that input value and if not treat it as an effective input to map over in the rest of the path. 

But the problem I see there is, what should the result of the following be?

| Expression | Input | Result |
| --------- | ------ | ----- |
|  `[1, $[1], 3].$` | `[1, 2, 3]` | ??? |

Should we be mapping the input over that first step or not?  It is an array, but it isn't really a literal array.  Nevertheless, `jsonata` currently does not map over it.  Following the "does it reference the input" policy, we would map the input value over this.  Both of these policies are going to require users to think pretty hard and they still violate the principle of least surprise (in my opinion) because they lead to cases where we get *identical* answers when evaluating the first step and yet, different answers when evaluating the complete path even if only the first step is different.

This, to me, reinforces the virtue of my original proposal (*i.e.,* "Always evaluate the first step as an initial expression").  In that case, we would get the following behavior:


Case | Expression | Result | Input
-- | -- | -- | --
1 | `[1, 2, 3]` | `[1, 2, 3]` | N/A
2 | `[1, 2, 3].$` | `[1, 2, 3]` | N/A
3 | `($v := [1,2,3]; $v)` | `[1, 2, 3]` | N/A
4 | `($v := [1,2,3]; $v).$` | `[1, 2, 3]` | `[1, 2]`
5 | `($v := [1,2,3]; $v).$` | `[1, 2, 3]` | `[1, 2, 3]`
6 | `$.($v := [1,2,3]; $v).$` | `[1, 2, 3, 1, 2, 3]` | `[1, 2]`
7 | `$.($v := [1,2,3]; $v).$` | `[1, 2, 3, 1, 2, 3, 1, 2, 3]` | `[1, 2, 3]`
8 | `[1, $[1], 3].$` | `[1, 2, 3]` | `[1, 2, 3]` |
9 | `$.[1, $[1], 3].$` | `[1, 2, 3]` | `[1, 2, 3, 1, 2, 3, 1, 2, 3]` |

As you can see from this table, the evaluation is consistent (the evaluation semantics are always the same in each case) and we can achieve every result we got before.

However, not that this would also result in the following changes:

| Case | Expression | Input | Old Result | New Result |
| ---- | ---- | ---- | ---- | ---- |
| 1 | `a` | `{ "a": 5 }` | `5` | `5` |
| 2 | `a` | `[{ "a": 5}, {"a": 7}]` | `[5, 7]` | `undefined` |
| 3 | `$.a` | `[{ "a": 5}, {"a": 7}]` | `[5, 7]` | `[5, 7]` |

Case 3 here underscores my point that if you want the previous behavior, you'd need to prepend a `$.` to the expression to force it to be mapped over vs. evaluated.  Although the evaluate in case 2 is different, to me it actually makes more sense if you really think about it because the input is an array and asking for field `a` of an array doesn't make sense (*i.e.,* it doesn't have a property called `a`).

To be clear, I could accept other semantics as well.  I have no pride wrapped up in "always evaluate the first step as an initial expression" semantics.  I'm just looking for a good compromise that provides consistent behavior and allows you to still get the same results with slightly different syntax (with simpler implementation and semantics being a bonus).

**Comment by xogeny** [comment]
After discussing this with @andrew-coleman, we decided that a good alternative would be to have explicit syntax to indicate that the start of the path was to be evaluated and used as an input (ignoring the provided input).  The proposed syntax would be a leading `.` in the path to trigger that type of evaluation.  We decided to prototype this to see that we could get the same results with this new syntax and semantics in cases that would be impacted.

**Comment by xogeny** [comment]
I've been ruminating on this topic over the last few days and I have some additional thoughts.

The core issue here, as I see it, is what to do with the first step in a path (although there are some implications for object creation as well).  Specifically, whether the first step should be considered an expression to be evaluated or whether it is an expression to apply to each element of the "input".  The current semantics are such that the first step in a path is handled differently depending on whether it references a variable or constructs an array.  This leads to some uneven handling and some inconsistent evaluation results.

After discussing it, @andrew-coleman and I decided that adding a new unary `.` operator at the start of a path could be a means to explicitly indicate that the first step in a path should be evaluated as a pure expression vs. applying it to each element of the input.  However, I see two potential complications.

First, if we were to add a leading `.` to a path to indicate that the first step should just simply be evaluated and form the effective input to the remaining steps, then what would `.$` mean?  In a sense, the leading `.` means "ignore the input" but then immediately following it is an expression that evaluates to the input.  But I think we can address this once we consider...

The second point was about use cases.  In thinking about this, I recognized that there are (at least) two distinct classes of use cases in `jsonata`.  One is where want to apply a `jsonata` expression to some input data and the other is where we simply want to evaluate the `jsonata` expression by itself (without any regard to the input data).  In my previous discussions with @andrew-coleman, I largely dismissed this second class of use cases because I always envisioned expressions like `[1, 2, 3].($*2)` where you are operating exclusively on constants.  If you operate on constants, you don't really need `jsonata`, just write `[2, 4, 6]` instead.  The use of constants seemed mainly for demonstration purposes (*i.e.,* demonstrating simple `jsonata` expressions without having to define an input).

But then I realized that there are plenty of use cases (even my own) like this that don't actually involve constants, *e.g.,* `$fetchData(someUrl).process.data`.  Here we are feeding in dynamic data to a `jsonata` expression, **we just aren't doing it via input data**.  We are fetching it (either from functions or from predefined variables).  At first glance, this seems like exactly the use case for our unary `.`, *i.e.,* `.$fetchData(someUrl).process.data` or even `.[1,2,3].($*2)`.

But in some sense there is a reason why the current `jsonata` semantics carve out a special case for array construction and variable references and that is because these are really the ways that we introduce new non-input data into the expression.  And using a leading `.` makes it explicit when you want to process data in this way.  But then I realized that in most cases, *we already know we are ignoring the input data* **because we aren't providing it**.  That got me thinking...in the case where the user does not provide any input data (*e.g.,*, they provide `undefined` as the input value), we can pretty much *assume* a leading `.`, no?

Generally speaking, I prefer explicit notation.  But I also like the DRY principle.  Having a leading `.` is explicit but at the same time, it seems redundant if we don't provide any input data because in that case it seems obvious we don't want to apply our expression over every element of the input data *because there isn't any input data*.

So in considering this tension between being explicit and being redundant, I think there is a reasonable compromise here and that is to assume that in cases where there is no input data, the first step in the path should simply be evaluated as a pure expression.  In this way, we don't actually need the unary `.`, we just need to have the discipline to not pass any input data.  It turns out, I'm not even sure we need change the evaluation semantics for a path either...

Now at the start I mentioned this also has implications for object construction.  It turns out that treating no input as a special case already exists in `jsonata`.  For example, if we pass in `undefined` (or any scalar value), it automatically gets promoted to an array [here](https://github.com/jsonata-js/jsonata/blob/master/jsonata.js#L1631) and [here](https://github.com/jsonata-js/jsonata/blob/master/jsonata.js#L2206) (that is where the object construction comes in).  We also do something similar (but not quite the same) [here](https://github.com/jsonata-js/jsonata/blob/master/jsonata.js#L1626).

 So my current thinking is why not just introduce the rule that if the input passed in to `evaluate` is undefined, that we immediately transform it into the array `[undefined]`.  That means our input has one value and that value is undefined.  In that case, we can treat every step in the path as a "map over" operation and, fortunately, the very first map over operation will be a map over an array with a single `undefined` value which is effectively the same thing as simply evaluating the first step as an expression (and it addresses my very first point because in that case `$` would be `undefined`).

This would allow us to eliminate the special handling of arrays and variables in path and treat all steps as "map over" cases. It means we could also get rid of special handling in the object construction case as well.  Overall, this means simpler and more consistent semantics.  You could *also* implement the unary `.` operator as a more explicit option.  But if these semantics are implemented, I'm not sure there is much call for it.

Comments?

**Comment by andrew-coleman** [comment]
I've just been doing a bit of GitHub archeology to find the time when the evaluator used to work exactly as you suggest above.  This [commit](https://github.com/jsonata-js/jsonata/commit/32044ff93bc84ed31da04f9db98f8469166e441c) added the special handling of the array constructor as the first step in the path.  I did this because I noticed that when pasting literal JSON into the JSONata expression box in the exerciser, it could evaluate to different things depending on what was in the input data box on the left-hand side.  One of the design points of JSONata is that it is a superset of JSON, and that evaluating a 'JSON literal' expression would produce the same JSON.  However, I could have resolved that issue by predicating that statement with '...produce the same JSON provided there is no input data passed in'.  So maybe, with the benefit of experience, that would be a better solution from the point of view of consistent semantics.  But what we also need to keep in mind is what is the best solution from the point of view of end user experience, and remember that end users might be using JSONata in an environment where they don't directly control what gets passed to the `evaluate` function (e.g. Node-RED, and others).  It was this 'surprise' of seeing a JSON array replicated in the result when I wasn't looking at the input that caused me to put this logic in.

So I'm a bit torn here, but I think you've made a good case for consistent semantics (which I totally agree with).  I think some explicit syntax for ignoring the input (e.g. unary `.`, as we discussed) will be required for users that can't necessarily control what is passes to the evaluate function.  I think you should go ahead and implement this in your evaluator and we should try and get it into a 2.0 branch on jsonata github so that we can play with it in the exerciser.

**Comment by xogeny** [comment]
As you know, I like the idea of invoking consistency principles (*e.g.,* "wrapping an expression with `(...)` shouldn't change the evaluate if it doesn't impact operator precedence", or "Adding a $.* in front of a path shouldn't impact the evaluate", *etc*).  But I had not fully realized the principle you were following here of JSONata expressions being a subset of JSON.  So I like that as a design constraint.  Note that if JSONata is a subset of JSON, it seems inconsistent to force the introduction of a `.` before the expression to ensure the principle that the expression should match the output.  Or perhaps I'm totally misunderstanding something here.

A couple of comments/questions.  The first question is, when you say "I think you should go ahead and implement *this*", I want to make sure I am straight on which antecedent you are referring to. 😄 Are you referring to a unary `.` operator?  Or my proposal to "introduce the rule that if the input passed in to evaluate is `undefined`, that we immediately transform it into the array [undefined]. "?

Before you answer that, I want to clarify something.  When I say "no data is passed in", I literally mean there is no data.  As far as I can tell, there is no way in the exerciser to pass `undefined` as an input.  Note that `undefined` is not a valid JSON token, so it really cannot be present in serialized JSON.  And leaving the input in the exerciser blank isn't treated as `undefined` either.  So unless Node-RED and other users *explicitly* pass `undefined` as an input, it doesn't seem like this should ever impact them and in those cases, I'm not entirely sure what they should expect as the output.  I don't think my proposal actually breaks the existing functionality in this case...?

**Comment by andrew-coleman** [comment]
resolved by #363
