### ISSUE TITLE
Missing data for errors?

### ISSUE THREAD

**Issue by xogeny** [jsonata-js/jsonata#178]
For errors of type `T0410`, it appears that the `throw` is missing data.  I say this because the message is defined [here](https://github.com/jsonata-js/jsonata/blob/master/jsonata.js#L4864) and appears to require a `token` field.  But in the two places that this is actually thrown ([here](https://github.com/jsonata-js/jsonata/blob/master/jsonata.js#L487) and [here](https://github.com/jsonata-js/jsonata/blob/master/jsonata.js#L498)), the information isn't provided.

As an aside, the way I'm dealing with errors in my `2.x` branch types each error so that the required information is present (otherwise a compile time error will be reported).

**Comment by andrew-coleman** [comment]
That's because the point at which the error is thrown (in the signature validator), the name of the function is not known.  The exception is caught further up the stack [here](https://github.com/jsonata-js/jsonata/blob/master/jsonata.js#L2717) where this missing insert is filled in.

**Comment by andrew-coleman** [comment]
Closing issue as I believe this has been answered
