### ISSUE TITLE
API usability issue?

### ISSUE THREAD

**Issue by brucejo75** [jsonata-js/jsonata#180]
I am just starting to integrate with JSONata.  My project plan is to parse many strings (1000s) with the same context.

I am looking at the API spec and the concept seems to be that a string to parse is sent into the pipeline then you can modify the context surrounding the string before final evaluation. e.g.:
```
var jsonata = require('jsonata');
var expr = jsonata("<string to parse>");
var data = {... context};
var result = expr.evaluate(data);
```

Essentially, I want to set up the context and then parse multiple strings, e.g.:

```
var jsonata = require('jsonata');
var context = jsonata({... context});
context.registerFunction('name', () => 'my function');
stringsToParse.forEach((jStr) => context .evaluate(jStr));
```

Is there a way to build (and cache) the context before evaluating multiple strings?  Otherwise, I believe I will have to pay the setup price for each string that I evaluate.

thanks for any and all feedback!

**Comment by xogeny** [comment]
I'm not sure I understand your question 100%.  Let me try and restate it and see if I get it right.

Your concerns is that you want to process the same data with multiple JSONata expressions.  In other words, you will be using the same data as input to the JSONata evaluate, but you want to pass a different string each time.

If so, then I presume your concern is with the effort of building what you call the "context" (the term used internally in JSONata is environment) given that you expect to have the same bindings (matching variable names to values or functions) in all cases.

To be honest, I don't think this will be much of a performance issue.  Behind the scenes, the "context" used here is a simple Javascript object and you are simply storing away key value pairs.  So this should be highly optimized.  Note that each JSONata expression has to be compiled and the computation effort involved in *that* is going to be much higher than the creation of the "context".

So personally, I really wouldn't worry about that part.

**Comment by brucejo75** [comment]
Thanks for the response.  I think your answer allays my concerns.
