### ISSUE TITLE
Matching API not documented

### ISSUE THREAD

**Issue by xogeny** [jsonata-js/jsonata#183]
As discussed in #177, there is a special API for handling regular expressions.  When evaluated, a regular expression returns an object containing:

  * `match` - The string that matched
  * `start` - Index (in the original string) where the match starts
  * `end` - Index (in the original string) where the match ends
  * `groups` - ??? (which group the match belongs to?!?)
  * `next` - A function to retrieve the next match or `undefined` if no more matches can be found.

**Comment by andrew-coleman** [comment]
This is now documented [here](https://docs.jsonata.org/regex).
