### ISSUE TITLE
broken links to Array Constructor documentation in JSONata doc

### ISSUE THREAD

**Issue by michaelthoward** [jsonata-js/jsonata#185]
[This section of this page](http://docs.jsonata.org/basic.html#top-level-arrays-nested-arrays-and-array-flattening) makes two hyperlink references to `array constructors`

The links are to `http://docs.jsonata.org/basic.html#array-constructors`

These references should link to `http://docs.jsonata.org/construction.html#array-constructors`

**Comment by michaelthoward** [comment]
Found another broken link in the doc ...
http://docs.jsonata.org/basic.html#navigating-json-arrays refers to _predicate_ with a link to `http://docs.jsonata.org/basic.html#predicates`
This link should reference
`http://docs.jsonata.org/complex.html#predicates`

**Comment by andrew-coleman** [comment]
Thanks for reporting.  These links (and a couple of others) have now been fixed.
