### ISSUE TITLE
Slack invitation pls

### ISSUE THREAD

**Issue by michaelthoward** [jsonata-js/jsonata#186]
I am new to JSONata and am trying to get involved. 
I see https://github.com/jsonata-js/jsonata/issues/98

If appropriate, I would like to get an invite for slack. 
Thanks

**Comment by andrew-coleman** [comment]
Please send me your email address - it's not in your github profile

**Comment by michaelthoward** [comment]
email is mhoward@podiumdata.com

**Comment by andrew-coleman** [comment]
invitation sent

**Comment by bigdoods** [comment]
Hi Andrew. Could you send me invite please john@bimlauncher.com - I cant see anywhere to signup

**Comment by mattbaileyuk** [comment]
@bigdoods I have sent you an invite.

For anyone else reading this, you can request an invite by clicking the Slack icon in the top-right on the exerciser (this [also mentioned in the docs](https://docs.jsonata.org/contributing#slack))
