### ISSUE TITLE
native implementation User Defined Function support

### ISSUE THREAD

**Issue by michaelthoward** [jsonata-js/jsonata#191]
I realize that this is/will-be implementation specific. 

In cases where JSONata lambdas don't quite cut it ...

Q: For the JavaScript/ES implementation of jsonata, is there a preferred/standard/supported mechanism for adding/registering native implementations of functions so that they can be used in JSONata queries?

**Comment by andrew-coleman** [comment]
Yes, this is supported and documented in the Readme:
https://github.com/jsonata-js/jsonata#expressionregisterfunctionname-implementation-signature
