### ISSUE TITLE
Transforming a simple guid object to a complex object within an array of arrays

### ISSUE THREAD

**Issue by raghubuddy1154** [jsonata-js/jsonata#197]
Hi, I am trying something to transform from:
![image](https://user-images.githubusercontent.com/23052510/38724919-42a88c64-3f23-11e8-995a-b2d64810054e.png)

to 
![image](https://user-images.githubusercontent.com/23052510/38724948-55613b6c-3f23-11e8-83a4-536e3d550225.png)

Basically, my change will be with the Input and Outputs tags within the Component named 'switchboard'.
"Input": "02a1a00c-9475-462f-a7ba-7cbf039d1d6b"

to 
"Input": {
                  "ID": "02a1a00c-9475-462f-a7ba-7cbf039d1d6b",
                  "name": "Id - 1"
                },

The input is now not a guid, rather I need a complex object which will contain this guid as ID and then a new property tag added).

Could someone guide me on iterating through an array of arrays and then create new objects to transform to ?

**Comment by raghubuddy1154** [comment]
Wow, thanks so much for this. I am an even bigger newbie to this. This works like a charm.

**Comment by andrew-coleman** [comment]
Thanks @michaelthoward for answering this.  Closing as resolved
