### ISSUE TITLE
Please invite me to Slack

### ISSUE THREAD

**Issue by brodo** [jsonata-js/jsonata#201]
Hi there, could I please have an invitation to the Slack channel?
julian.dax@posteo.de

Thanks!

**Comment by andrew-coleman** [comment]
Invite sent.  BTW, anyone already in this Slack channel can invite anyone else.

**Comment by angelineflorajohn** [comment]
Hi @andrew-coleman, my team and I use JSONata extensively. Could we get invited to the official JSONata slack channel ? ahoffer@institutesofhealth.org and angeline@institutesofhealth.org
