### ISSUE TITLE
Can we move the $clone function out of the test suite?

### ISSUE THREAD

**Issue by deepilla** [jsonata-js/jsonata#207]
It's been confirmed that the `$clone()` function is not meant to be used in JSONata expressions (see [this thread](https://github.com/jsonata-js/jsonata/issues/193)). So I'd like to remove it from the Go implementation of JSONata. The transform operator will still make copies of objects under the hood, but there won't be a `$clone()` function available to end-users.

This will cause the following tests in the test suite to fail:

- all tests from the [function-clone](https://github.com/jsonata-js/jsonata/tree/master/test/test-suite/groups/function-clone) group
- [one test](https://github.com/jsonata-js/jsonata/blob/master/test/test-suite/groups/transforms/case012.json) from the transforms group

I propose moving these tests from the main test suite to the [JavaScript test suite](https://github.com/jsonata-js/jsonata/blob/master/test/implementation-tests.js). The `$clone()` function only exists to make jsonata-js play nicely with node-red. That's not something that other implementations will need. And if a similar requirement (for pluggable copy semantics) arose in jsonata-go, I wouldn't want to implement it in the same way.

Ideally the language-agnostic test suite would only include functionality that we expect to be common across all JSONata implementations. The node-red backdoor is a workaround for one specific implementation.

**Comment by andrew-coleman** [comment]
Yes, I'm happy that you do this.  Feel free to submit a PR. Thanks!

**Comment by mattbaileyuk** [comment]
Fixed by #209 - thanks @deepilla
