### ISSUE TITLE
Request: function or functions for testing data type of a value

### ISSUE THREAD

**Issue by michaelthoward** [jsonata-js/jsonata#208]
Per [this question on stackoverflow](https://stackoverflow.com/questions/49712517/jsonata-method-or-function-for-testing-json-value-datatype/49900869), JSONata needs a function functions for testing JSON data type. 

Seems this could be predicates for testing individual data types (e.g. isBoolean(), isNumber(), etc.) and/or a function which returned the data type as a string.

**Comment by basel-shishani** [comment]
+1
I believe this feature is essential as it's very common to have structures with anyOf possible types.

**Comment by jhorbulyk** [comment]
**Proposal for syntax:** 
`$type(value)`
Returns:
- (non-string) `undefined` if `value` is undefined
- (string) `'null'` if `value` is null
- (string) `'number'` if `value` is a number
- (string) `'string'` if `value` is a string
- (string) `'boolean'` if `value` is a boolean
- (string) `'array'` if `value` is an array
- (string) `'object'` if `value` is an object
- (string) `'function'` if `value` is a function

**Comment by andrew-coleman** [comment]
Resolved by #381
