### ISSUE TITLE
$filter returns undefined in async mode

### ISSUE THREAD

**Issue by dprentis** [jsonata-js/jsonata#217]
I am not able to use the filter function in async mode. It always returns undefined ie.
```
const out = await new Promise((resolve) => {
  const expression = jsonata('$filter(data, function($d) { true })');
  expression.evaluate(input, {}, (err, value) => {
    console.log('ERROR?', err); // null
    resolve(value); // undefined
  });
});
```
data is a valid array and the expression `data` returns the array. Also using `$filter` in synchronous mode works as expected (using version 1.5.3).

**Comment by andrew-coleman** [comment]
This is one example of a number of problems with the async mode of operation.  I have now written an async test driver to run the whole test suite in async mode and fixed up all the failing cases, including this one.

**Comment by dprentis** [comment]
That's amazing - thanks!
