### ISSUE TITLE
Parts work but not expression

### ISSUE THREAD

**Issue by wnm3** [jsonata-js/jsonata#223]
Given input like this:
````
{
  "dm_classifier": {
    "response": "2",
    "outputs": [
      "A",
      "B",
      "C",
      "D"
    ]
  }
}
````
And an expression like this:
````
dm_classifier.outputs[$number(dm_classifier.response)]
````
I get "no match", however, $number(dm_classifier.response) returns 2, and dm_classifier.outputs[2] returns "C".

What am I missing?

**Comment by wnm3** [comment]
This does work however:
````
($x:=$number(dm_classifier.response);dm_classifier.outputs[$x])
````

**Comment by shrickus** [comment]
It has to do with the current context of the expression inside the square brackets... if you reset your context to the root, like so, then it works as expected:

**Comment by wnm3** [comment]
Thank you!

**Comment by andrew-coleman** [comment]
Closing as resolved
