### ISSUE TITLE
What are the @ and # operators?

### ISSUE THREAD

**Issue by deepilla** [jsonata-js/jsonata#232]
The list of operators in jsonata-js includes the symbols `@` and `#`. They don't appear to be used anywhere but defining them as operators precludes their use in variable names for example. Are they being reserved for future use?

**Comment by andrew-coleman** [comment]
Yes, I reserved them for future use (not sure what yet!)

**Comment by deepilla** [comment]
Ok, thanks. I should probably do the same in jsonata-go then.
