### ISSUE TITLE
Inconsistency between $map and $filter/$sift

### ISSUE THREAD

**Issue by deepilla** [jsonata-js/jsonata#233]
The `$map` and `$filter` functions have similar definitions. They both take an array of values and a function with the following signature (from the docs):

```
function(value [, index [, array]])
```

This suggests that `$map` and `$filter` can handle functions that take one, two, or three arguments. But only `$map` seems to work like this. `$filter` chokes if you give it a function that can't take all three arguments.

Let's use the `$boolean` function as an example. It only takes one argument, yet this map expression works as you'd expect:

```
$map([0, 1, 2], $boolean)  // returns [false, true, true]
```

Whereas using `$boolean` in a filter expression causes an error:

```
$filter([0, 1, 2], $boolean)  // returns Argument 2 of function "filter"
                                     does not match function signature
```

You can make this work by wrapping the call to `$boolean` in a lambda function:

```
$filter([0, 1, 2], function($x){$boolean($x)})  // returns [1, 2]
```

It might appear that this lambda function only takes one argument, but lambdas without type signatures will happily accept any number of arguments (try it!). Add a type signature specifying a single argument, and the expression fails again: 

```
$filter([0, 1, 2], function($x)<x:b>{$boolean($x)})  // fails!
```

If you play around with the signature it's clear that any function incompatible with three arguments causes an error:

```
$filter([0, 1, 2], function($x)<xx:b>{$boolean($x)})  // fails!

$filter([0, 1, 2], function($x)<xxx:b>{$boolean($x)})  // returns [1, 2]

$filter([0, 1, 2], function($x)<x+:b>{$boolean($x)})  // returns [1, 2]

$filter([0, 1, 2], function($x)<xxxx:b>{$boolean($x)})  // fails!
```

This looks like a bug in the `$filter` function. While `$map` checks how many arguments your function takes and only passes that number, `$filter` always passes all three values. This happens to work for lambdas but it can cause issues with built-in or third-party functions.

`$sift`, the equivalent of `$filter` but for objects, has the same problem:

```
$sift({"a": 1}, $boolean)  // fails!
```

**Comment by andrew-coleman** [comment]
Many thanks for the detailed analysis here.  I'll fix this.
