### ISSUE TITLE
JSON transformation

### ISSUE THREAD

**Issue by RJFoster** [jsonata-js/jsonata#234]
The JSONata [documentation claims that it is capable of transforming JSON objects](http://docs.jsonata.org/index.html#introduction), and I like the power the JSONata syntax provides

However the only documentation around transformation I see is the [~> | ... | ... | operator](http://docs.jsonata.org/operators.html#------), which somewhat assumes that the structure of the two documents are similar. Am I missing something? What is the best practice for transforming JSON documents with JSONata?

For example I might want to transform from an object like:
```
{
    a: {
        id: 'aye',
        namespace: 'bob'
    },
    b: [
       {
           bx: '12',
           by: '34'
       },
       {
           bx: '56',
           by: '78'
       },
    ]
    c: 'see',
    d: {
        data: 'ignored'
    }
    e: 'eeeeh'
}
```
to something like
```
{
    m: 'see',
    n: 'eeeeh',
    o: [
      {
          oa: {
              code: 'aye',
              ns: 'bob',
              q: 'aye@bob'
          }
          ox: '12',
          oy: '34'
      },
      {
          oa: {
              code: 'aye'
              ns: 'bob',
              q: 'aye@bob'
          }
          ox: '56',
          oy: '78'
      }
    ],
    p: 'hardcoded'
}
```

**Comment by andrew-coleman** [comment]
The following will do this:
```
{
  "m": c,
  "n": e,
  "o": b.{
    "oa": $$.a.{
      "code": id,
      "ns": namespace,
      "q": id & "@" & namespace
    },
    "ox": bx,
    "oy": by
  },
  "p": "hardcoded"
}
```
See example [here](http://try.jsonata.org/HkGjjbBx7)

The general approach is to use the expected output JSON as a starting point for your JSONata expression, then replace the hardcoded values with expressions that reference the input.  Be careful to use properly formatted JSON (property names must be quoted) rather than the Javascript notation that you have pasted above.

**Comment by xogeny** [comment]
@RJFoster Another way to look at this...JSONata is a superset of JSON.  This isn't always obvious but what it means in practice is that it you can use it to describe a JSON value but the "superset" part allows you to reference variables in the process.  Variables such as `$$` and `$` can be used to refer to an input JSON value but you can also refer to external values and functions in the "environment".  So in such cases, the transformation occurs not via the explicit syntax for transformation but through this process of building a new value from a bunch of other values in the environment.

**Comment by RJFoster** [comment]
Thanks @andrew-coleman, @xogeny that is what I was looking for. Can I suggest that the documentation be updated with a "common use cases" or similar section as the current docs are very syntax centric rather than use case centric
