### ISSUE TITLE
Singleton operator has no effect on an array of objects

### ISSUE THREAD

**Issue by DaelDe** [jsonata-js/jsonata#236]
Consider the following input:
```
[
{"type":"command"},
{"type":"commands"}
]
```
and expression `$[type='command']`. It returns the first object properly. However, I want to use the singleton operator to have easier handling: `$[][type='command']` does not return an array of matches and `$[type='command'][]` does neither.
How can I always return an array of results in my case?

**Comment by jhorbulyk** [comment]
`[$[type='command']]` does what you are looking for.

**Comment by andrew-coleman** [comment]
This is a bug and is related to the second paragraph of [this comment](https://github.com/jsonata-js/jsonata/issues/218#issuecomment-391981518).  I'll fix this.

**Comment by DaelDe** [comment]
@jhorbulyk indeed but I am not sure if this is intended behavior of jsonata, from reading the docs I am not sure.
