### ISSUE TITLE
Flatten Hierarchical JSON

### ISSUE THREAD

**Issue by aahladatparadigm** [jsonata-js/jsonata#238]
Hi I am trying to flatten nested JSON Data

Sample Input
`{
    "publishers": [
        {
            "name": "pub1",
            "books": [
                {"bookName": "book1" },
                {"bookName": "book2" }
            ]
        },
        {
            "name": "pub2",
            "books": [
                {"bookName": "book3" },
                {"bookName": "book4" }
            ]
        }
    ]
}`

I want this input to be Flatten like below
`{
    "books":[
        {"bookName": "book1", "publisherName": "pub1" },
        {"bookName": "book2", "publisherName": "pub1" },
        {"bookName": "book3", "publisherName": "pub2" },
        {"bookName": "book4", "publisherName": "pub2" }
    ]
}`

I tried but unable to refer to the parent attribute value.

**Comment by andrew-coleman** [comment]
Try this:
```
{
  "books": publishers.(
    $pubName := name;
    books.{
      "bookName": bookName,
      "publisherName": $pubName
    }
  )
}
```

**Comment by aahladatparadigm** [comment]
@andrew-coleman  Perfect!! Thank you so much.
