### ISSUE TITLE
Set case to a string array

### ISSUE THREAD

**Issue by gmag11** [jsonata-js/jsonata#239]
Hi,
I need to check if a string is contained in an array. String case can vary, it could be like 
`{"array":["one","two""three"] or ["oNe","Two","THREE"]}` in any conbination.

If in this example I should find "one" or "One" or "ONE" or "onE" ......... what expresion could I use?

I've tried `"one" in array` and `"one" in $lowercase(array)`. First fails when case is not exact and second complain about array not being a string.

Is there any way to use a string function with each array member?

Thanx

**Comment by gmag11** [comment]
I've found it. I did not know the function `$map`.

Expression is `"one" in $map(array,$lowercase)`

**Comment by andrew-coleman** [comment]
You can also do
```
array.$lowercase()
```
because `.` is an implicit map operator

**Comment by gmag11** [comment]
Great. Thanks!!!
