### ISSUE TITLE
Boolean operators return inconsistent results with undefined inputs

### ISSUE THREAD

**Issue by deepilla** [jsonata-js/jsonata#246]
This issue was first raised in a [Slack post](https://jsonata.slack.com/messages/C2L3MR5EH/p1531168044000184). I'm reposting here (with some additional info) so it doesn't get lost.

The original poster was using the `or` operator with one falsy value and one undefined value (a non-existent path expression). They noticed that the `or` operator sometimes returned `false` and sometimes returned `undefined` depending on the order of the operands.

I tried various combinations of the `or` and `and` operators with one or more undefined values (named `foo` and `bar`) and got the following results.

#### Or

```
true or foo    // true
foo or true    // true

false or foo   // undefined
foo or false   // false

foo or bar     // undefined
```

#### And

```
true and foo    // undefined
foo and true    // undefined

false and foo   // false
foo and false   // undefined

foo and bar     // undefined
```

Note that:

1. Combining a falsy value with an undefined value does indeed give different results depending on the order of the operands.

2. There's a mix of boolean and undefined results, e.g. `true or foo` returns `true` but `true and foo` returns `undefined`.

These are the only binary operations that produce such inconsistent results. Numeric operators (like `+` and `-`) return `undefined` if either operand is undefined. Comparison operators (like `=` and  `<`) return `false` if either operand is undefined. And the concatenation operator (`&`) treats undefined operands as empty strings.

Boolean operators should have a similarly well-defined approach to undefined inputs. I suggest one of the following:

1. Treat undefined operands as `false` (this would turn all of the `undefined` results above to `false`).

2. Return `undefined` if either operand is undefined (all of the above expressions would then evaluate to `undefined`).

Any thoughts on this, @andrew-coleman?

**Comment by wnm3** [comment]
If we are considering increasing the use of undefined, I think we need a function to test for this state (unless = "undefined" will work). Perhaps an $isDefined() or $exists() would be helpful here.

**Comment by jhorbulyk** [comment]
> Perhaps an $isDefined() or $exists() would be helpful here.

@wnm3 [Like this `$exists()` function](http://docs.jsonata.org/boolean-functions.html#existsarg)?

**Comment by wnm3** [comment]
Precisely like that ;^) thank you -- I hadn't found this when I looked.

**Comment by andrew-coleman** [comment]
Thanks for raising this @deepilla.  I think I favour your first suggestion

> 1. Treat undefined operands as false (this would turn all of the undefined results above to false).

This would be consistent with the comparison operators

**Comment by wnm3** [comment]
Try $boolean(**.tags)
Best Regards, Nat
 
Nathaniel Mills
Senior Technical Staff Member - Project Lead / Chief Architect WILD Conversation Workflow Orchestration Project
Phone: 1-860-812-5089 (m)
E-mail: wnm3@us.ibm.com
 
 
----- Original message -----From: monicagarud <notifications@github.com>To: jsonata-js/jsonata <jsonata@noreply.github.com>Cc: Nathaniel Mills <wnm3@us.ibm.com>, Mention <mention@noreply.github.com>Subject: Re: [jsonata-js/jsonata] Boolean operators return inconsistent results with undefined inputs (#246)Date: Wed, Jul 18, 2018 2:24 AM 
$boolean() is not working correctly for empty array as per mention in the document http://docs.jsonata.org/boolean-functions.html
check this for reference:http://try.jsonata.org/S1SR3InX7
Thank you
