### ISSUE TITLE
Is $keys supposed to return a sequence?

### ISSUE THREAD

**Issue by deepilla** [jsonata-js/jsonata#249]
I noticed that `functionKeys()` includes a call to `createSequence()`, yet `$keys` doesn't behave like other functions that return a sequence. For example, the expression `$keys({"a": 1})` evaluates to `["a"]` (a singleton array) rather than `"a"`.

There's [a test](https://github.com/jsonata-js/jsonata/blob/master/test/test-suite/groups/function-keys/case003.json) in the test suite that checks for the singleton array case. However I just wanted to double-check that this is the intended behaviour.

**Comment by andrew-coleman** [comment]
Yes, this is a bug in `functionKeys()`.  The sequence is being overwritten by an array.  The test needs to change too.
Thanks!
