### ISSUE TITLE
Should $each accept functions that take a single argument?

### ISSUE THREAD

**Issue by deepilla** [jsonata-js/jsonata#250]
The following expression returns an error:

```
$each({"hello": "world"}, $uppercase)  // Error: Argument 2 of function "each"
                                             does not match function signature
```

This makes sense. According to the docs, the second parameter of `$each` is a function that takes two arguments, `value` and `name`. And `$uppercase` only takes one argument.

However the docs also say that `name` is optional, which suggests (to me at least) that `$each` should work with functions that take a single argument. Other higher order functions like `$sift`, `$map` and `$filter` either already work like this or are being updated to do so (see [this issue](https://github.com/jsonata-js/jsonata/issues/233)). Is there any reason why `$each` should not follow suit?

**Comment by andrew-coleman** [comment]
Yep - I agree on both of these points.
