### ISSUE TITLE
Proposal: Extend $number() to booleans

### ISSUE THREAD

**Issue by jhorbulyk** [jsonata-js/jsonata#257]
Currently JSONata has the function [`$number()`](https://docs.jsonata.org/numeric-functions.html#numberarg).  The documentation for this function states:

> Casts the arg parameter to a number using the following casting rules
> - Numbers are unchanged
> - Strings that contain a sequence of characters that represent a legal JSON number are converted to that number
> - All other values cause an error to be thrown.
> 
> If arg is not specified (i.e. this function is invoked with no arguments), then the context value is used as the value of arg.

I suggest the following additional casting rule:
> - Booleans with value `true` produce `1`.  Booleans with value `false` produce `0`.

Any objections?

**Comment by andrew-coleman** [comment]
Sounds reasonable to me
