### ISSUE TITLE
Change Json keys during transformation

### ISSUE THREAD

**Issue by wxwang33** [jsonata-js/jsonata#262]
Hi,

Is there a way to change the keys of an nested hash while using shortcut accessors?
As an example, if Account.Order gives an array of hash, can I change any of the keys in these hashes?

Thanks

**Comment by andrew-coleman** [comment]
Closing as resolved.  I believe the previous comment is the answer to this question, but feel free to reopen if I've missed the point, or post the question on StackOverflow (tag jsonata).
