### ISSUE TITLE
Test suite - possible changes needed

### ISSUE THREAD

**Issue by cristiangraz** [jsonata-js/jsonata#274]
I'm still working through the test suite, but I've noticed a few areas where I expect different results than what JSONata returns/the test suite asserts.

## Range Operator
There is an error for the left/right side of the range operator not evaluating to an integer, but JSONata seems to just silently ignore errors. See below.

**range-operator/case007.json**
**input**: `[-2..blah]`
**return**:  `[]`
**expected**: `T2004` `The right side of the range operator (..) must evaluate to an integer`

**range-operator/case008.json**
**input**: `[blah..5, 3, -2..blah]`
**return**:  `[]`
**expected**: `T2003` `The left side of the range operator (..) must evaluate to an integer`

## Numeric Operators
If the `-` prefix is used to negate something, and the right side does not evaluate to a numeric value, shouldn't we see `D1002` returned?

**numeric-operators/case016.json**
**input**: `- notexist`
**return** undefined
**expected**: `D1002` `Cannot negate a non-numeric value: {{value}}`

## Errors

**errors/case005.json**
**input**: `unknown(function)`
**return**: `T1006`: `Attempted to invoke a non-function`
**expected**: `function` is a language keyword -- the parser should catch that it's missing `(` and return `S0202` `Expected "(", got ")"`

I see the value of this test, but I think this should be two tests. This one (as written) should return a parser error. The original test should just use `unknown()` as the `input` (no function args necessary) and expect `T1006`

**Comment by andrew-coleman** [comment]
In all of these cases I believe they are working as designed.  

In the case of the numeric operators (including the range operator), they will return `undefined` if either, or both operands are `undefined`.  There was a recent discussion ([bug 242](https://github.com/jsonata-js/jsonata/issues/242) case 2) where we agreed that if either operand did exist, then its type checking should take precedence over existence checking of the other operand.  However, that doesn't apply to these three cases.

`function` is not a keyword.  JSONata has no reserved keywords.  Some words (i.e. `and`, `or`, `in`) will get interpreted as operator tokens iff they are used in the expression as a binary operator.  When parsing a function invocation `name()`, the JSONata parser will recognise if the name of the function is "function" and will interpret that as a function definition.  However, in the expression `unknown(function)`  the name "function" will be interpreted as field reference (i.e. lookup the value of the 'function' property of the current context object).  That part might well return `undefined`, but it's not an error.

Hope that makes sense.
