### ISSUE TITLE
Angular 6, ES5, and IE11 issues

### ISSUE THREAD

**Issue by CPolarisAlpha** [jsonata-js/jsonata#287]
Hi!

**Angular 6:**
Alright, so I'm running into a few issues with Jsonata.  I've wrapped Jsonata in an Angular 6 package and it's working well on Chrome and Firefox.  Unfortunately, I need to support IE 11 as well.  I can't find a way (other than fileReplacements and shell scripts) to select the ES5 version of Jsonata pulled down in node_modules.  My Angular 6-fu is weak, so if anyone knows of a better way to do this, it would be appreciated.

**ES5 and IE11:**
When I cracked open the ES5 version of Jsonata I found shorthand property notations (functions returning functions via shorthand), spread operators, and a fat arrow function.  None of which are supported by ES5 in IE11.  Other browsers seem to handle it just fine, still an issue with IE11.

Thanks!

**Comment by andrew-coleman** [comment]
Yep, I've been working on getting the test suite to run on Nashorn (a barebones ES5 implementation), and found a number of shortcomings.  Working on a fix.

**Comment by MaciejJer** [comment]
Hello!
Facing the same problem as author.
What is a civilized way to import es5 version of JSONATA by default in angular app?

import * as jsonata from 'jsonata';
points to jsonata.d.ts which uses es6 version of Jsonata, hence IE11 crashes.
Any idea? Is there may be a parameter which I can add to package.json of the Application o force use of es5 version?

**Comment by manojkr001** [comment]
@MaciejJer ,
Facing same issue, Did you get any way to add  es5 version of JSONATA in angular app..

**Comment by MaciejJer** [comment]
@manojkr001 
1. Add needed polyfills to the polyfills.js file
2. import * as jsonata from 'jsonata/jsonata-es5.js';
this has resolved my issue, basically check where jsonata-es5.js is located. cheers

**Comment by manojkr001** [comment]
Thanks a lot @MaciejJer, for quick response and suggestion.. it worked...
