### ISSUE TITLE
Question: Odd Behavior With Bound Moment

### ISSUE THREAD

**Issue by goulderb** [jsonata-js/jsonata#298]
I've been binding moment through into JSONata by doing the following on an expression:

```
expression.registerFunction('moment', moment, '<s?s?(sb)?b?:o>');
```

When I try to use certain instance methods, like .diff, the behavior of these methods seems to be completely broken from how I'd expect them to work. There's some examples below, and I'm trying to understand why these evaluate differently.

Given the following input data:
```json
{
  "beginDate": "2019-01-23T16:38:27.276Z",
  "endDate": "2019-01-23T17:48:27.276Z"
}
```

Each of the following produce different results:

Correct Output:
```
(
  $beginDate := $moment(beginDate);
  $endDate := $moment(endDate);

  {
    "beginDate": $beginDate,
    "endDate": $endDate,
    "diff": $moment($endDate).diff($beginDate)
  }
)
```

Incorrect (passing a string to .diff):
```
(
  $beginDate := $moment(beginDate);
  $endDate := $moment(endDate);

  {
    "beginDate": $beginDate,
    "endDate": $endDate,
    "diff": $moment($endDate).diff(beginDate)
  }
)
```

Incorrect (invoking $moment inline):
```
(
  $beginDate := $moment(beginDate);
  $endDate := $moment(endDate);

  {
    "beginDate": $beginDate,
    "endDate": $endDate,
    "diff": $moment($endDate).diff($moment(beginDate))
  }
)
```

In the two incorrect cases, it seems like moment completely fails to parse begin date and uses the current date instead. The only way that I seem to be able to consistently get the .diff instance method to work is the to do what I did in the "correct" output and bind each value to a variable.

All of these test cases can be executed against try.jsonata.org as well, so I'd appreciate any insight into why JSONata is spitting out the output it is.

**Comment by andrew-coleman** [comment]
It looks to me like the context is not getting passed down into the `.diff` step.  In your second two (failing) examples, if you replace `beginDate` with `$$.beginDate`, then they work as expected.

**Comment by andrew-coleman** [comment]
I think this has been answered.
No further discussion, so closing.
