### ISSUE TITLE
Access deeper properties via path string

### ISSUE THREAD

**Issue by M0ebiu5** [jsonata-js/jsonata#300]
Is there a way to access deeper properties with a path string?

For example:
$lookup(payload, "data.val")

```
"payload": {
            "data": {
                "loc": "wz",
                "cmd": "volume",
                "val": 5
            }
        }

**Comment by jhorbulyk** [comment]
What about `$lookup(payload, "data").val` ?

**Comment by andrew-coleman** [comment]
[`$eval`](https://docs.jsonata.org/string-functions#eval) will do this.  The string can contain any valid JSONata expression.

`$eval("data.val", payload)`

**Comment by M0ebiu5** [comment]
> $eval("data.val", payload)

This does not work for me - i get the following error:
```
Error evaluating expression:
  Attempted to invoke a non-function

**Comment by andrew-coleman** [comment]
Are you on the latest version? `$eval` was added to v1.6.
http://try.jsonata.org/H1Xb1ksEE

**Comment by mattbaileyuk** [comment]
@M0ebiu5 What version of JSONata are you using? `$eval()` was added in 1.6.1. I don't believe node-red have picked this up yet if that's where you're using JSONata

**Comment by M0ebiu5** [comment]
@mattbaileyuk yes, i come from the node-red side...
BR & thank you all!
