### ISSUE TITLE
add my own function extension?

### ISSUE THREAD

**Issue by yxuco** [jsonata-js/jsonata#301]
To evaluate an expression that uses my own functions, I can add my own function using `expression.registerFunction("myfunc", ...)`, but it applies to only the single expression.  Is it possible to register my function "permanently", so I can use it in all other transformation expressions?

**Comment by mattbaileyuk** [comment]
One way I've done it in the past is to have another function as a wrapper, e.g.

```
const jsonata = require('jsonata')
  
let jsonataExtended = (expression) => {
        let expr = jsonata(expression)
        expr.registerFunction("add", (a, b) => a + b, "<nn:n>")
        return expr
}
```
so I can then call `jsonataExtended(myExpression).evaluate(myJSON)` to evaluate my JSONata expression, which will use both the both in functions as well as my additional one. In this case, `jsonataExtended("$add(10,5)").evaluate({}))` to return `15`.
