### ISSUE TITLE
$lookup function signature should be <o-s:x>

### ISSUE THREAD

**Issue by wnm3** [jsonata-js/jsonata#304]
The $lookup function operates on an object passed or via context variable but its function signature claims it works with anything (<x-s:x>)

**Comment by andrew-coleman** [comment]
This is a similar issue to [this one](https://github.com/jsonata-js/jsonata/issues/303#issuecomment-470889457)

**Comment by andrew-coleman** [comment]
Closing since I believe this is working as designed
