### ISSUE TITLE
$append function signature should show ability to use context variable <x-x:a>

### ISSUE THREAD

**Issue by wnm3** [jsonata-js/jsonata#305]
$append works with context variable but function signature does not advertise this is possible.

**Comment by andrew-coleman** [comment]
You've raised lots of bugs that are all related.  I'll explain how the evaluator works in this one, and close all the others as duplicates.

Any function whose parameter is an array cannot have that array passed in as the context.  In other words, a signature of the form `<a->` is not possible.  The reason for this is if an array were on the left hand side of a map operator (`.`) then the expression on the right hand side would get evaluated for each value inside that array.  So if the LHS was the array `[1,2,3]` and the RHS was a function `$append`, then the function would get evaluated 3 times, first with the value `1` as the context, then the value `2`, then `3`.  It would *not* be evaluated once with `[1,2,3]`.  To get that you could use the chain operator (`~>`), i.e `[1,2,3] ~> $append([4,5,6])`
