### ISSUE TITLE
$exists function signature should show ability to use context variable <x-:b>

### ISSUE THREAD

**Issue by wnm3** [jsonata-js/jsonata#306]
$exists function signature does not show it works with the context variable, but it does.

**Comment by andrew-coleman** [comment]
...but it does what?  Please could you paste an example of what you believe it is doing wrong?
Thanks.

**Comment by wnm3** [comment]
I think I was testing various combinations of swapping out the "~>" (chain) operator with the "." (map) operator in try.jsonata.org and found cases where they worked, but the signature didn't advertise the capability. I understand the difference now between chain and map so I'll close this.

It may have been examples like:
($x=false; $x.$exists())
but to be honest, I don't recall what expression I was testing at the time.
