### ISSUE TITLE
$lookup() should throw exception Context value is not a compatible type with argument 1 of function "lookup"

### ISSUE THREAD

**Issue by wnm3** [jsonata-js/jsonata#312]
This would make it more compatible with other context seeking functions missing their first argument... It currently throws the exception: Argument 1 of function "lookup" does not match function signature

**Comment by andrew-coleman** [comment]
Please could you provide an example of data/expression that demonstrates this?

**Comment by wnm3** [comment]
Now that I understand the desired behavior for $lookup to be more relaxed to search out objects for matching keys, I will close this. What I was claiming was, if $lookup's signature should have limited input solely to an Object, then it should throw the exception (Argument 1 of function... ) if it had received an array. So, I was lobbying for something like #304 to throw this exception. However, your kind example in #304 explained how $lookup and $keys functions can work with other input variables.
