### ISSUE TITLE
Array output results differ between 1.6.4 and 1.5.4

### ISSUE THREAD

**Issue by webOS101** [jsonata-js/jsonata#314]
Given the following input:

```
{
  "tags": [
    {
      "title": "example",
      "description": "Hello"
    }
  ]
}
```

And the following expression:
```
$.tags[][title='example'][]
```

1.6.4 produces an extra nested array:
```
[
  [
    {
      "title": "example",
      "description": "Hello"
    }
  ]
]
```

Whereas 1.5.4 produced this output:
```
[
  {
    "title": "example",
    "description": "Hello"
  }
]
```

I didn't see any bug fixed that might explain this, unless it was #236 (listed twice in the vnotes for 1.6.1).

It's entirely possible that my poor jsonata skills are at fault, but I didn't expect a difference between these two versions.

**Comment by webOS101** [comment]
Investigating along the lines that I'm not so great at jsonata, I tried a few different expressions.  This seems to work in both 1.5.4 and 1.6.4:

```
$.[tags[title='example']]
```

What I'm trying to do is ensure I get back an array of all objects in `tags` with a title of `'example'`.

**Comment by andrew-coleman** [comment]
There's clearly a regression in v1.6.  There shouldn't be an extra level of nesting in the output.

**Comment by andrew-coleman** [comment]
resolved by [this commit](https://github.com/jsonata-js/jsonata/commit/afe903cbd2b6e24a445bc5db5adfe1dee3654962)
