### ISSUE TITLE
extend cope of defined functions to everywhere in the document

### ISSUE THREAD

**Issue by cscetbon** [jsonata-js/jsonata#315]
I'd like to define functions that could be used when parsing different documents. However it seems that a function can be used only in the block it's defined. Am I wrong or is there a way to do it otherwise ?

```
{ "hidden-code": ($square := function($n){ $n * $n };),
  "ValidProductID": ($square(2))
}

Attempted to invoke a non-function
```

**Comment by jhorbulyk** [comment]
try
```
(
$square := function($n){ $n * $n };
  { 
    "ValidProductID": ($square(2))
  }
)
```

**Comment by cscetbon** [comment]
@jhorbulyk exactly what I was looking for. Thanks !
