### ISSUE TITLE
Empty Array input always renders empty object output no matter what the query is

### ISSUE THREAD

**Issue by apoggi-carecloud** [jsonata-js/jsonata#316]
Input:
`[]`
will always result in 
Output:
`{}`
Example query:
`{"hello": "world"}`

**Comment by mattbaileyuk** [comment]
@apoggi-carecloud Would http://try.jsonata.org/SycA90CIE describe your situation?
That looks like a bug to me, whereby the query which is being used to build a new output (and thus shouldn't care about the input) is being ignored in favour of processing of the input empty array. (Applying a function does work, so it's not getting `{}` is _every_ case)

**Comment by apoggi-carecloud** [comment]
Your linked example is exactly the issue I am having.

**Comment by andrew-coleman** [comment]
This issue is related to how JSONata handles input arrays.  There is a lengthy discussion in #170 on this topic.  I'm currently prototyping a solution that uses explicit syntax to determine whether to map over the input array verses just use it as a single context value.

**Comment by andrew-coleman** [comment]
resolved by #363
