### ISSUE TITLE
Returning an element from a dictionary

### ISSUE THREAD

**Issue by cscetbon** [jsonata-js/jsonata#317]
I'm trying to create a function to retrieve values for a provided code. It's not provided in the input data, so I'm defining it in a function. However I can't find a way to retrieve it. 
Here is what I tried : http://try.jsonata.org/HJYOFH_DN 

I was expecting to get **value2** but whatever I pass to function $cc I get it back. I'm surely not using the right syntax but that'd be great to see what's the right way to do it.

**Comment by jhorbulyk** [comment]
try
```
{
"cc": ($cc:=function($x){($a := {"key1": "value1", "key2": "value2"};
                          $lookup($a, $x))}; 
       $cc(f1))
}
```

**Comment by cscetbon** [comment]
Thanks @jhorbulyk. That's exactly it. Last question, is there a way to mark fields as required and to enforce JSONata to raise an error if no value is found ?

**Comment by mattbaileyuk** [comment]
@cscetbon There is not, and I'm not sure I would expect JSONata to do that sort of validation. I think you would be better off building a [JSON Schema](https://json-schema.org/understanding-json-schema/index.html) and using that to perform validation of your data (possibly even two schema, one for input and one for output if you want to be strict) using some of the existing validators up on npm.
