### ISSUE TITLE
How can I use a variable to hold the regex?

### ISSUE THREAD

**Issue by duartegarin** [jsonata-js/jsonata#319]
Hi,
When trying to pass a regex pattern to a function using a variable it doesn't seem to work.
For example:
$match($v,/$regex_expression/)
Is there any way to achieve this?
Cheers

**Comment by jhorbulyk** [comment]
```
(
$regex_expression := /^f.*b/;
$match("foobar",$regex_expression)
)
```
works for me.

**Comment by duartegarin** [comment]
@jhorbulyk thanks, but the idea is to make part of the expression variable. In my case I need to pass some months of the year (and they change on each object).

**Comment by jhorbulyk** [comment]
```
(
$inputVar := "b";
$regex_expression := $eval("/^f.*" & $inputVar & "/");
$match("foobar",$regex_expression)
)
```

**Comment by duartegarin** [comment]
You sir, are a legend!
Thank you :)

**Comment by haydenk** [comment]
> ```
> (
> $inputVar := "b";
> $regex_expression := $eval("/^f.*" & $inputVar & "/");
> $match("foobar",$regex_expression)
> )
> ```

This isn't really your problem but just so it's there for anybody searching this issue. This solution does not work for AWS Step Functions as `$eval` is not available.
