### ISSUE TITLE
How to break chain if it was evaluated sucessfull. 

### ISSUE THREAD

**Issue by phantomis** [jsonata-js/jsonata#320]
Hi

I'm trying to check if this lib could help me doing some transformations with combinations of values like this: 

I need to perform something like this

source: 

```
{
   "CodeX":"ValueX",
   "CodeY":"ValueY"
}
```

Destination:

```
{
   "CodeA":"ValueA",
   "CodeB":"ValueB",
   "CodeC":"ValueC"
}
```

And the rules should be: 

`If CodeX.value == ValueX AND CodeY.value== ValueY, then, CodeA.value = ValueA, CodeB.value = ValueB, CodeC.value = ValueC`

OR

`If CodeX.value == ValueX AND CodeY.value== ValueY2, then, CodeA.value = ValueD, CodeB.value = ValueE, CodeC.value = ValueF`

I did this with the following expresion.
http://try.jsonata.org/ryMP_I8uV

Is it a good approach? is it performant? I feel like I'm testing every combination in a chain sequence, and I know if match with one function of the chain, it should stop to propagate the callings.

Thanks a lot

**Comment by mattbaileyuk** [comment]
I'm trying to understand the more generic case; for example, does order matter? (I'm assuming not if the items are not in an array) Is it that if:
- one item matches a certain value
- AND if another item matches one of two values
then set up the ValueA,B,C object, or if
- another item matches the second of two values
then set up the ValueD,E,F object?

Not that I have any particular objection to how it has been done in the link, it's just I'm struggling to think of a more efficient generic expression, probably using JSONata functions, while trying to solve the rules as is.

I am partly expecting one of our regular to chime in with a great idea, though 😄

**Comment by phantomis** [comment]
the problem itself is, mathing combinations of values in the source, to a specific values as destination. So, the order doesn't matter, and, if you matched some combinations, jsut stop to test the others alternatives. 

In pseudocode the logic should be


```
if ( codeA == 'A' ) {
 if (codeB == 'B') {
   return  { "anotherCode1" : "AnotherValue1" , "anotherCode2" : "AnotherValue1" }
 }
 else if (codeB == 'C') {
   return  { "anotherCode1" : "AnotherValue3" , "anotherCode2" : "AnotherValue4" }
 }
}
else if ( codeA == 'D' ) {
 if (codeB == 'A') {
   return  { "anotherCode1" : "AnotherValue5" , "anotherCode2" : "AnotherValue6" }
 }
 else if (codeB == 'B') {
   return  { "anotherCode1" : "AnotherValue7" , "anotherCode2" : "AnotherValue8" }
 }
}
```

**Comment by andrew-coleman** [comment]
I think the most performant approach would be to preprocess all of the input conditions into a set of lookup tables.  This will involve generating a single mangled key for each of the possible combinations of inputs.  The following example simply concatenates them into a single string (using your rules above): 

```
(
  $anotherCode1 := {
    "AB": "anotherValue1",
    "AC": "anotherValue3",
    "DA": "anotherValue5",
    "DB": "anotherValue7"
  };
  $anotherCode2 := {
    "AB": "anotherValue1",
    "AC": "anotherValue4",
    "DA": "anotherValue6",
    "DB": "anotherValue8"
  };
  {
    "anotherCode1": $lookup($anotherCode1, CodeA & CodeB),
    "anotherCode2": $lookup($anotherCode2, CodeA & CodeB)
  }
)
```
The lookup with then be efficient.
http://try.jsonata.org/r17KI5EF4

**Comment by andrew-coleman** [comment]
Closing since I think this has been answered
