### ISSUE TITLE
How can i access an array element dynamically?

### ISSUE THREAD

**Issue by M0ebiu5** [jsonata-js/jsonata#323]
Why this expression does not work?
`payload.stat.arpath[payload.stat.pathcnt-2]`

this is the according json:

```
 {
     "_msgid": "ccd5af07.c6c1e",
     "topic": "",
     "payload": {
         "name": "/mnt/toshi1/Rezepte/Suesses/zopf flechten.GIF",
         "stat": {
             "size": 4903,
             "arpath": [
                 "",
                 "mnt",
                 "toshi1",
                 "Rezepte",
                 "Suesses",
                 "zopf flechten.GIF"
             ],
             "pathcnt": 6,
             "ext": ".GIF"
         }
     }
 }
```

I'm using v1.6.4
Here is the try link http://try.jsonata.org/r1OWgUYOV

**Comment by jugaadi** [comment]
The scope of the context value inside arpath is limited to arpath. If you want to break out of the current context scope to a different path, then you could use `$$` to navigate from the root of the document.

So `payload.stat.arpath[$$.payload.stat.pathcnt-2]` should solve your problem.

**Comment by M0ebiu5** [comment]
Great, thanks!
