### ISSUE TITLE
JSONata for API transformation in OS technology

### ISSUE THREAD

**Issue by tony-shannon** [jsonata-js/jsonata#325]
Hi,

Kudos to the authors of jsonata for your leading work on this very powerful technology.

Question please about its use in API management, transformation etc.
We are using a JS based technology http://qewdjs.com/  for JSON mapping and transformation of APIs in the healthcare domain here, as part of a set of open source tooling that healthcare needs, please see here for info
https://github.com/robtweed/qewd-transform-json
https://github.com/robtweed/qewd-transform-json-editor

This allows us to transform JSON to/from APIs between at least 3 variants;
eg DB JSON -- Interchange JSON -- UI JSON etc
All the transforms are JSON also
See in action here
https://www.youtube.com/watch?v=iaGGGgJdWvM&feature=youtu.be&list=PLNxHSK29ViKLrrhdPTqbYr6XGTya4uGBv&t=273

Am aware of jsonata uses in other integration technologies from #248 as well as its use in NodeRED which is very interesting, but I haven't see it in use for API transformation in that setting/with any other OS integration engine technology

So wanted to ask about 
1) the use of JSONata for API transformation & API management 
2) which OS technologies (eg NodeRed) are using it for that purpose

thanks in advance for discussion on this
Tony

PS am posting this Q here >stackoverflow as been kicked before for asking non coding Q on stackoverflow before :o(

**Comment by Allam76** [comment]
We use jsonata for precisely the same as you describe. We use it standalone with node.js

cheers Martin

**Comment by tony-shannon** [comment]
thanks Martin, good to know, so I assume you use it as is/ no other framework tooling... other than JS in Node. thanks for that

It strikes me as v suited within a nodeJS based integration framework, like qewdJS and assume there may be others..

**Comment by andrew-coleman** [comment]
Hi Tony - just done a quick search, and it looks like TreeGateway is an API management tool that uses JSONata in this way:
https://github.com/TreeGateway/tree-gateway/wiki/requestbodytransformer

JSONata itself will run in any modern Javascript environment, including Node and in the browser (the JSONata [exerciser](http://try.jsonata.org/) evaluates the expressions in _your_ browser, not on the server).

**Comment by tony-shannon** [comment]
Many thanks @andrew-coleman and again kudos on your leading work.

Thanks for the pointer to TreeGateway, looks interesting and have dropped them a line
I'm wondering about NodeRED and whether it is used there, but I guess I should ask there now.. will update here for others info.

I understand that JSONata can work nodeJS server side so I recognise its powerful potential, we're going to look closer at it.. 

Any other pointers, please do add here for now

thanks again
Tony

**Comment by tony-shannon** [comment]
Related update to this issue from the NodeRed forum can be seen here
https://discourse.nodered.org/t/anyone-using-nodered-as-json-api-transformation-tool/9821

**Comment by tony-shannon** [comment]
thanks again for the help @andrew-coleman & @Allam76 , will close this for now
