### ISSUE TITLE
Deploying website locally with registered functions

### ISSUE THREAD

**Issue by cscetbon** [jsonata-js/jsonata#327]
Can you share how we can deploy the website you provide at http://try.jsonata.org ?
I'd like to have a similar tool locally with custom registered functions.

**Comment by mattbaileyuk** [comment]
Yes, that website is known as the "exerciser" and it's fully open-sourced in a sister repo: https://github.com/jsonata-js/jsonata-exerciser

You can clone that, `npm install`, and then `npm start` to run it locally. You can deploy it to any nodeJS environment; in the case of try.jsonata.org it's actually a Cloud Foundry app on IBM Cloud, but it could equally be a Docker container in a Kubernetes environment.

**Comment by cscetbon** [comment]
Thanks @mattbaileyuk. I'll use slack for the rest of my questions.
