### ISSUE TITLE
Array functions do not appear to return an array when the resulting array has lenght 0

### ISSUE THREAD

**Issue by jhorbulyk** [jsonata-js/jsonata#328]
Consider the following input:
`["a","b","c"]`
and the following JSONata expression:
`$filter($, function($v){false})[]`
I would expect the following result:
`[]`
Instead, I get 
`undefined`

Similarly, if the input is:
`[]`
and the JSONata expression is 
`$map($, function($v){false})[]`
the result is:
`undefined`
as opposed to:
`[]`

**Comment by jhorbulyk** [comment]
> if they return undefined then applying the result sequence syntax [] afterwards does not generate an empty array.

The bug that I'm reporting is that in almost all other programming languages, these functions with these inputs should return empty arrays, not `undefined`.

**Comment by andrew-coleman** [comment]
As Matt says, these functions return sequences which are subject to sequence normlisation rules.  The docs do need to be clearer on this.  The `[]` syntax will return an array for a singleton, but not an empty array for an empty sequence.  However, your proposal (#295) for an array cast function will provide what you need.

**Comment by andrew-coleman** [comment]
Closing this issue since I believe it has been addressed in the comments.  Feel free to re-open if you believe there is a bug.
