### ISSUE TITLE
Object constructors: inconsistent result

### ISSUE THREAD

**Issue by bs-rezve** [jsonata-js/jsonata#330]
Hi,
In documentation example,
`Phone.{type: number}` gives us 

```json
[
  {
    "home": "0203 544 1234"
  },
  {
    "office": "01962 001234"
  },
  {
    "office": "01962 001235"
  },
  {
    "mobile": "077 7700 1234"
  }
]
```
Which is fine. But if in our source JSON data has only one phone number like,
```json
 "Phone": [
    {
      "type": "home",
      "number": "0203 544 1234"
    }
  ]
```
then, `Phone.{type: number}` gives back
```
{
  "home": "0203 544 1234"
}
```
It's just a single object! But we are expecting an array of object like,
```
[
  {
    "home": "0203 544 1234"
  }
]
```
Because in the documentation it says, `If an array of objects is required (one for each context value), then the object constructor should immediately follow the dot '.' operator`

 is it something that is possible to fix or am I missing something? 
Thanks

**Comment by mattbaileyuk** [comment]
While `Phone.{type: number}` can produce an array of objects, if it comes back with only one object then the standard JSONata concept that arrays with a single value are returned as just the value (see https://docs.jsonata.org/predicate#singleton-array-and-value-equivalence)

As stated there, you can ensure an array is always returned by adding `[]` at the end, as shown in http://try.jsonata.org/HJo1qgyiE which should give you the result structure you're expecting if there are 1 or many results.

**Comment by jhorbulyk** [comment]
JSONata has a feature where arrays with a single element are automatically converted to a single element.  This was recorded in earlier versions of the documentation however, I don't see it in the current documentation, though [there does seem to be a placeholder here](https://docs.jsonata.org/simple#empty-sequences-and-singleton-sequences).

That being said, one can debate the usefulness of this feature [as a lot of times it is unexpected](https://github.com/jsonata-js/jsonata/issues/328) and [currently there isn't a simple way to reverse it](https://github.com/jsonata-js/jsonata/issues/295).
