### ISSUE TITLE
Proposal: Add a "prettify" option to $string()

### ISSUE THREAD

**Issue by jhorbulyk** [jsonata-js/jsonata#334]
If one has an object that they want to render as a string in JSONata, it is possible to produce a JSON representation of that object with the [`$string()` function](https://docs.jsonata.org/string-functions#string).  However, this function produces a JSON output with minimal whitespaces which can be good for some situations but not good for others.  It would be nice if there was a way to render "prettified" JSON (one line per field, indenting based on the field depth) to the output.  Perhaps a second boolean argument to `$string()` called `prettify` might do the trick.

**Comment by jhorbulyk** [comment]
Simply adding a second argument to `$string()` isn't as straight forward as I expected since if one uses `$string()` in a hof, then the hof supplies an int as a second argument.

**Comment by andrew-coleman** [comment]
Resolved by #356
