### ISSUE TITLE
Golang port

### ISSUE THREAD

**Issue by mintbridge** [jsonata-js/jsonata#336]
Hi, 

The used to be a golang port at https://github.com/jsonata-go/jsonata but its not available any more?

Are there plans to have other language implementations?

**Comment by mattbaileyuk** [comment]
I know a Golang port was underway but I didn't realise any code had been published (and then withdrawn), or whether those projects were related.

I'm not aware of another Go port, but it looks like there is a wrapper for this JS version: https://github.com/yxuco/gojsonata

There is a Java version of JSONata which was published in GitHub not that long ago:

**Comment by andrew-coleman** [comment]
@deepilla implemented that particular Go port of JSONata.  I'm not sure what the current status is, or whether there are plans to open-source it.

**Comment by deepilla** [comment]
The jsonata-go port was a work for hire to be used as part of a larger project. While there was talk of open sourcing it at some point, there were never any concrete plans and the repo was made private some time back. There was another Go version in the works but I can't find that on GitHub any more either.

So it looks like there are no publicly available Go implementations right now. But if you were thinking about writing one, I can tell you that Andy & co were very helpful when I was writing mine.

**Comment by steffkelsey** [comment]
For any interested, we recently open sourced a port to Golang here: https://github.com/blues/jsonata-go
We have it to be about parity with v1.5.4. 
PRs welcome!

**Comment by mattbaileyuk** [comment]
@steffkelsey That's excellent to hear, and thanks for sharing here 🙂 If you're looking to discuss it further I would recommend joining our Slack community (use the link [in the top-right of the exerciser](https://try.jsonata.org/), as there has definitely been interest in a Go port there too.

**Comment by siyul-park** [comment]
I started a project to wrap the latest JS because I could no longer find the go port that was maintained.

https://github.com/siyul-park/jsonata-go
