### ISSUE TITLE
Proposal: Add function that throws exceptions

### ISSUE THREAD

**Issue by jhorbulyk** [jsonata-js/jsonata#345]
Currently JSONata evaulation involves three parts:

* Input Data which must represent valid JSON
* Output Data which must represent valid JSON
* The Expression, which is a string that conforms to valid JSONata syntax.

With the above three parts, one of the following can happen:
* Evaluation is successful and results in output data
* Evaulation is not possible, because the input data is not valid
* Evaluation is not possible because the expression does not conform to JSONata syntax
* Evaluation occurs but throws an exception because the evaluation can not be completed on the input data.  (e.g. input data is `{"foo":"bar"}` and the expression is `$number(foo)`)

It would be nice if an expression writer had a means to deliberately trigger the exception case in a controlled way.  For instance, there could be a function `$exception(msg)` that if evaluated would always throw an exception where the text of the exception message was `msg`.

**Comment by deepilla** [comment]
FYI there is an open issue for this feature [here](https://github.com/jsonata-js/jsonata/issues/167).

**Comment by jhorbulyk** [comment]
Ok.  I can close this duplicate.
