### ISSUE TITLE
Wrong addition result showing in exerciser

### ISSUE THREAD

**Issue by bs-rezve** [jsonata-js/jsonata#346]
**Input:**

```javascript
{
  "a": 12.34,
  "b": 12.34,
  "c": 9.95
}
```
**Query:**
```javascript
{
  "result": a+b+c
}
```

**Result in exerciser:**
``` javascript
{
  "result": 34.63
}
```
You  can check the sample input and output [here](http://try.jsonata.org/rJTmA2CfH)

But in node.js (v10.16.0) it gives:
``` javascript
{
  "result": 34.629999999999995
}
```

to check it quickly you can run the following code [here](https://npm.runkit.com/jsonata) 
```javascript
var jsonata = require("jsonata")
var data = {
 	"a": 12.34,
  	"b": 12.34,
  	"c": 9.95
};
var expression = jsonata("a+b+c");
var result = expression.evaluate(data);
console.log(result);
```

**Comment by andrew-coleman** [comment]
It's not the wrong result, it's just that the exerciser stringifies the JSON with reduced numeric precision:
https://github.com/jsonata-js/jsonata-exerciser/blob/master/public/scripts/exerciser.js#L287

This is done intentionally to avoid these rounding issues associated with IEEE754 floating point arithmetic

**Comment by bs-rezve** [comment]
Thanks for the response.

But why should exerciser reduced numeric precision if jsonata actually returns it ? It's impossible to know for a user who map his/her response using exerciser.

**Comment by andrew-coleman** [comment]
Because `34.63` is the correct answer to `12.34 + 12.34 + 9.95`.  A casual user who is not familiar with the inaccuracies of floating point representation will be (and have been) puzzled by seeing numbers like `34.629999999999995` appear in the output, especially since it's mathematically incorrect.
