### ISSUE TITLE
Proposal: Add an array function $single() 

### ISSUE THREAD

**Issue by jhorbulyk** [jsonata-js/jsonata#348]
.NET's LINQ contains an operator [`.Single()`](https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.single?redirectedfrom=MSDN&view=netframework-4.8#System_Linq_Enumerable_Single__1_System_Collections_Generic_IEnumerable___0__System_Func___0_System_Boolean__) which
> Returns the only element of a sequence that satisfies a specified condition, and throws an exception if more than one such element exists.

It would be convenient if JSONata had a similar function.

**Comment by andrew-coleman** [comment]
Resolved by #355
