### ISSUE TITLE
Comparison to jq

### ISSUE THREAD

**Issue by gaui** [jsonata-js/jsonata#352]
Could you be so kind to add comparison to [jq](https://stedolan.github.io/jq/)?

**Comment by andrew-coleman** [comment]
I'm not entirely sure what you are asking for, but if it's a general discussion on the relative merits of each technology, then you'd be better served by asking this on stackoverflow.  If you have a particular feature request or bug report for JSONata, then feel free to raise an issue here. 
Thanks!

**Comment by aeberhart** [comment]
@gaui, you might find some answers here:
https://medium.com/@dashjoin/jq-vs-jsonata-language-and-tooling-compared-5f0f7acc778e
