### ISSUE TITLE
IE11 issues with Meteor jsonata-es5.js

### ISSUE THREAD

**Issue by adamgins** [jsonata-js/jsonata#358]
HI, 

Awesome package JSONATA, we're using it extensively.

We're using JSONATA v `1.6.5` with Meteor 1.8.1 (Node v8.15.1) If I include the `jsonata` package and Meteor tries to do an ES5 compatible build that should work with IE11 I hit an issue https://github.com/meteor/meteor/issues/10658

The IE bug is just generic... nothing helpful

Is there some trick to get it to pickup on the ES5 code?

If I remove refs to `jsonata` package all works fine on IE11 (I hate IE :-( )

any help appreciated

thanks

https://github.com/jsonata-js/jsonata/issues/287#issuecomment-512788295

**Comment by adamgins** [comment]
ah... I got it to work add the `jsonata` to my '/imports/links` using a symbolic link `ln -s ../../node_modules/jsonata .`

**Comment by manojkr001** [comment]
@adamgins , I am also facing similar issue with angular and jsonata with IE11 , if possible could you please suggest something here to make it work in IE 11  with angular app .. [#492](https://github.com/jsonata-js/jsonata/issues/492)

**Comment by adamgins** [comment]
> #492

did the symbolic link approach not work https://github.com/jsonata-js/jsonata/issues/358#issuecomment-525228566 ?
