### ISSUE TITLE
$single function is not working in the try page.

### ISSUE THREAD

**Issue by Chengxuan** [jsonata-js/jsonata#365]
![image](https://user-images.githubusercontent.com/5425125/65016973-79aa6580-d91d-11e9-847d-87ac54044156.png)

**Comment by andrew-coleman** [comment]
Correct.  Although `$single()` has been merged into `master` branch, it has not yet been released to NPM.  The exerciser uses the most recent NPM version (currently 1.6.5).  As soon as v1.7.0 is released (hopefully soon), it will be available in the exerciser.
