### ISSUE TITLE
Proposal: Add $assert() function

### ISSUE THREAD

**Issue by jhorbulyk** [jsonata-js/jsonata#369]
Originally proposed in https://github.com/jsonata-js/jsonata/issues/167

Once JSONata has an `$error()` function, the most common use case becomes building assert statements.

Syntax:
`$assert(condition, message)`
If `condition` is true, the function returns undefined.  If the condition is false, an exception is thrown with the message as the message of the exception.

**Comment by andrew-coleman** [comment]
Resolved by #375
