### ISSUE TITLE
Key in object structure should always evaluate to a string

### ISSUE THREAD

**Issue by hannah-bulmer** [jsonata-js/jsonata#378]
Hello! It appears this might be an edge case for this rule that seems to be causing some strange behaviour in JSONata.

See this example:
http://try.jsonata.org/ryr2FtVOB

This express creates no error, but I would assume the intended output would be an error, as it is inconsistent with both the error message (`foo` returns an array) and creates some strange behaviour going forward with these results.

When adding other objects to the array that have different key values, we get the error message as intended. For example, changing the JSON to 
```JSON
[
  {"foo": "bar"},
  {"foo": "baz"},
  {"hello": "World"}
]
```
gives an error. This seems to be a bug to me, but if there is an explanation for this behaviour please let me know!

**Comment by andrew-coleman** [comment]
Which version of JSONata are you using?  When I follow your link (which uses the latest 1.7.0 release) I get the following result (error):
`Key in object structure must evaluate to a string; got: ["bar","baz"]`

This did behave differently in earlier versions, but I fixed that under [PR 363](https://github.com/jsonata-js/jsonata/pull/363).

To avoid the error, you need to explicitly map over the input array using:
`$.{foo: $}`

**Comment by andrew-coleman** [comment]
Closing - I think this is resolved.  Please re-open if you are still seeing problems.

**Comment by vijayan007** [comment]
- My case I got `Key in object structure must evaluate to a string; got: undefined`
- I don't have a key
- Is it possible to treat undefined as some default value?
