### ISSUE TITLE
GUI?

### ISSUE THREAD

**Issue by poindexd** [jsonata-js/jsonata#38]
Do you know of any GUI implementations, or plans to make any?

I am interested in building one in angular.

Excellent library! Thanks!

**Comment by andrew-coleman** [comment]
Hi - sounds good - I'd be interested in hearing what you'd like your GUI to offer.  

There is the 'JSONata exerciser' at http://try.jsonata.org/ which gives you the ability to paste in sample JSON data and run your JSONata queries against it.  There is also some excellent work that the Node-RED team have done integrating JSONata into their product as its expression language (https://nodered.org/blog/2017/01/11/version-0-16-released#jsonata).

I'd be very interested in seeing anything you create around this.  And thanks for the feedback :)

**Comment by poindexd** [comment]
Thanks for the response!

I love the syntax! Even non-technical users can learn it fairly easily. I want to create a GUI to make it even more intuitive. I am imagining an interface like this:

![example](https://cloud.githubusercontent.com/assets/5418127/23178883/0aa37940-f83a-11e6-9682-fee6dba28718.png)

> $sum(Account.Order.Product.(Price * Quantity))

The main idea is that blocks can be arranged visually to build expressions. Some of the features I am thinking about:

- Drag and drop
- Autocompletion of child nodes in path
- Dropdowns to select a different property, conditional, etc.
- Text input blocks for transformation and assignment to new properties

**Comment by andrew-coleman** [comment]
@poindexd are you still developing this? In case you are, you may be interested in the new 'robust parse' mode in v1.3 which does it's best to build an abstract syntax tree even if there are syntax errors in the expression.  This would be useful for this scenario.

Closing this issue - please re-open if you have any problems.
