### ISSUE TITLE
arbitrary code execution

### ISSUE THREAD

**Issue by travisghansen** [jsonata-js/jsonata#384]
Very cool project! I'm just starting to look into the docs etc and familiarize myself so forgive my ignorance on the subject. From what I can tell the 'functions' can only use `jsonata` specific/defined/allowed function such that arbitrary code execution is not allowed? They are not *actual* js functions?

I'm not saying it's good or bad, just want to know what I'm getting myself into for scenarios where the 'query' is potentially untrusted.

Is it safe to assume that under no circumstance/code path arbitrary code can be executed via expressions/queries?

In my case I'll be using it in a nodejs environment and want to understand the risks that could be associated with it (ie: `process.exit()` getting executed or the like).

Thanks!

**Comment by andrew-coleman** [comment]
All functions are jsonata defined.  There's no mechanism to invoke arbitrary javascript code from a jsonata expression.

**Comment by jhorbulyk** [comment]
> There's no mechanism to invoke arbitrary javascript code from a jsonata expression.

But there are mechanisms (in the outer JS environment) to bind arbitrary JS code so that it appears as a function that is call-able from inside JSONata.

**Comment by travisghansen** [comment]
Yes, understood on both fronts and that was what my understanding was. Thanks for the response!

Has anyone ever made a cli variant of the project? A jq-esque setup where input can be piped and the like.

**Comment by mattbaileyuk** [comment]
@travisghansen Yes, @blgm made `jfq` a little while back: https://www.npmjs.com/package/jfq

**Comment by loganvolkers** [comment]
@travisghansen You may want to consider adding timeboxing for your expressions, like the exerciser does: https://github.com/jsonata-js/jsonata-exerciser/blob/master/public/scripts/exerciser.js#L231

**Comment by travisghansen** [comment]
Ah I'll have a look. I'm generally dealing with very simplistic data but potentially repetitive in aggregate so across many many invocations it adds up. Some background here as an example: https://github.com/sanack/node-jq/issues/222

My similar test with jsonata results in very similar times as jsonpath...of course it's very simplistic but the overhead seems much lower than what's associated with jq as a base line. I'm sure invoking more complex queries would up things a bit but generally seems ok. I am already monitoring the open issue with this project revolving around performance :)

**Comment by andrew-coleman** [comment]
I think this has been answered.  Closing.
