### ISSUE TITLE
Proposal: add versioning information to the docs

### ISSUE THREAD

**Issue by boisei0** [jsonata-js/jsonata#385]
At the moment the documentation for JSONata does not say when functions got added/changed. As a result, when attempting to write syntax on (older) versions, I have to look up on the releases page when this functionality got added, or if it is even released already (see `$type` for a post 1.7.0 addition that is on the live docs already: http://docs.jsonata.org/object-functions#type)

Another option could be to have separate documentation for each major version, with the information matching the specific version. Still, it would be good to have information on when specific aspects got changed, for example the $reduce function for 1.7.0.

**Comment by andrew-coleman** [comment]
I agree this is needed.  The simplest solution (for me) is to use the versioning feature of docusaurus to generate separate versions of the documentation for each release (your second option).
