### ISSUE TITLE
Query place holder for sub object data

### ISSUE THREAD

**Issue by evanwellens** [jsonata-js/jsonata#389]
Been enjoying this library and was hoping there was a way to  take something like below
And extract all of the Zone names.. I tried * as a placeholder , but I don't think that does anything but wild card and didn't seem to be happy if I did
List.*.Zones.*.Name to give back 
Bath Bedroom LivingRoom

Is there a way to accomplish this with this library ?

{
	"List": {
		"0ab72b23-20e6-4e04-8770-e2fd480b8211": {
			"DeviceDetails": {
				"DeviceId": "0ab72b23-20e6-4e04-8770-e2fd480b8211",
				"Hostname": "Host1"
			},
			"Zones": {
				"Zone1": {
					"Name": "Bath"
				}

			}

		},
		"0ab72b23-20e6-4e04-8770-e2fd480b2222": {
			"DeviceDetails": {
				"DeviceId": "0ab72b23-20e6-4e04-8770-e2fd480b2222",
				"Hostname": "Host2"
			},

			"Zones": {
				"Zone1": {
					"Name": "Bedroom"

				},
				"Zone2": {
					"Name": "Livingroom"

				}

			}
		}
	}
}

**Comment by andrew-coleman** [comment]
The expression `List.*.Zones.*.Name` 
returns `["Bath", "Bedroom", "Livingroom"]`.  
Is that what you wanted?
See http://try.jsonata.org/BJ3bLdG2S

**Comment by evanwellens** [comment]
Wow that is awesome.. Thanks!!
