### ISSUE TITLE
Transform error with null values

### ISSUE THREAD

**Issue by Alkarex** [jsonata-js/jsonata#396]
Hello,
I believe this is an error:

Input:

```json
{
  "hi": "world",
  "bye": null
}
```

Transform:

```js
$ ~> | ** ["hi"] | {"hello": hi}, ["hi"] |
```

Output with http://try.jsonata.org :

```
u is null
```

Instead, I would expect the following output:

```json
{
  "bye": null,
  "hello": "world"
}
```

**Comment by andrew-coleman** [comment]
Certainly it's a bug that you are getting a non-jsonata error bubbling up from the evaluator.  I'll fix that.

However, to get the result you want, the predicate on the descendent wildcard (**) needs to be the path/property `hi`, not the string literal `"hi"`.  The following expression will work for you:

`$ ~> | ** [hi] | {"hello": hi}, ["hi"] |`

See http://try.jsonata.org/B1NqQGUAB

**Comment by Alkarex** [comment]
@andrew-coleman Thanks for the feedback! Ok, I thought the two forms were equivalent.
