### ISSUE TITLE
Remove array entries with object transform operator?

### ISSUE THREAD

**Issue by johnsusek** [jsonata-js/jsonata#404]
Hello, thank you for JSONata! I am not sure if this is a feature request, or if I am just missing something... Basically I want to filter an array of objects within my data, but return the entire surrounding data structure back (minus what I've filtered out). 

When I saw the object transform operator I thought that that is what I need, but it doesn't appear to be able to remove array entries, only keys from objects. 

http://try.jsonata.org/SJbKhL9WL

Here's what I've tried to far:

This kind of works, but only removes the keys from the results, not the results themselves:

`$ ~> | feed[0].entry[][$not(title ~> /iPhone/)] | { }, ['title', 'link', 'id', 'published', 'updated', 'author', 'content'] |`

This returns the right entries, but not the rest of the feed:
```
$filter(feed[0].entry, function($v, $i, $a) {
  $v.title ~> /iPhone/
})
```
This returns exactly what I need, but I have to hard code the surrounding JSON:

```
{
  "feed": [
    {
      "#attr_xmlns": "http://www.w3.org/2005/Atom",
      "title": "Daring Fireball",
      "subtitle": "By John Gruber",
      "link": [
        {
          "#attr_rel": "alternate",
          "#attr_type": "text/html",
          "#attr_href": "https://daringfireball.net/"
        },
        {
          "#attr_rel": "self",
          "#attr_type": "application/atom+xml",
          "#attr_href": "https://daringfireball.net/feeds/main"
        }
      ],
      "id": "https://daringfireball.net/feeds/main",
      "updated": "2020-01-24T23:46:57Z",
      "rights": "Copyright © 2020, John Gruber",
      "entry": feed.entry[title ~> /iPhone/]
    }
  ]
}
```

Is there a way to remove array entries like I am trying to do, using the object transform operator?

Thanks again!

**Comment by markmelville** [comment]
The key to the solution is what you did there when you manually copied the structure but then replaced the "entry" property with a new expression. The transformation operator does this, and what's really cool is that it is yields a function, therefore it can be passed in to higher order functions such as `$map`. 

Is this the output you want? It will do it for every item in the feed.
```
{
	'feed': $map(feed,|$|{ 'entry': entry[title ~> /iPhone/]}|)
}
```

**Comment by johnsusek** [comment]
@markmelville Very cool, thanks for that! This indeed does what I want, I just had to wrap `feed` in brackets since it is an array in the input

```
{
	'feed': [$map(feed,|$|{ 'entry': entry[title ~> /and/]}|)]
}
```

The only issue now is that "entry" becomes an object when there is a single result, but it is an array in the input

**Comment by johnsusek** [comment]
Actually I figured it out, I just had to do this:

```
{
	'feed': [$map(feed,|$|{ 'entry': [entry[title ~> /and/]]}|)]
}
```

Thanks again
