### ISSUE TITLE
Is there a way to assign a Jsonata function?

### ISSUE THREAD

**Issue by markmelville** [jsonata-js/jsonata#406]
I want to add several "helper functions" to my jsonata expressions. For example, take this expression evaluated against the Invoice model:
```
Account.(`Account Name` & ' is ' & [status,'active'][0])
```
yields: `"Firefly is active"`

I can write a function with the neat transformation syntax and do this:
```
(
  $cancel:=| $ | {'status':'cancelled'} |;
  $cancel(Account).(`Account Name` & ' is ' & [status,'active'][0])
)
```
which yields: `"Firefly is cancelled"` :(

I am trying to add such extension functions, which are written in Jsonata, using assign. But assign only accepts a literal or a javascript function. I want to do something like this:
```
let expr = jsonata("$cancel(Account).(`Account Name` & ' is ' & [status,'active'][0])");
let function = jsonata("| $ | {'status':'cancelled'} |");
expr.assign("cancel", function);
expr.evaluate(invoice);
```
I've tried using a few of the compiled function's internals which I spied. Still no luck.
```
expr.assign("cancel", function.evaluate);
expr.assign("cancel", function.implementation);
expr.assign("cancel", function.apply);
```
Is it possible to do? Thanks.

**Comment by markmelville** [comment]
The alternate approaches I'm exploring are:
1) just concatenate one big string :
```
let expression = "$cancel(Account).(`Account Name` & ' is ' & [status,'active'][0])"
let functions = {cancel: "| $ | {'status':'cancelled'} |"};
jsonata("("+Object.entries(functions).map(([k,v])=>`$${k}:=${v}`).join(";")+";"+expression+")");
```
2) wrap the invocation of a compiled expression in an arrow function:
``
let f = "| $ | {'status':'cancelled'} |";
let cancel = jsonata("($f:=" + f + ";$f($))");
expr.assign("cancel",i=>aug.cancel(i));
```
which works, but only for 1-arg functions

**Comment by andrew-coleman** [comment]
Going back to your original code, it works if you add `.evaluate()` to the function you are defining:

```
let expr = jsonata("$cancel(Account).(`Account Name` & ' is ' & [status,'active'][0])");
let func = jsonata("| $ | {'status':'cancelled'} |").evaluate();
expr.assign("cancel", func);
expr.evaluate(invoice);
```

**Comment by markmelville** [comment]
Makes sense. The bindings must be JavaScript constructs, and the way to turn a Jsonata function to a Javascript function is not to compile it, but to evaluate it.

Thanks, Andrew!
