### ISSUE TITLE
Writing higher-order extension functions

### ISSUE THREAD

**Issue by markmelville** [jsonata-js/jsonata#410]
I'm trying out different kinds of custom extension functions. Here's a basic higher-order function that does exactly what `$map` does:
```
let expr = jsonata("$loop([1,2,3],function($i){$i*2})");
```
I hoped the implementation of `$loop` would be something like:
```
expr.assign("loop", (items, func) => items.forEach(func));
// expected output
[2,4,6]
```
But seeing that that the func passed to javascript is a generator function, I did this:
```
expr.assign("loop", (items, func) => items.map(item=> {
    let values = Array.from(func(item));
    console.log(`input ${item} => ${values}`);
    return values;
}));
```
Each invocation of the generator apparently yields the function's operands, rather than returning the result of the evaluation.
```
// logged:
input 1 => 1,2,
input 2 => 2,2,
input 3 => 3,2,
// return value
[ [ 1, 2, undefined ], [ 2, 2, undefined ], [ 3, 2, undefined ] ]
```
Is it a pipe dream to be able to write custom HOFs?

**Comment by andrew-coleman** [comment]
Does this help?...
https://github.com/jsonata-js/jsonata/blob/master/test/implementation-tests.js#L510

**Comment by markmelville** [comment]
It's a starting point, but I keep hitting limitations. What I want to do is make a user defined function that will iterate items in an array, and apply each one to the `fn`. If that returns a promise because function is async then I want to await that promise before applying the next value from the array. So this seems like the implementation:
```
var myfunc = async function*(arr, fn) {
    let result = [];
    for (let item of arr) {
        result.push(await (yield * fn(item)));
    }
    return result;
};
```
Thing is, though async functions work and generator functions work, async generator functions don't seem to work. console logs don't output and evaluate just returns `Object [AsyncGenerator] {}`.

I've tried a version that doesn't use async/await but instead uses `.then`, but with generator functions the yield has to be enclosed in a function, but the engine doesn't seem to like that either. For example trying to iterate the array and apply values to the function with `Array.map`:
```
    return arr.map(function*(i) {
        return yield * fn(i);
    });
```
It returns an array of generators:
```
[ Object [Generator] {}, Object [Generator] {}, Object [Generator] {} ]
```
These are the kinds of roadblocks I keep hitting.

**Comment by markmelville** [comment]
I figured out a way to do it! Admittedly I don't have much experience with generator functions, but it was clear that I needed to find a way to invoke them without the `yield*` syntax. I found that with a utility function to "fulfill" the generator function like this:
```
function fulfull(iterator) {
    function doNext(arg) {
        const next = iterator.next(arg);
        return next.done ? next.value : Promise.resolve(next.value).then(doNext);
    }
    return doNext();
}
```
I could then write a promise chain like so:
```
var myfunc = function(arr, fn) {
    let output = [];
    if (arr.length == 0) return output;
    var p = Promise.resolve(fulfull(fn(arr[0])));
    for (let i=1; i<arr.length; i++) {
        p = p.then(result => {
            output.push(result);
            return fulfull(fn(arr[i]));
        });
    }
    return p.then(result=>{output.push(result); return output});
};
```
this works with a simple function like `$myfunc([1,2,3], function($i){$i})`, returning `[1,2,3]` immediately, or with a fake async function like:
```
expr.registerFunction('delay', (ms, val) => new Promise(r => setTimeout(() => r(val),ms)));
```
I can run `$myfunc([1,2,3], function($i){$delay(500,$i)})` which returns `[1,2,3]` after a 1.5 second delay.

I'll resolve this issue, but it might be good to add test cases for more examples, and maybe even add some user-defined function implementation tips to the docs. I'm willing to submit PRs.

**Comment by markmelville** [comment]
or even better now that async/await is back on the table:
```
async (arr, fn) => {
    let output = [];
    for (let i=0; i<arr.length; i++) {
        output.push(await fulfull(fn(arr[i])))
    }
    return output;
}
```
Much simpler

**Comment by andrew-coleman** [comment]
That's great news.  PRs for extra test cases and improved documentation would be very gratefully received.  Thanks!
