### ISSUE TITLE
Error when trying to get invitation for slack channel

### ISSUE THREAD

**Issue by Maurice22** [jsonata-js/jsonata#412]
When entering my email address and checking the captcha on the try.jsonata.org page, there is an error saying that no server with the hostname was found. Has your hostname perhaps changed and it was not updated in the script?

Cheers Maurice

**Comment by mattbaileyuk** [comment]
@andrew-coleman has been playing around with the websites to sort out certs for https endpoints and upgrade the exerciser (try.jsonata.org), so it could be related. However, I tried it just now and was able to successfully get an invite to a new address; it might have been some error somewhere in the chain at the time, so please try again and hopefully it will work for you now.

**Comment by Maurice22** [comment]
Hi @mattbaileyuk, I tested it again and it is still not working. Looks like the javascript is trying to access the following endpoint: https://c40c296d.us-south.apigw.appdomain.cloud/api/slack but I can't reach the host (not even ping it). Could there be a region restriction of some kind? I'm in Europe.

**Comment by mattbaileyuk** [comment]
@Maurice22 I am in the UK and I'm able to reach the endpoint on my home, work and mobile networks (and get the "Error: Whoops. Verb not supported." message in a browser as `GET` isn't supported), so I'm not sure what to recommend. I was also able to ping the endpoint. Maybe it's being blocked by your ISP or corporate network? If possible, it might be worth trying to change DNS settings.

**Comment by Maurice22** [comment]
@mattbaileyuk You were right! It seems as if the hostname was not correctly resolved by the DNS. Switched the DNS server and was working now. Thanks for your help!
