### ISSUE TITLE
Is it possible to pass multiple values under IN  Comparison expressions Like  "01962 001234", "01962 001235"in Phone.number

### ISSUE THREAD

**Issue by manojkr001** [jsonata-js/jsonata#414]
Is it possible to pass multiple values under IN  Comparison expressions Like  
"01962 001234", "01962 001235" in Phone.number.

This is a valid expression **"01962 001235" in Phone.number** where we can pass one value under IN 
Comparison expressions. But I am looking for a way where we can pass multiple value under IN 
Comparison expressions like  **"01962 001234", "01962 001235" in Phone.number**. Kindly suggest if there is any way to achieve this functionality.

Thanks

**Comment by markmelville** [comment]
Absolutely. I'm assuming you want to check if each value is in the set. Wrap the values in an array and you can use `$map`:
```
$map(["01962 001234", "01962 001235"], function($value){ $value in Phone.number })
```
which outputs `[true,true]`

If there is a more elegant syntax, I am not aware of it. If you want something else such as an "any" or "all" function, that is doable as well.

**Comment by andrew-coleman** [comment]
The map operator `.` can also be used for a slightly more compact syntax:

`["01962 001234", "01962 001235"].($ in $$.Phone.number)`

which does the same as above. 
https://try.jsonata.org/ECQip0b6

**Comment by manojkr001** [comment]
> Absolutely. I'm assuming you want to check if each value is in the set. Wrap the values in an array and you can use `$map`:
> 
> ```
> $map(["01962 001234", "01962 001235"], function($value){ $value in Phone.number })
> ```
> 
> which outputs `[true,true]`
> 
> If there is a more elegant syntax, I am not aware of it. If you want something else such as an "any" or "all" function, that is doable as well.

Thanks @markmelville  for the Quick response and solution. I am for the expression which will match any element from the given set and return **true** if any one of the element from the set match otherwise **false**.

**Comment by andrew-coleman** [comment]
`["01962 00134", "01962 00125"].($ in $$.Phone.number)  ~> $boolean()`

See https://docs.jsonata.org/boolean-functions#boolean

**Comment by manojkr001** [comment]
> `["01962 00134", "01962 00125"].($ in $$.Phone.number) ~> $boolean()`
> 
> See https://docs.jsonata.org/boolean-functions#boolean

Thanks a lot @andrew-coleman  for the quick response and solution :)

**Comment by loganvolkers** [comment]
```
(
   $overlaps := function($a, $b){ $a.($ in $b) ~> $boolean() };

   Phone.number ~> $overlaps(["0203 544 1234", "01962 00125"])
)
```
As a reusable function

**Comment by manojkr001** [comment]
Thanks @loganvolkers
