### ISSUE TITLE
Bower doesn't find jsonata.js 

### ISSUE THREAD

**Issue by fantonangeli** [jsonata-js/jsonata#417]
Hello there!
In my project (Grunt+Bower ) "grunt wiredep" doesn't put the script in the index.html.
I see that in the bower.json of jsonata there is the  'main": "jsonata.js"' but there is no file jsonata.js
To use jsonata I downgraded to the 1.5.4 version.

If you want I'll be happy to compile the file and make a PR.
Just let me know :-)

**Comment by andrew-coleman** [comment]
I think this can be closed given the discussion in the PR
