### ISSUE TITLE
Does jsonata expression support "Between" keyword to filter record based on two dates 

### ISSUE THREAD

**Issue by manojkr001** [jsonata-js/jsonata#419]
Does jsonata expression support "Between" keyword to filter records based on two given dates or two given number.

Thank you,

**Comment by mattbaileyuk** [comment]
I'm always expecting to be outdone by a more clever expression on here... but I will offer that you can use blocks of [predicate expressions](https://docs.jsonata.org/predicate) to filter both above and below, e.g. https://try.jsonata.org/D4UzwlEH

**Comment by manojkr001** [comment]
@mattbaileyuk  Thank you for the quick response and solution.

Does this type of date comparison support all date format, I mean here we are passing the date in single quote which would be string. I was trying this expression with some different date format. Below are the expression and results 

Input json 
`{
    "Product": [
        {
            "Date": "2020-02-20",
            "Product Name": "Bowler Hat"
        },
        {
            "Date": "2020-02-21",
            "Product Name": "Trilby hat"
        },
        {
            "Date": "2020-02-22",
            "Product Name": "Bowler Hat"
        },
        {
            "Date": "2020-02-23",
            "Product Name": "Cloak"
        }
    ]
}`

Expression 

Product.Date[$ > '2020-02-20']
[$ < '2020-02-23']

Result 

[
  "2020-02-21",
  "2020-02-22"
]

2.  
Input json

{
    "Product": [
        {
            "Date": "2020-02-20T00:00:00.000Z",
            "Product Name": "Bowler Hat"
        },
        {
            "Date": "2020-02-21T00:00:00.000Z",
            "Product Name": "Trilby hat"
        },
        {
            "Date": "2020-02-22T00:00:00.000Z",
            "Product Name": "Bowler Hat"
        },
        {
            "Date": "2020-02-23T00:00:00.000Z",
            "Product Name": "Cloak"
        }
    ]
}

expression 

Product.Date[$ > '2020-02-20T00:00:00.000Z'][$ < '2020-02-23T00:00:00.000Z']

Result 

[
  "2020-02-21T00:00:00.000Z",
  "2020-02-22T00:00:00.000Z"
]
 3. input 

{
    "Product": [
        {
            "Date": "Thu Feb 20 00:00:00 IST 2020",
            "Product Name": "Bowler Hat"
        },
        {
            "Date": "Fri Feb 21 00:00:00 IST 2020",
            "Product Name": "Trilby hat"
        },
        {
            "Date": "Sat Feb 22 00:00:00 IST 2020",
            "Product Name": "Bowler Hat"
        },
        {
            "Date": "Sun Feb 23 00:00:00 IST 2020",
            "Product Name": "Cloak"
        }
    ]
}

expression 

Product.Date[$ > 'Thu Feb 20 00:00:00 IST 2020'][$ < 'Sun Feb 23 00:00:00 IST 2020']

Result 

**NO Matches**   

It should return two match rows.

kindly suggest

**Comment by markmelville** [comment]
The date sort works on the the ISO 8601 standard because its string format makes it sort lexographically. The recommendation is to use that format. The `picture` argument of the date time functions allows conversion from and to non-standard formats:
```
(
    $fromOtherFormat:=function($s){$toMillis($s,'[FNn,*-3] [MNn,*-3] [D] [H]:[m]:[s] IST [Y]')~>$fromMillis()};
    Product.Date[$fromOtherFormat($) > $fromOtherFormat('Thu Feb 20 00:00:00 IST 2020')][$fromOtherFormat($) < $fromOtherFormat('Sun Feb 23 00:00:00 IST 2020')]
)
```

**Comment by mattbaileyuk** [comment]
@markmelville Thanks, you got there before me 🙂

It's what I like about ISO8601 dates, that you can just sort them logically without having to do special treatment for date/time sorting.

**Comment by manojkr001** [comment]
@markmelville and @mattbaileyuk  Thank you for the response and clarifications
