### ISSUE TITLE
Should the $split() function accept a regex separator?

### ISSUE THREAD

**Issue by shrickus** [jsonata-js/jsonata#42]
In the JSONata Exerciser, using the default JSON data structure, I am able to use the expression
`Account.Order.Product."Product Name".$split($, /[ ,.\n]+/)`
to generate a list of words used in the Product Names. Using a regex is a great feature, since not all strings can be split on just a list of characters.

While the string_functions.html documentation states that this feature is available, the functions.md file does not allow this:
>The optional separator parameter specifies the characters within the str about which it should be split. If separator is not specified, then the empty string is assumed, and str will be split into an array of single characters. It is an error if separator is not a string.

Is the regex feature newer than the docs?  The reason I'm asking is that the ace editor embedded in node-red uses the ace/mode/jsonata validators (rules?) that will not allow me to use a regex. I'm not seeing where that validation occurs in node-red, so I'm just wondering if it requires a change in either this library or the Ace editor library. Thanks for any help on who to contact to enable this feature in node-red.

**Comment by andrew-coleman** [comment]
The new regex support, together with the upgrade of function $split was introduced in JSONata version 1.1.0.  The latest version (0.16.2) of Node-RED currently uses version 1.0.10.  @knolleary will be able to advise on how the Ace editor does its validation.

The latest docs are at http://docs.jsonata.org, and the function section of this is up to date.  I do need to do a lot more work documenting the rest of the language.

Apologies for the functions.md file.  That is out of date.  I will remove it and point to the website.

**Comment by andrew-coleman** [comment]
Ouch!  Thanks for reporting that.  Should be back up now

**Comment by andrew-coleman** [comment]
closing issue

**Comment by knolleary** [comment]
Just for completeness, I've now updated node-red to the latest jsonata release. Regex support will be available in our next release (either 0.16.3 or 0.17).
