### ISSUE TITLE
Need a way to chunk an array

### ISSUE THREAD

**Issue by adityapant1286** [jsonata-js/jsonata#424]
Currently, there is no option to chunk an array of elements to multiple arrays. Or break some iteration. Is it possible to add one?

**Comment by jhorbulyk** [comment]
```
(
    $chunkArray := function ($array, $chunkSize) {(
        $arrayLength := $count($array);
        $numChunks := $ceil($arrayLength / $chunkSize) ;
        [0..$numChunks-1] ~> $map(function($chunkNumber){
            $array ~> $filter(function($element, $index){
                $chunkNumber*$chunkSize <= $index and $index < ($chunkNumber + 1) * $chunkSize
            })
        })
    )};
    $chunkArray(array, 3)
)
```
Seems to do what you want.
Sample input:
```
{"array": [
  0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10
]}

Sample output:
```
[
  [
    0,
    1,
    2
  ],
  [
    3,
    4,
    5
  ],
  [
    6,
    7,
    8
  ],
  [
    9,
    10
  ]
]
```
```

**Comment by adityapant1286** [comment]
**This is absolutely fantastic Jacob.** 

I tried using $each() function earlier but there wasn't option to break the loop and recursion was messy/suitable only for limited array length. Thought about the tail-call pattern, but it was so much just to chunk an array.

_Your solution is much cleaner._

**Comment by alexiswl** [comment]
This is great! I've made a slight modification so that if the final chunk is of size one, it is still an array

See https://try.jsonata.org/J31V0YuJB as an example


## Inputs

```json
[
  "apples",
  "bananas",
  "oranges",
  "pineapples"
]
```

## Bindings

```json
{
  "chunkSize": 3
}
```

## JSONata

```jsonata
(
    $chunkArray := function ($array, $chunkSize) {(
        $arrayLength := $count($array);
        $numChunks := $ceil($arrayLength / $chunkSize) ;
        [0..$numChunks-1] ~> $map(function($chunkNumber){
            [
                $array ~> $filter(function($element, $index){
                    $chunkNumber*$chunkSize <= $index and $index < ($chunkNumber + 1) * $chunkSize
                })
            ]
        })
    )};
    $chunkArray($, $chunkSize)
)
```

## Output

```json
[
  [
    "apples",
    "bananas",
    "oranges"
  ],
  [
    "pineapples"
  ]
]
```

Output from @jhorbulyk 

Gives

```json
[
  [
    "apples",
    "bananas",
    "oranges"
  ],
  "pineapples"
]
```
