### ISSUE TITLE
How to extend an object with extra key-value pairs without explicitly copying all the existing key-value pairs ?

### ISSUE THREAD

**Issue by janvda** [jsonata-js/jsonata#425]
I am frequently using the excellent jsonata library to extend objects with extra key - value pairs.

I know how to do this.
E.g. If I want to add the key:value `"NEW FIELD" : "VALUE OF NEW FIELD"` to the `"Account"` object of the `Invoice` (https://try.jsonata.org/) then I can easily do that with following query:
```
{ 
    "Account" : Account.
      {
          "Account Name": `Account Name`,
          "Order": Order,
          "NEW FIELD" : "VALUE OF NEW FIELD"
      }
}
```

The problem with that approach is that I need to explicitly copy the 2 existing key-value pairs of that object (i.e. `"Account Name"` and `"Order"`).

Is there a way to do this without explicitly copying all the existing key-value pairs ?

**Rationale for this request:**
1. This would make my jsonata query independent of all the existing key-value pairs.
2. If an object has many key-value pairs then my jsonata query will not be that big as I won't have all the code to explicitly copy all those existing key-value pairs.

**Comment by jhorbulyk** [comment]
What about
```
{ 
    "Account" : $merge([Account,
      {
          "NEW FIELD" : "VALUE OF NEW FIELD"
      }])
}
```

**Comment by andrew-coleman** [comment]
Or this
```
$ ~> | Account | { "NEW FIELD": "VALUE OF NEW FIELD"} |
```

**Comment by janvda** [comment]
Thanks a lot - exactly what I was looking for.
