### ISSUE TITLE
Question: How to join by key?

### ISSUE THREAD

**Issue by drpicox** [jsonata-js/jsonata#426]
Given the following data:

```json
{
   "favorites":[
      "post1"
   ],
   "posts":{
      "post1":{
         "author":"user1",
         "body":"......"
      },
      "post2":{
         "author":"user2",
         "body":"......"
      },
      ...
   }
}
```

How can I generate the join between favorites and posts? The result would be:

```json
[
   {
      "author":"user1",
      "body":"......"
   }
]
```

Is there any shorthand?

Thanks in advance,

**Comment by andrew-coleman** [comment]
`favorites@$F.posts.$lookup($F)`

https://try.jsonata.org/jwyf0zMt

**Comment by drpicox** [comment]
Thanks!

I cannot believe it. More than one hour looking to the documentation and I missed completely: https://docs.jsonata.org/object-functions.html

Thanks!
