### ISSUE TITLE
Update deeply nested property - transform 

### ISSUE THREAD

**Issue by bakman2** [jsonata-js/jsonata#439]
Apologies that this is not a _real_ issue related to JSONata, but my misunderstand of its inner works (or maybe it is)

Consider following object:

```
{
  "ipaddress": "10.0.0.218",
  "network": {
    "children": [
      {
        "children": [
          {
            "children": [
              {
                "children": [
                  {
                    "name": "iMac",
                    "properties": {
                      "ip": "10.0.0.217",
                      "reachable": false
                    }
                  },
                  {
                    "name": "XPenology NAS",
                    "properties": {
                      "ip": "10.0.0.200",
                      "reachable": false
                    }
                  },
                  {
                    "name": "Laser Printer",
                    "properties": {
                      "ip": "10.0.0.100",
                      "reachable": false
                    }
                  }
                ],
                "name": "SWITCH_CF2",
                "properties": {
                  "ip": "10.0.0.3",
                  "reachable": false
                }
              },
              {
                "name": "Home Automation Server",
                "properties": {
                  "ip": "10.0.0.6",
                  "reachable": false
                }
              }
            ],
            "name": "SWITCH_CF1",
            "properties": {
              "ip": "10.0.0.2",
              "reachable": false
            }
          },
          {
            "children": [
              {
                "name": "espressif",
                "properties": {
                  "ip": "10.0.0.218",
                  "reachable": false
                }
              },
              {
                "name": "Sonoff Bridge",
                "properties": {
                  "ip": "10.0.0.26",
                  "reachable": false
                }
              },
              {
                "name": "Sonoff - Printer Power",
                "properties": {
                  "ip": "10.0.0.232",
                  "reachable": false
                }
              },
              {
                "name": "NL0130",
                "properties": {
                  "ip": "10.0.0.234",
                  "reachable": false
                }
              }
            ],
            "name": "UBNT AP",
            "properties": {
              "ip": "10.0.0.230",
              "reachable": false
            }
          }
        ],
        "name": "UBNT ERX",
        "properties": {
          "ip": "10.0.0.1",
          "reachable": false
        }
      }
    ],
    "name": "Internet",
    "properties": {
      "ip": "google.com",
      "reachable": false
    }
  },
  "state": true
}
```

General idea: find `ipaddress` in `ip` and set `reachable` to the `state` value, while keeping the network object in tact.

I ended up with a transform expression:

```
**.network ~>| *.properties[$contains(ip,$$.ipaddress)] |{"reachable":$boolean($$.state)} |
```
This sometimes works, sometimes doesn't. I use `$$.ipaddress` and wonder if that correct, something like `**.ipaddress` (?) but jsonata does not accept it.

Can anyone perhaps steer me in the right direction ?

**Comment by andrew-coleman** [comment]
You're nearly there.  I think this does what you want:

```
network ~>| **.properties[$contains(ip,$$.ipaddress)] |{"reachable":$boolean($$.state)} |
```

See https://try.jsonata.org/jAS6Kqp5b

**Comment by bakman2** [comment]
@andrew-coleman nice, thanks a lot for the quick response! Still some issues 😬

The first element:

```
"name": "Internet",
    "properties": {
      "ip": "google.com",
      "reachable": false
    }
```
does not want to update.

![Screenshot 2020-04-23 at 16 17 08](https://user-images.githubusercontent.com/333960/80109725-1d2bba80-857e-11ea-99c3-d0086118d229.jpg)

and same for some nested child, I am not really understanding the randomness.

![Screenshot 2020-04-23 at 16 16 41](https://user-images.githubusercontent.com/333960/80109728-1ef57e00-857e-11ea-8a49-65bb39e2736d.jpg)

**Comment by andrew-coleman** [comment]
Did you follow the link I gave to the exerciser (https://try.jsonata.org/jAS6Kqp5b)?
It shows that the only item that gets set to `"reachable": "true"` is the one named "expressif", and that's because its `ip` property matches the top level `ipaddress` (10.0.0.218).  I was working with the data you pasted earlier.

I'm not sure where these screenshots you are showing me come from.

**Comment by bakman2** [comment]
Yes the try link is almost my homepage ;)

There is something going on in node-red that is not updating the object properly. In the excerciser it works all fine. I will investigate some more. Thanks a lot for the quick hints and support.

**Comment by bakman2** [comment]
I see what went wrong, I had to use the $globalContext object as input instead of the network object that I passed through. Thanks again.
