### ISSUE TITLE
Custom Sort Order

### ISSUE THREAD

**Issue by sindhuchinthalapally** [jsonata-js/jsonata#441]
Hi,
I have this sample json below and I would like to sort the list based on a specific sort order. 
For example: 
I want to sort the status in this order. New, Draft, In Progress, Closed, Deferred

How can I do it? Any help would be really appreciated. 

Input: 
```
{
  "issues": [
    {
      "status": "Closed",
      "title": "Bug 1"
    },
    {
      "status": "Draft",
      "title": "Story 2"
    },
    {
      "status": "In Progress",
      "title": "Bug 2"
    },
    {
      "status": "New",
      "title": "Story 1"
    },
    {
      "status": "Deferred",
      "title": "Bug 3"
    }
  ]
}
```

Output
```
{
  "issues": [
    {
      "status": "New",
      "title": "Story 1"
    },
    {
      "status": "Draft",
      "title": "Story 2"
    },
    {
      "status": "In Progress",
      "title": "Bug 2"
    },
    {
      "status": "Closed",
      "title": "Bug 1"
    },
    {
      "status": "Deferred",
      "title": "Bug 3"
    }
  ]
}
```

**Comment by markmelville** [comment]
I would use a map to resolve statuses to a logical ordering. Then it's easy to write a custom sort function:
```
(
    $statuses:={
        "New":1,
        "Draft":2,
        "In Progress":3,
        "Closed":4,
        "Deferred":5
    };
    $~>|$|{"issues":$sort(issues,function($a,$b){
        $lookup($statuses,$a.status) > $lookup($statuses,$b.status)})
    }|
)
```
https://try.jsonata.org/q1mBhza2b

**Comment by andrew-coleman** [comment]
Yes, and you could generate this map dynamically from the ordered array (and use the order-by operator):

```
(
    $states := ['New', 'Draft', 'In Progress', 'Closed', 'Deferred'];
    $table := $states#$i{$:$i};
    issues^($lookup($table, status))
)
```

https://try.jsonata.org/E2bONf0Ep

**Comment by markmelville** [comment]
Leave it to @andrew-coleman to provide the more elegant expression!
1) the table could be inlined, right?
```
$table := ['New', 'Draft', 'In Progress', 'Closed', 'Deferred']#$i{$:$i};
```
2) Tangent for which I should probably make a separate request. I wish there were an operator for $lookup. I just think it would be great to make this expression something like:
```
issues^$table[status]
```
where parens would not needed because of some order-of-operations. I know `[]` is used for array filtering, so not necessarily that, but could you think of a way to make it work, Andrew? I ask because you brought the transformation operator to life.

**Comment by andrew-coleman** [comment]
> the table could be inlined, right?

Yes
> I wish there were an operator for $lookup

I'll give it some thought.  I'm running a bit low on available tokens.

**Comment by andrew-coleman** [comment]
I'm going to close this as resolved.  

@sindhuchinthalapally, hope the above helps.  Feel free to join the slack channel for general questions (link in the [Exerciser](https://try.jsonata.org/)), or [stackoverflow](https://stackoverflow.com/tags/jsonata).

**Comment by dirajkumar** [comment]
@markmelville @andrew-coleman. This is awesome thanks a lot for the code.
