### ISSUE TITLE
with arrays of arrays can a path return inner arrays unmerged?

### ISSUE THREAD

**Issue by darrencruse** [jsonata-js/jsonata#444]
using try.jsonata.org I was trying to work out an expression selecting "b" below that would return the "b" arrays unchanged rather than merging the "b" arrays:
```
{
  "a": [
    {
      "b": [1, 2]
    },
    {
      "b": []
    }
  ]
}
```
here is my playground if it helps: https://try.jsonata.org/m23ZPfQin

so "a.b" returns:
```
[
  1,
  2
]
```
I know my example is abstract but my issue is that in my real data this would mean something different than the above yet it returns exactly the same thing:
```
{
  "a": [
    {
      "b": [1]
    },
    {
      "b": [2]
    }
  ]
}
```
as does this:
```
{
  "a": [
    {
      "b": [1, 2]
    }
  ]
}
```
this put me in mind of the square bracket operator so still using this last shortened example I tried "a.b[]" which left me encouraged that it gave this:
```
[
  [
    1,
    2
  ]
]
```
example here:  https://try.jsonata.org/LlHSLk4Mm

But going back to my original 2 element input with the "a.b[]" the output went back to being flattened(!?) i.e. back to this again:
```
[
  1,
  2
]
```
example here:  https://try.jsonata.org/B03lNDW6d

I guess at this point I'm confused if that's a bug in the [] syntax or if I'm confused how it works...

(the way I was thinking about it is that [] would be the way I could convey to jsonata that the array merging shouldn't/can't be done in my situation I just want it to return me the "b" array values exactly as they are)

**Comment by jhorbulyk** [comment]
Using the $map() function can break out of the array flattening problems that can be introduced by the basic selection. (e.g. `a ~> $map(function($a) {$a.b})`)

**Comment by darrencruse** [comment]
Thanks Jacob

The truth is in our app we have a mix of non-technical and semi-technical users who are non-programmers that we were hoping could use jsonata expressions as kind of a better more powerful version of something like jsonpath

i.e. the need for calling $map like the above we hoping/wishing/crossing-our-fingers would not be needed

**Comment by andrew-coleman** [comment]
Hi Darren,  to return the "arrays of b's", use the following:
```
a.[b]
```

That will return:
```
[
  [
    1,
    2
  ],
  []
]
```
https://try.jsonata.org/UeoSV-7zU

**Comment by darrencruse** [comment]
Thanks I had seen this sorry I forgot to reply

and I do see it now in the docs this is like "each email object generates an array of addresses" somehow I'd overlooked it:
https://docs.jsonata.org/construction#array-constructors

**Comment by darrencruse** [comment]
not sure what the etiquette is but I notice I can close this issue

(and I feel a little bad for these issues where I'm just struggling to understand certain bits of JSONata)

so closing
