### ISSUE TITLE
duplicates on parent backtracking

### ISSUE THREAD

**Issue by sadams-rti-org** [jsonata-js/jsonata#445]
Trying:  **.*.find_me.%.%
On:
{
    "parameters": {
      "steps": {
        "find_me": 1
      },
      "speed": {
        "find_me": 2
      }
    },
    "go": {
      "very": {
        "deep": {
          "parameters": {
            "sight": {
              "find_me": 3
            },
            "angle": {
              "find_me": 4
            }
          }
        }
      }
    }
  }
Yields:
  [
    {
      "steps": {
        "find_me": 1
      },
      "speed": {
        "find_me": 2
      }
    },
    {
      "steps": {
        "find_me": 1
      },
      "speed": {
        "find_me": 2
      }
    },
    {
      "sight": {
        "find_me": 3
      },
      "angle": {
        "find_me": 4
      }
    },
    {
      "sight": {
        "find_me": 3
      },
      "angle": {
        "find_me": 4
      }
    }
  ]
Why are there duplicates?

**Comment by sadams-rti-org** [comment]
@shrikus found a better query to accomplish the goal:
     **[*.find_me != null]
But there is still the question of what should we expect from the use of stacked parent refs

**Comment by andrew-coleman** [comment]
You get duplicates because you are asking for the parents of siblings.  You can use the `$distinct` function to de-duplicate the results from any expression.
