### ISSUE TITLE
Expression evaluation timeout: Check for infinite loop

### ISSUE THREAD

**Issue by adityapant1286** [jsonata-js/jsonata#456]
Hi team,
I absolutely love JsonATA and became a fan overnight.
I am able to resolve many cases with the help of the documentation, however there is a particular issue I am facing which I need some advise.

Every `$map()` function in the script error out with timeout and infinite loop.

It is quite hard to debug such issues on the online editor, after removing some lines it is uncertain to know what is causing this error. One thought, the large data size in array might be causing it, but not sure.
I have tried to generate a shareable link but after waiting for 10 minutes unable to generate the sharable link. However I have added data and script files on Google drive and the link added here.

https://drive.google.com/drive/folders/1ACDwS3SUxCkJ8f9K6p4-dxShpSor1bhz?usp=sharing

**Comment by andrew-coleman** [comment]
The online version of the exerciser has a one second timeout on expressions to protect against runaway expressions hanging your browser.  
You can clone the exerciser and run it locally - instructions here: https://github.com/jsonata-js/jsonata-exerciser.
It doesn't timeout when run locally.  

I'll close this issue for now - if you find other issues, feel free to repoen.
