### ISSUE TITLE
strange behaviour when processing sparse arrays

### ISSUE THREAD

**Issue by janvda** [jsonata-js/jsonata#458]
The problem is also raised in node-red forum : 

- [Weird behaviour when processing an array of arrays having null values](https://discourse.nodered.org/t/weird-behaviour-when-processing-an-array-of-arrays-having-null-values/28615)

So as input we are using the following sparse array:

![image](https://user-images.githubusercontent.com/17238398/85199868-fcb87c00-b2f2-11ea-91fe-eab034c58a37.png)

Although the above screenshot shows `payload[1][1] = null` - actually this array element is not specified in javascript (= sparse javascript array).

When running the following script:
```
payload.{
   "row" : $
}
```
then the "null" cell gets removed as you can see in below output:

![image](https://user-images.githubusercontent.com/17238398/85199894-44d79e80-b2f3-11ea-8872-aa5f1f20895a.png)

Is this expected behaviour ?

**Comment by andrew-coleman** [comment]
I see there is a lot more discussion on the node-red forum, but from a pure jsonata point of view, I would be interested to know what the input _JSON_ data looks like.

The entire JSONata test suite is specified as JSON in / JSON out to make it implementation agnostic (there was once a Go implementation - not sure what became of it).  

There is no defined behaviour for inputs that can't be expressed in JSON, and I don't think sparse arrays can be.

**Comment by janvda** [comment]
With node-red it is possible to pass a sparse array as input for a JSONata expression in a change node.

I agree that sparse arrays can't be expressed in JSON.
I also agree that in that case the behavior is undefined.

So for me it is fine to close this issue.
