### ISSUE TITLE
$eval returns empty object if the context value is an empty array

### ISSUE THREAD

**Issue by goulderb** [jsonata-js/jsonata#463]
When $eval is provided an empty array, it always returns empty object.

Example:
```
$eval("{ 'test': 1 }", [])
```

Output:
```json
{}
```

Expected Output:
```json
{
  "test": 1
}
```

**Comment by andrew-coleman** [comment]
Looks like a bug, I think

**Comment by goulderb** [comment]
@andrew-coleman Do you happen to have any areas of the code that you would start looking at to dig into this issue? It's impacting me as I've got quite a few JSONata expressions that use $eval to do some meta-programming style functionality.

I'd be open to contributing a bug fix for this, but I am not really sure where to start.
