### ISSUE TITLE
Escaping / sanitizing strings?

### ISSUE THREAD

**Issue by patarapolw** [jsonata-js/jsonata#465]
For example, I cannot find a way to query this.

```json
{
  "Account": {
    "Account`[ Name": "Firefly"
  }
}
```

**Comment by patarapolw** [comment]
It seems to be escapable with `"`, therefore, `JSON.stringify`. However, I cannot find this in the documentation?

```json
{
  "Account": {
    "Account`[ \"Name": "Firefly"
  }
}
```

```
Account."Account`[ \"Name"
```

**Comment by mattbaileyuk** [comment]
As I just mentioned in [another issue](https://github.com/jsonata-js/jsonata/issues/466#issuecomment-671327619), single and double quotes were originally used for escaping, but were replaced by backticks as they didn't hit the issue of needing to escape quite so commonly.

Is this theoretical, or are you actually getting JSON data with backticks in that you need to escape? I think the best way at the moment is using the single quotes instead, as you have, but it will be something to keep in mind if we do get around to removing the older mechanisms in a future release.

**Comment by andrew-coleman** [comment]
You can always use the `$lookup()` function if the string contains a backtick.

**Comment by patarapolw** [comment]
Yes, it is indeed theoretical. As keys are mostly likely created on the server.

However, nasty string values, which I haven't tried yet, can be real, via possibly malicious users.

**Comment by andrew-coleman** [comment]
> via possibly malicious users.

In which case you should definitely be checking the values before injecting them into a query! :)

**Comment by andrew-coleman** [comment]
closing as resolved
