### ISSUE TITLE
Matching a field with a name that contains spaces or special charecters

### ISSUE THREAD

**Issue by kaan-atakan** [jsonata-js/jsonata#466]
Lets say I have some JSON like:

{
  "normal": 1,
  "has some spaces": 2,
  "@": 3
}

How do I select "has some spaces" or "@"?

I couldn't find anything about this in the documentation.

**Comment by jhorbulyk** [comment]
Under the [**Navigating JSON Objects**](https://docs.jsonata.org/simple#navigating-json-objects) section, the following is listed:
> Field references containing whitespace or reserved tokens can be enclosed in backticks

Thus if the incoming object is 
```
{
"normal": 1,
"has some spaces": 2,
"@": 3
}
```
then the JSONata expressions `` `has some spaces` `` and `` `@` `` will match `2` and `3` respectively.

**Comment by kaan-atakan** [comment]
Oops, I guess I skimmed that section a bit too fast and missed the final example. You might want to consider giving it it's own heading. Also after randomly typing things I noticed that `$.'has some spaces'` and `$."@"` also resolve the elements, though I wasn't able $ in the documentation and don't understand why it works. I suppose it's in there and I missed it again.

**Comment by mattbaileyuk** [comment]
`$` is explained in [this doc page](https://docs.jsonata.org/programming#built-in-variables); you're referring to the root here, and selecting an element under that root object.

Single or double quotes were originally used to select values with spaces, but that ran into issues (e.g. `it's`!), so `1.3.0` onwards adopted backticks, as they are now familiar to Markdown users. Both are still supported to avoid breaking existing expressions (including in the product that JSONata was originally written for); if/when there's a 2.0.0 release I could see that finally going, so I would use backticks when you need to escape.

**Comment by andrew-coleman** [comment]
closing as resolved

**Comment by lew** [comment]
What is the correct way to escape the U+0060 character inside keys like in:    
```json
{
  "test`": "something"
}
```

A backslash doesn't seem to work:
```jsonata
`test\`` = "something"
```
![grafik](https://user-images.githubusercontent.com/42109/193026781-199fb89a-ffaa-4d60-a3d4-e47f81890ab8.png)
