### ISSUE TITLE
[BUG] Errors when using variables who start with number

### ISSUE THREAD

**Issue by amcdnl** [jsonata-js/jsonata#468]
## Bug
If a variable starts with a number, the parser throws a `Syntax Error`.

I realize this is INVALID JavaScript to create a variable which starts with a number/etc character but I would expect JSONATA to handle this elegantly or document the issue. 

While I agree this is probably a anti-pattern sadly APIs like JIRA actually return variables like this: https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-users/#api-rest-api-3-user-get 

## Steps to Reproduce
Take the following JSON which contains a variable `24x24Image`:

```json
{
  "Account": {
    "Account Name": "Firefly",
    "24x24Image": "foo",
  }
}
```

Now try to pull out the `24x24Image` variable using JSONATA like so:

```
Account.24x24Image
```

Note the error:

```
Syntax error: "x24Image"
```

**Comment by andrew-coleman** [comment]
This is not a bug, you just need to enclose the offending property name in backticks:
```
Account.`24x24Image`
```

See the final bullet in https://docs.jsonata.org/simple#examples

**Comment by amcdnl** [comment]
Totally missed that - thanks for getting back to me so quickly!

A better error message might help - not sure how feasible that is though.
