### ISSUE TITLE
Feature Request - findIndicesOfMatchingPredicates

### ISSUE THREAD

**Issue by raj-work** [jsonata-js/jsonata#47]
Hi,
We started using JSONata for one of our projects and discovered that we will need an ability to find the indices of matching predicates in the JSON path. Just wanted to see if we can add that ability.
Thanks.

**Comment by andrew-coleman** [comment]
Hi @raj-work 
Thanks for the request - we can definitely look at this.  Would it be possible to clarify exactly what you need by showing us some sample JSON data, together with the output that you are trying to get.  Perhaps you could create a Gist that contains this, and paste a link to it in this issue.
Many thanks.

**Comment by raj-work** [comment]
hi @andrew-coleman 
Thanks for the quick response. I have create a gist with an example. I hope this helps clarify my requirement clearer.
<script src="https://gist.github.com/raj-work/22c26fb72e42f0489a352672087ccb06.js"></script>

**Comment by raj-work** [comment]
Hi @andrew-coleman - Thanks for your valuable feedback. Unfortunately, we are using JSONata inside a Java application. And currently, Nashorn is not supporting ECMA 6 functions. Is there any suggestion of how to use this inside a Java application? Also, is there any Java implementation which you suggest will work better with JSONata? Thanks.

**Comment by mattbaileyuk** [comment]
@raj-work JSONata 1.2.1 was released today and contains a transpiled version called `jsonata-es5.js`for ES5 users, so hopefully you could use that with Nashorn.

**Comment by raj-work** [comment]
@mattbaileyuk - I notice that the 1.2.1 version has dependency on babel too. I am also looking at using J2V8 engine instead of Nashorn. Are you guys familiar with it? And do you see any drawback in using J2V8 instead of Nashorn?

**Comment by mattbaileyuk** [comment]
@raj-work I haven't had experience of using either, but I think @andrew-coleman has spoken to people who have used JSONata in Java (and/or he's done it himself)

**Comment by raj-work** [comment]
@mattbaileyuk thanks for your help. @andrew-coleman is it possible for your provide your feedback?

**Comment by andrew-coleman** [comment]
@raj-work I've never used J2V8 so I can't really add anything here.  It looks interesting though, and if you get chance to try it with JSONata, I'd be very keen to hear about your experiences.

**Comment by raj-work** [comment]
@andrew-coleman - Let me try and update you guys if that works. Thanks for all your help.

**Comment by andrew-coleman** [comment]
Closing this issue since the original requirement has been met.
