### ISSUE TITLE
Is there a way to add newline character?

### ISSUE THREAD

**Issue by adityapant1286** [jsonata-js/jsonata#470]
If I have an array of string, is there a way to transform array to strings but each element should be on a new line?
Tried with `\n` or `\\n`. `$string` with prettify true option adds `\n` but the output displays on the same line.

Example:
```
[
   "This is ",
   "an example ",
   "to be transformed"
]
```

Output:
```
This is
an example 
to be transformed
```

**Comment by andrew-coleman** [comment]
Use the `$join` function

`$join($, "\n")`

**Comment by adityapant1286** [comment]
Thank you Andrew. Appreciate your time and comments.

```$join($, "\n")```

It adds \n which is showing in 1 line.

Following is the example.

https://try.jsonata.org/CSOSo9u43

**Comment by radhakrishnan-chandarasikharan-kr** [comment]
I have the same question and have the same output. However with the command-line tool jfq, I do get the response on separate lines

[https://try.jsonata.org/lFgCffDYy](https://try.jsonata.org/lFgCffDYy)

```
$ cat sample.json | jfq -q csv.qry
a,b
alpha,beta
zeta,jones
```

* sample.json has the input and csv.qry has the Jsonata expression

**Comment by nicobo** [comment]
This issue should be reopened as it was not answered ; and I confirm I have still the same behavior (\n) printed out instead of generating a new line...

**Comment by nicobo** [comment]
Answering to myself, if it can be of some help => you have to **print** the result to interpret the `\n`, for instance with `console.log(result)` (and no `JSON.stringify`, which was my mistake)
