### ISSUE TITLE
Filtering arrays inside $map

### ISSUE THREAD

**Issue by avifatal** [jsonata-js/jsonata#474]
Hi
I am trying to filter out a property from json while building result inside $map
```
{
  "nodes": [
    {
      "field_type": "a",
      "text": "test_a"
    },
    {
      "field_type": "b",
      "text": "test_b"
    },
    {
      "field_type": "b",
      "text": "test1_c"
    }
  ]
}
```
I want to return only a and c. and remove b.
this is what I have so far: https://try.jsonata.org/Oz9umE30F
Thanks

**Comment by andrew-coleman** [comment]
`nodes[field_type != 'b']`

https://try.jsonata.org/zWJcKrrhm

**Comment by avifatal** [comment]
Hi
I have more complex use-case when I use $map, to simplify it I have posted a flat simple json.
Can you please explain how to acheive using $map?
Thanks

**Comment by avifatal** [comment]
@andrew-coleman can you please re-open this issue?

**Comment by avifatal** [comment]
@andrew-coleman 
![image](https://user-images.githubusercontent.com/12430740/94656379-b2d72d00-0308-11eb-9ce7-dd3109a58cc4.png)

**Comment by mattbaileyuk** [comment]
@avifatal You haven't provided much detail on your new problem, and why the solution that @andrew-coleman provided to your original issue does not work.

From an etiquette point of view, angry emojis are not helpful to the conversation.
