### ISSUE TITLE
$toMillis() fails when a timezone is added to picture string

### ISSUE THREAD

**Issue by rcrichton** [jsonata-js/jsonata#477]
Both of these expressions fail to execute on any version of JSONata:

```
$toMillis('2020-09-09 00:00:00 +02:00', '[Y0001]-[M01]-[D01] [H01]:[m01]:[s01] [Z]')
$toMillis($now('[Y0001]-[M01]-[D01] [H01]:[m01]:[s01] [Z]', '+0200'), '[Y0001]-[M01]-[D01] [H01]:[m01]:[s01] [Z]')
```

If you remove the timezone from the picture string and timestamp string everything work as normal.

Links to try these out:
* https://try.jsonata.org/jYoHi-8k0
* https://try.jsonata.org/H3rxBmGEn

**Comment by andrew-coleman** [comment]
Looks like this was never implemented for parsing a timestamp, only for formatting.   I'll mark this as a bug.
