### ISSUE TITLE
support js6 spread syntax?

### ISSUE THREAD

**Issue by bayeslearner** [jsonata-js/jsonata#480]
Hi, 
very new to this.  Does it support  "..." for json object spread so that it is easy to do a template-like programming?   Maybe I'm just confused.

**Comment by markmelville** [comment]
No. JSONata's language features are not tied to those of javascript. However what you want to do is achievable in JSONata with the transform operator.

"Spread" each product's description onto the product: https://try.jsonata.org/XjLEb01ZH
```
Account.Order.Product~>|$|Description,'Description'|
```
which would be something like this in JS:
```
products.map(p => {
   let {Description, ...rest} = p;
   return {...rest,...Description};
});
```

**Comment by andrew-coleman** [comment]
Thanks Mark for answering this.
