### ISSUE TITLE
Reassign variable to new value?

### ISSUE THREAD

**Issue by adityapant1286** [jsonata-js/jsonata#481]
Is there a way to reassign variable? Or another way to solve it

In below example, the `$paymentAmount` should be updated to remaining after subtraction, so that when it becomes 0, it should exit the inner `$map()`. Going with this way because the output of inner $map() will be different.

When `$paymentAmount` becomes 0, the inner `$map()` of invoices should start from the index when it becomes 0.

### Example:
https://try.jsonata.org/FGNYsACXV

In this example, _Remaining_ and _lastIndex_ of the invoice should be updated. It is a traditional way but if there is a better way, much appreciated.

### Expectations

> PaymentAmounts = [50, 100];
> InvoicesAmounts = [10, 40, 20];
> PaymentIteration1
> Remaining = PaymentAmounts[0]; // 50
> 
> InvoiceIteration1
> Remaining = Remaining - InvoicesAmounts[0] // 40
> InvoiceIteration2
> Remaining = Remaining - InvoicesAmounts[1] // 0 - here InvoiceIteration should break and store its last index which is 1
>
> PaymentIteration2
> Remaining = PaymentAmounts[1]; // 100
> 
> InvoiceIteration1
> Remaining = Remaining - InvoicesAmounts[2] // 80

**Comment by jhorbulyk** [comment]
JSONata is generally designed to be immutable. There is probably a way to obtain what you want with the `$reduce()` function.

**Comment by adityapant1286** [comment]
Appreciate your time and response Jacob.
I think for this use case I would need some way to store the previous state.
I had tried with `$reduce()` for below example and can't get it to work when the Invoice amount > payment amount.
Also, need a way to start the invoice array index where accumulator becomes 0 in the first reduce execution because once these invoices are used for subtraction it should not be used again.

Case 100 > 50 = works for the first time, but since no state stored (immutable), unfortunately, cannot start from the last index.
Case 100 < 150 = fails with error 
> The expressions either side of operator ">" must evaluate to numeric or string values

https://try.jsonata.org/mFHJ17Gwe

**Comment by andrew-coleman** [comment]
The tricky thing is, you've specified the problem by using an imperative example of how it might be solved, and you are then trying to use a functional language to implement it.  I.e. you've described a "how" not the "what".  Your example doesn't state, for example, what happens if the sum of the first two invoices doesn't add up to the first payment amount.

In general, I'd rather these sorts questions get posted to stackoverflow, and use github issues for raising bugs or enhancement requests.

Thanks!

**Comment by adityapant1286** [comment]
Hi @andrew-coleman, thank you for the comments. Appreciate it.

I solved it in JavaScript due to time constraints, but I will spend some time on this.

FYI 
> what happens if the sum of the first two invoices doesn't add up to the first payment amount

If sum of first two invoices doesn't add up, example, Payment amount = 40.
In this case invoice amount 10 will be subtracted (payment balance 30).
Invoice amount 40 > payment balance 30, then only 30 will be subtracted and invoice balance becomes 10. Also the last index remains 1.
In next iteration when payment amount = 100, then first invoice balance 10 will be subtracted (using last index) followed by 20.
In the end, payment balance remains 70.
