### ISSUE TITLE
Js2Py to support jsonata in Python

### ISSUE THREAD

**Issue by anshikg** [jsonata-js/jsonata#488]
I am trying to use jsonata in python using [Js2Py](https://github.com/PiotrDabkowski/Js2Py) by using the following piece of code: 
```
from js2py import require
jsonta = require('jsonata') #https://www.npmjs.com/package/jsonata
```

It seems to fail when importing jsonata in python with the following error:
```
Error: Can't walk dependency graph: Cannot find module './functions' from '/usr/local/lib/node_modules/jsonata/jsonata.js'
```

I looked at the jsonata.json file on my local machine it seems to failing when trying to run the following line of code
```
var fn = require(./functions');
```

I am wondering if the above line of code should be:
```
var fn = require(functions');
```

Any suggestions around this would be super helpful.

**Comment by andrew-coleman** [comment]
I can't help with python.  Have you looked at this: https://pypi.org/project/pyjsonata/ ?

Failing that, please post questions to https://stackoverflow.com/search?q=JSONata
Thanks!

**Comment by anshikg** [comment]
Thanks for getting back to me. I have looked at  https://pypi.org/project/pyjsonata The make file seems to be broken and does not work for PyPI. I will spend more time on stackoverflow and see if I find anything useful.

**Comment by nedosa** [comment]
@anshikg I wonder if you found any solution to this issue ? 

@andrew-coleman It would be great to get jsonata to run against `js2py`, I think it will really expand the user base of jsonata if it can be run on python.
