### ISSUE TITLE
How to get the object index?

### ISSUE THREAD

**Issue by kgalilio** [jsonata-js/jsonata#490]
I have a node red node that produces an array. I am able to get the object properties using JSONata but I would also like to retrieve the object index.
In the following case:
`payload.port_overrides[name="PS4"].port_idx` I get "11" which is the correct property value; however, I would like to also retrieve the object id/index which is 10.
![image](https://user-images.githubusercontent.com/48642035/98433290-be233280-20d6-11eb-821e-c0550a435d7d.png)

**Comment by kgalilio** [comment]
I managed to resolve it using the following:
`($x:=payload.port_overrides ~> $map(function($v, $i) { $v.name = 'PS4' ? $i });
$exists($x)?$x:-1)`

**Comment by andrew-coleman** [comment]
You can also use the index operator (https://docs.jsonata.org/path-operators#-positional-variable-binding) to bind a variable to the index of the value in the sequence.  See https://try.jsonata.org/HeSitd4Z2 for an example.

So your expression could be
`payload.port_overrides#$i[name="PS4"].$i`
