### ISSUE TITLE
Escape characters for JSON properties

### ISSUE THREAD

**Issue by dstrohschein** [jsonata-js/jsonata#494]
I looked everywhere in the documentation and could not find this - **Is there a way to escape characters** that are in the JSON object? For instance, one of our systems outputs JSON like this:

`{ '@PropertyName' : 'SomeValue'}`

If we try to get the value of the property using the really basic Transform of :

`@PropertyName`

It fails. Since it has the @ sign in it, the JSONata parser throws errors when we try to access it because the @ sign is used as a reserved symbol in JSONata. Is there a way we can escape the @ char in the property name? We have systems that produce some really dirty JSON structures, where properties have dots, spaces, symbols, all kinds of junk in them. Part of the reason we want to transform the data is to produce something that looks better when we don't have the ability to change the source of the JSON data.

**Comment by andrew-coleman** [comment]
Use backticks as shown in the last example here: https://docs.jsonata.org/simple#examples
