### ISSUE TITLE
JSONata Website lists outdated copyright info

### ISSUE THREAD

**Issue by fbuchinger** [jsonata-js/jsonata#497]
https://jsonata.org/ -> "© Copyright 2016 jsonata.org"
https://docs.jsonata.org/overview.html -> "Copyright © 2018 JSONata.org"

This could make people believe there have been no JSONata updates since 2016/18 and deter them from using the library.

**Comment by mattbaileyuk** [comment]
I've put in a PR for the date in the docs as the docs are actually in this repo.

I don't believe the main page is stored in a repo and I think only @andrew-coleman has access to update that.

@andrew-coleman If you do update that page, the developerWorks Open link could do with updating to https://developer.ibm.com/open/projects/jsonata/ as it looks like they moved some pages around.

**Comment by andrew-coleman** [comment]
Thanks Matt.  I've updated the website, which is in this repo btw: https://github.com/jsonata-homepage/jsonata-homepage.github.io
