### ISSUE TITLE
[QA] Nested `[` is officially support?

### ISSUE THREAD

**Issue by fredppm** [jsonata-js/jsonata#507]
Hello

I was trying to figure out if the nested brackets is officially support or may be a bug feature.

My may sample 

I want to sum all values from the array of objects named `totals` and filter it when only this object has the Id with `CustomTax` or `Tax`
So this query works for me
`(totals[id in ["CustomTax", "Tax"]].value ? $number($sum(totals[id in ["CustomTax", "Tax"]].value)) : undefined)`

But using the try page the syntax highlight appear to be bugged
![image](https://user-images.githubusercontent.com/12805319/112061558-6d6c1d80-8b3d-11eb-84d3-509db3930210.png)

I didn't find any warnings in the docs about this nested operations so I want just to confirm if the query interpretation officially handling this inception .
Thank

**Comment by markmelville** [comment]
That expression has no syntax errors for me in the exerciser (try page).

BTW, this expression is effectively the same (I'm not sure of your input data):
```
$sum(totals[id in ["CustomTax", "Tax"]].value)
```

**Comment by andrew-coleman** [comment]
I suspect @fredppm doesn't like the colours in the exerciser.
There is an issue open for this: https://github.com/jsonata-js/jsonata-exerciser/issues/18
Closing this one.
