### ISSUE TITLE
async custom function with <sa<s>:s> signature run into T0412 error

### ISSUE THREAD

**Issue by oliverlorenz** [jsonata-js/jsonata#510]
I could reproduce a strange behavior with async calls. 

**Context:**
* I have a custom function `asyncItemsFromDb` (`<:a<s>>`), to get some data (
* I have another custom function `removeItems` (`<sa<s>:s>`) which consumes return of `asyncItemsFromDb`
* result is a `T0412` with message `Argument 2 of function "removeItems" must be an array of "strings"`

**Example Code:**

```
const jsonata = require('jsonata');
expression = jsonata(
	'$removeItems("my string has item1 within", $asyncItemsFromDb())'
);

expression.registerFunction(
	'asyncItemsFromDb',
	async () => {
		return new Promise((resolve) => {
			resolve(['item1', 'item2']);
		});
	},
	'<:a<s>>'
);

expression.registerFunction(
	'removeItems',
	(text, itemsToRemove) => {
		itemsToRemove.forEach((item) => {
			const regexp = new RegExp(`\\b${item}\\b`, 'gi');
			text = text.replace(regexp, '');
		});
		return text;
	},
	'<sa<s>:s>'
);

let result = expression.evaluate();
console.log(result);
```
```
{
  code: 'T0412',
  stack: 'Error\n' +
    '    at <REMOVED>/node_modules/jsonata/jsonata.js:7244:57\n' +
    '    at Array.forEach (<anonymous>)\n' +
    '    at <REMOVED>/node_modules/jsonata/jsonata.js:7213:45\n' +
    '    at Array.forEach (<anonymous>)\n' +
    '    at Object.validate (<REMOVED>/node_modules/jsonata/jsonata.js:7186:28)\n' +
    '    at validateArguments (<REMOVED>/node_modules/jsonata/jsonata.js:5033:39)\n' +
    '    at applyInner (<REMOVED>/node_modules/jsonata/jsonata.js:4902:33)\n' +
    '    at applyInner.next (<anonymous>)\n' +
    '    at apply (<REMOVED>/node_modules/jsonata/jsonata.js:4869:26)\n' +
    '    at apply.next (<anonymous>)',
  value: Promise { <pending> },
  index: 2,
  type: 'strings',
  token: 'removeItems',
  position: 13,
  message: 'Argument 2 of function "removeItems" must be an array of "strings"'
}
```

If I change the signature of `removeItems` function, from `<sa<s>:s>` to `<sa<o>:s>` the error is gone. But this is not the result I try to get ;) 

So, the problem seems I get a promise back here instead of the result of the promise. Any idea how to fix this?

**Comment by markmelville** [comment]
because you are using an async function, you have to [invoke evaluate with a callback](https://docs.jsonata.org/embedding-extending#expressionevaluateinput-bindings-callback). That's what sets the evaluation into "async mode". Here is a post where an example is given of turning that into a promise: https://github.com/jsonata-js/jsonata/issues/77#issuecomment-338307253

**Comment by oliverlorenz** [comment]
Thank you for your quick and precise response! Problem solved :heart:
