### ISSUE TITLE
Editor highlight error

### ISSUE THREAD

**Issue by acoroleu-tempus** [jsonata-js/jsonata#511]
While trying this expression from the docs in the editor:
`` Account.Order.Product {
  `Product Name`: {"Price": Price, "Qty": Quantity}
} ``
The highlight seems to break for `Price`. On the other hand this expression does not break the highlight:
`` Account.Order.Product {
  `Product Name`: {'Price': Price, "Qty": Quantity}
} ``

Am I doing something wrong? Any plans to fix it?

Thanks

**Comment by acoroleu-tempus** [comment]
Any updates on this?

**Comment by andrew-coleman** [comment]
When you say 'the editor', I assume you mean the [JSONata Exerciser](https://try.jsonata.org/) website?  In which case, feel free to reopen this issue in the [exerciser repo](https://github.com/jsonata-js/jsonata-exerciser).  The exerciser uses [Monaco](https://microsoft.github.io/monaco-editor/) for the editor and supplies a [config file](https://github.com/jsonata-js/jsonata-exerciser/blob/master/src/jsonataMode.js) which instructs the editor how to highlight the tokens.  You could try fiddling with this to see if you can get any better results than I've managed.

I don't think there's a JSONata runtime issue here, so closing from this repo.
