### ISSUE TITLE
Transform function does not update the key value properly

### ISSUE THREAD

**Issue by mhamza1234** [jsonata-js/jsonata#513]
Trying to change the Key name using the Transfer function. The name did not change on the first occurrence. It did change subsequent occurrences.

$ ~> |Account.Order|{'Product_ID': Product}|

https://try.jsonata.org/6N7If6tSN

**Comment by markmelville** [comment]
It's not clear what the problem is. Looking at your link, the expression is doing exactly what it's supposed to. The output has a `Product_ID` key on all 4 product objects. You said you're trying to change the key name. If so, you may want to delete the original key like this:
```
$ ~> |Account.Order|{'Product_ID': Product}, ['Product']|
```

**Comment by andrew-coleman** [comment]
No response from @mhamza1234 
Closing issue.
Thanks Mark.

**Comment by tvkit** [comment]
> The name did not change on the first occurrence. It did change subsequent occurrences.

@mhamza1234  at first glance, the results look like what you described, but your expression adds the additional block named, _Product_ID_, but doesn't replace the block being assigned, _Product_.  I guess that helps to explain the utility of the delete option as shown in @markmelville 's post.
