### ISSUE TITLE
Nested $map functions cause runtime to scale exponentially

### ISSUE THREAD

**Issue by taylorreece** [jsonata-js/jsonata#532]
Hi JSONata team!

I'm running into an issue with a JSONata expression that includes nested `$map` functions. The nested `$map` functions appear to cause processing time to scale exponentially, when I _think_ it should scale linearly.

I put together a repo, https://github.com/taylorreece/jsonata-nested-map-slowness to show what I'm talking about. In `slow.js` and `fast.js` I have an *array* of "customer" objects that looks like this:

```js
[
  {
    "id": 12345,
    "name": "Test Name Here",
    "addresses": [
      {
        "addressLine1": "1234 Test Road Here",
        "addressLine2": "Fake Town, USA"
      },
      {
        "addressLine1": "456 Fake Road",
        "addressLine2": "Real Town, CA"
      }
    ]
  },
  // ...
]
```

If I run a simple `$map` over the array of customer objects like this:

```js
$map($, function($customer) {
  {
    "Id": ($customer.id),
    "Name": ($customer.name)
  }
})
```

the script runs pretty quickly, and scales linearly with number of customers:

```
$ node fast.js

Input of size 100 took 29ms to process.
Input of size 200 took 12ms to process.
Input of size 400 took 30ms to process.
Input of size 600 took 12ms to process.
Input of size 800 took 15ms to process.
Input of size 1000 took 17ms to process.
Input of size 2000 took 28ms to process.
Input of size 3000 took 41ms to process.
Input of size 4000 took 55ms to process.
Input of size 5000 took 71ms to process.
```

If I have a nested `$map` function to loop over addresses for each customer, like this:

```js
$map($, function($customer) {
  {
    "Id": ($customer.id),
    "Name": ($customer.name),
    "Address": $map($customer.addresses, function($address) {
      {
          "Address1": ($address.addressLine1),
          "Address2": ($address.addressLine2)
      }
    })
  }
})
```

then the script takes longer and longer as the number of customer objects increase - it seems to increase exponentially, towards the end taking about 5 minutes.

```
$ node slow.js

Input of size 100 took 87ms to process.
Input of size 200 took 258ms to process.
Input of size 400 took 970ms to process.
Input of size 600 took 2168ms to process.
Input of size 800 took 3913ms to process.
Input of size 1000 took 6902ms to process.
Input of size 2000 took 35898ms to process.
Input of size 3000 took 100967ms to process.
Input of size 4000 took 191469ms to process.
Input of size 5000 took 345477ms to process.
```

I get that if you have a loop inside of a loop, you usually see a big-O runtime of `O(n^2)`, but in this case our runtime should be computed off of `O(customers * addresses)`. `addresses.length` is always `2`, so `customers` is the only thing really increasing. I'm pretty sure runtime should scale _linearly_ with `customers.length`. I'd expect that JSONata expression in `slow.js` to run just about as fast as the one in `fast.js`.

Thanks in advance for your thoughts on this!

**Comment by markmelville** [comment]
A few observations:

1) the execution of the inner function isn't the only thing happening in the outer loop. It's actually re-defining that function in every iteration. If we define it beforehand the performance is much improved:
```
(
$extractAddress:=function($address) {
  {
      "Address1": ($address.addressLine1),
      "Address2": ($address.addressLine2)
  }
};
$map($, function($customer) {
  {
    "Id": ($customer.id),
    "Name": ($customer.name),
    "Address": $map($customer.addresses, $extractAddress)
  }
})
)
```
```
Input of size 100 took 26ms to process.
Input of size 200 took 25ms to process.
...
Input of size 4000 took 269ms to process.
Input of size 5000 took 309ms to process.
```

2) It can be done without using `$map` at all, using idiomatic JSONata:
```
$.{
    "Id": id,
    "Name": name,
    "Address": {
        "Address1": addressLine1,
        "Address2": addressLine2
    }
  }
```
giving the best performance of all (including the `$map` version with no inner loop)
```
Input of size 100 took 6ms to process.
Input of size 200 took 13ms to process.
...
Input of size 4000 took 43ms to process.
Input of size 5000 took 49ms to process.
```

So, with all this in mind...
Is there a performance problem with defining functions in nested `$map` calls? Yes.
Is it something that needs to be fixed? Maybe not.

**Comment by taylorreece** [comment]
Welp, @markmelville , I just learned more about JSONata in the last 30 seconds than I have over the last several weeks.  Thanks so much for your help! This is lightening-quick now!

**Comment by andrew-coleman** [comment]
Thanks @markmelville for picking this up.  Closing as resolved.
