### ISSUE TITLE
An error occurred when convert empty array to an object in 1.8.5

### ISSUE THREAD

**Issue by hankei6km** [jsonata-js/jsonata#547]
I'm trying to convert an array of API responce to an object with JSONata.
in many cases it works very well.
(JSONata is very powerful)

However, I get an error when I convert an empty array in JSONata 1.8.5.
(in 1.7.0 work as expected)

```
Key in object structure must evaluate to a string; got: undefined
```

## steps to reproduce

I tried it with JSONata Exerciser.

### array to object

It works in the following cases.

https://try.jsonata.org/uvEJnSWm-

jsonata: `$${id:{"label":label,"value":value}}`

json:
```json
[
  {
    "id": "abc",
    "label": "ABC",
    "value": 123
  },
  {
    "id": "def",
    "label": "DEF",
    "value": 321
  }
]
```

result:
```
{
  "abc": {
    "label": "ABC",
    "value": 123
  },
  "def": {
    "label": "DEF",
    "value": 321
  }
}
```

### empty array

An error occurred when json was an empty array.
https://try.jsonata.org/r9UY9cPmx
(in 1.7.0 work as expected)

json:
```json
[]
```

result (1.8.5):
```
Key in object structure must evaluate to a string; got: undefined
```

result (1.7.0):
```
{}
```

## workaround

The following query works even with an empty array

```
$count($$) > 0 ? $${id:{"label":label,"value":value}} : {}
```

**Comment by hankei6km** [comment]
Additional Information.

In "1.8.0 - 1.8.4" worked as expected.


## steps to reproduce

```
$ node --version
v14.18.1
```

```javascript
import jsonata from 'jsonata';

const data = [];
try {
  const expression = jsonata('$${id:{"label":label,"value":value}}');
  console.log(
    `result => ${JSON.stringify(expression.evaluate(data), null, '  ')}`
  );
} catch (err) {
  console.log(`err => ${err.message}`);
}

```

1.8.0 - 1.8.4
```
result => {}
```

1.8.5
```
err => Key in object structure must evaluate to a string; got: undefined
```

**Comment by andrew-coleman** [comment]
Resolved by #555

**Comment by asampal** [comment]
Doesn't this warrant a new release?

**Comment by mattbaileyuk** [comment]
@asampal 1.8.6 was released today with this fix (among others)
