### ISSUE TITLE
Additional Functions to support timestamps and unique ids

### ISSUE THREAD

**Issue by shrickus** [jsonata-js/jsonata#55]
Per our discussion on the slack channel: here are some ideas for new functions related to

- *Timestamps* -- potentially providing such variants as Unix time (secs. since epoch), JavaScript time (millis since epoch), and Microsoft filetime (just kidding)
- *Unique IDs* -- variants such as UUID/GUID, or my favorite originally based on [Firebase PushIDs](https://gist.github.com/mikelehen/3596a30bd69384624c11)

Although version 1.2 includes the `$now()` function, this returns an ISO 8601 formatted date string, which in a bit unwieldy to calculate differences between dates. I was looking for something more like the Unix timestamp, that is sortable and avoids timezone and locale formatting issues.

**Comment by andrew-coleman** [comment]
Function `$millis()` has been added to branch `1.3`.  This returns the number of milliseconds since the epoch.  In common with `$now()`, this function returns the same value for every invocation within a single expression.

**Comment by shrickus** [comment]
Andrew, the `$millis()` function is a nice addition - thanks for that.

Seems like the other missing piece is a way to get the ISO 8601 formatted date string from this number of millis. Is that in the plans as well?

**Comment by andrew-coleman** [comment]
It certainly occupies my thoughts, and I'd want to make sure that it fits in with the wider requirement on string/number/date/time formatting captured in issue #54.

**Comment by msmiths** [comment]
Hi Andrew,

We actually have requirement to be able to convert in both directions, i.e.:

- millis -> ISO 8601 formatted data
- ISO 8601 formatted data -> millis

Are both being considered for inclusion in JSONata?

**Comment by mattbaileyuk** [comment]
The functions `$toMillis()` (ISO 8601 to millis) and `$toDateTime()` (millis to ISO 8601) have been added to the branch `convert_timestamps` as a consideration for 1.4

**Comment by shrickus** [comment]
This will be a useful addition -- thanks for that.

I am wondering about the names of the functions, however. Often with a pair of inverse functions like this, one will be named "toXXX", and the other will be "fromXXX". As the terms "date" and "time" are so overloaded, and "ISO8601" is specific but ugly and hard to type, I would suggest `$toMillis(date)` and `$fromMillis(number)` maybe?

**Comment by mattbaileyuk** [comment]
@shrickus Good idea; I wasn't happy with `$toDateTime()` but it was certainly better than `$toISO8601()`... I've now updated the branch with the new function name.

**Comment by mattbaileyuk** [comment]
That branch has now been merged in with the `1.4` branch for release alongside the other new functions and changes in that.

As mentioned elsewhere, you can now play around with branch `1.4` (or any branch) in the [exerciser](http://try.jsonata.org) by typing
`J:branch 1.4`
and hitting return

**Comment by andrew-coleman** [comment]
`toMillis()` & `fromMillis()` now released in v.14
