### ISSUE TITLE
functionnal programming question

### ISSUE THREAD

**Issue by j2l** [jsonata-js/jsonata#553]
After multiple trials, I can't access JSONATA slack and SO doesn't loves me (and I don't love it) so github we go.
Reading http://docs.jsonata.org/programming why something like:
```
(
    $L := library.loans.isbn;
    $B := library.books.isbn;
    library.books[$L=$B];
)
```
doesn't throw any result or error?
Besides `library.loans@$L.books@$B[$L.isbn=$B.isbn]` that throws (everything * loans), what would be a correct way to do it using programming?
Thanks

**Comment by markmelville** [comment]
You haven't made your intent very clear, but I'll guess that you want to show books that are in the list of loans:
```
(
    $L := library.loans.isbn;
    library.books[isbn in $L]
)
```
or even without programming:
```
library.books[isbn in %.loans.isbn]
```

**Comment by j2l** [comment]
Thanks @markmelville !
