### ISSUE TITLE
Request to take ownership of jsonata-wrapper

### ISSUE THREAD

**Issue by pibara** [jsonata-js/jsonata#592]
Because pyjsonata by @qlyoung is barely maintained and doesn't publish source packages on pypi, I've made a litle Pyton wrapper lib for JSONata [here](https://github.com/pibara/jsonata-wrapper) that is roughly based on what @qlyoung did. It uses pybind11 to make the glue code a lot smaller but like pyjsonata also uses duktape. 

It should be a low maintenance wrapper, because it ads very little functionality other than an optional bigint patch. When a new version of JSONata comes out, so should a new version of this wrapper come out because like in pyjsonata, the javascript is compiled into the binary part of the wrapper.

If I keep ownership, chances are I might miss a JSONata release for many months.  I would therefore like to ask if it would be possible for you guys to take ownership of this wrapper, if needed after changes you require.

**Comment by qlyoung** [comment]
Wow, pybind11 looks amazing, didn't know about it. I've taken a quick look and agree that the project is better than the code in `pyjsonata` and I support @pibara's idea of the jsonata org maintaining it.

**Comment by andrew-coleman** [comment]
Thanks for creating this and for offering it to us.  However, Python is not a language that I ever use so I would not be a good person to try and maintain it.

Thanks again!
