### ISSUE TITLE
Path processing filter is inconsistent for numeric data

### ISSUE THREAD

**Issue by dushyantbangal** [jsonata-js/jsonata#596]
When we try to use the Path processing Filter `[]` on numeric values, it is inconsistent compared to text values.

Consider the following input:

```
[
  {
    "txt":"one",
    "num":1
  },
  {
    "txt":"two",
    "num":2
  },
  {
    "txt":"three",
    "num":3
  },
  {
    "num":4
  },
  {
    "txt":"five"
  }
]
```

Inconsistencies:
1. `$[num]` does not return anything, but `$[txt]` returns all the objects in which `txt` has any value.
    ![image](https://user-images.githubusercontent.com/13764676/193201875-cc9c2638-c76a-44f1-b780-05b72261af09.png)

2. In the input, if you change the value in Object 4 from `"num":4` to `"num":3`, then `$[num]` starts working but only returns that one object even when others have value and we are not specifically filtering for num=3
    - This is happening when theres duplicate values one after another. When both Object 1 and 2 have `"num":1`, it returns the second object.
    - When Object 3 and 5 have save value for `num`, it they dont get included.
     ![image](https://user-images.githubusercontent.com/13764676/193202758-eddcebc0-4234-4df0-b0cf-7f48a1c5c1c7.png)

**Comment by dushyantbangal** [comment]
I was trying to use it to filter the records which have `num`. This method worked for string data number is not working for numeric data.

For now, I have started using `$[$type(num)]` but it does not filter `""` so maybe I'll use `$[$type(num)="numeric"]`

**Comment by andrew-coleman** [comment]
If the expression in square brackets evaluates to a number, then it is used as the index of the array.  If it's not a number, then it is treated as a predicate by casting to its equivalent boolean value.  Described here:
https://docs.jsonata.org/simple#navigating-json-arrays
If you want it to be treated in the same way as the string values, then you can cast it to a string using `$[$string(num)]`.

**Comment by dushyantbangal** [comment]
@andrew-coleman thanks. I kept thinking of it as filter, completely forgot Arrays indexes!

And looks like for point 2, it goes on jumping from to the Array location and evaluates the expression on that.
<img width="431" alt="image" src="https://user-images.githubusercontent.com/13764676/193280813-7f5517d2-a0e7-423a-b6cf-322c1b75118a.png">
