### ISSUE TITLE
`isSequence` check interferes with inputs containing JavaScript Proxy instances

### ISSUE THREAD

**Issue by emanuelpalm** [jsonata-js/jsonata#598]
To be able to detect when object or array lookups in JSONata expressions fail, I use a JavaScript [Proxy](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) around some input fields, as follows:

```js
const proxyHandler = {
  get(target, property, receiver) {
    if (!(property in target)) {
      throw `'${property}' property missing!`;
    }
    return Reflect.get(target, property, receiver);
  }
}

const expression = 'hello & ", " & world.name & "!"';
const input = { hello: "Hello", world: new Proxy({ name: 'World' }, proxyHandler)};

try {
  const result = jsonata(expression).evaluate(input);
  console.log(`Result: ${result}`);
} catch (error) {
  console.log(error)
}
```

The code above should succeed and indeed does if you leave out the Proxy. However, if you run the code as it is, the output currently is:

```
'sequence' property missing!
```

The culprit is the [`isSequence()` function](https://github.com/jsonata-js/jsonata/blob/master/src/utils.js#L75-L77), which checks for a `sequence` property in every tested value. Currently, there is no way for me to determine if an attempt to access a `sequence` property comes from a `sequence` identifier in a JSONata expression or from the `isSequence()` function. This could be fixed by modifying the `isSequeuce()` function as follows:

```js
   const SequenceSymbol = Symbol("sequence");

   function isSequence(value) {
        return Array.isArray(value) && value[SequenceSymbol] === true;
    }
```

The first improvement is to start with checking if `value` is an array. No property lookups will then take place in values that are not arrays. The second improvement would be to use a symbol instead of a string to designate a value as a sequence. As far as I know, there is no way of expressing symbols in JSONata expressions, which means that a symbol lookup must always come from outside an expression.

With these changes, I could modify the `proxyHandler` in the top example to avoid throwing when `isSequence()` is used by JSONata. The modified handler could look as follows:

```js
const proxyHandler = {
  get(target, property, receiver) {
    if (typeof property === 'string' && !(property in target)) {
      throw `'${property}' property missing!`;
    }
    return Reflect.get(target, property, receiver);
  }
}
```

**Comment by andrew-coleman** [comment]
There is also discussion on this here: https://github.com/jsonata-js/jsonata/issues/296
Please could you measure the impact your fix has on performance because previous attempts have significantly degraded performance, and despite what you might read in that issue, runtime performance is a serious concern to many users.

Thanks for looking at this.

**Comment by emanuelpalm** [comment]
Sorry to say, but I've changed employer and have no longer any real reason to spend time on this. Thank you, @andrew-coleman, for taking time to look at the issue.
