### ISSUE TITLE
JSONata is rounding numbers which leads to entirely wrong results!

### ISSUE THREAD

**Issue by dev-cb** [jsonata-js/jsonata#599]
Wanted to process a 14-digit id which is uniquely identifying a specific product.

- the first screenshot shows the real 14-digit data
- the second screenshot shows the behavior more clear: >13 digits will be rounded

<img width="951" alt="image" src="https://user-images.githubusercontent.com/13319306/199952338-4c1c5d31-b7de-4cae-bc55-43a2efd8e86a.png">

<img width="951" alt="image" src="https://user-images.githubusercontent.com/13319306/199952147-8d0865b6-7f65-417e-8e73-dfa3c6b92c00.png">

**Comment by andrew-coleman** [comment]
It's the JSONata exerciser that is rounding the numbers, which is does to avoid displaying the tiny errors you get when trying to do integer arithmetic on numbers stored in a IEEE754 floating point format.

The JSONata processor itself simply returns a Javascript number, it's up to you how you convert it to a string.
