### ISSUE TITLE
Indirect field name as function input

### ISSUE THREAD

**Issue by sebas1986** [jsonata-js/jsonata#600]
Hi,

i'm trying to create a function that has as input the name of a subfield and internally extract the value. The problem is that when passing the subfield it does not return what I expect. 
This works (I know, it does not make sense but just to explain):
`(
  $getField := function($field){$.response.doc."_id"};
  $getField("_id");
)`

While this does not work:
`(
  $getField := function($field){$.response.doc.$field};
  $getField("_id");
)`

Any idea?

Many thanks

Sebastian

**Comment by markmelville** [comment]
this is what the [$lookup function](http://docs.jsonata.org/object-functions#lookup) is for.
```
(
  $getField := function($field){$lookup($.response.doc,$field)};
  $getField("_id");
)
```

**Comment by markmelville** [comment]
or just `$lookup($.response.doc,"_id")`, if you don't actually need to curry the function.

**Comment by sebas1986** [comment]
Many thanks for that, it solves my issue.
I take the chance to ask for an extra level of complexity on the same topic: what if I want to pass as variable input fields+subfields?
i.e. 
`(
  $getField := function($field){$lookup($.response,$field)};
  $getField("doc._id");
)`
It does not seem to work as above. What is your advice?

Sebastian

**Comment by markmelville** [comment]
[$eval](https://docs.jsonata.org/string-functions#eval) will do that nicely:
```
$eval("doc._id",$.response)
```
