### ISSUE TITLE
keys with spaces

### ISSUE THREAD

**Issue by ryanmerolle** [jsonata-js/jsonata#601]
Hello! I have a use case to try jsonata on API responses where spaces exist in some keys.  How would I go about tackling this. Quotes, parentheses, and other approaches did not work for me.

My alternative is to replace the spaces with underscores.  I would not normally post an issue, and use the GitHub discussion or a chat room, but I did not see any associated to this project.

Regards, thanks for this wonderful tool!

**Comment by markmelville** [comment]
the [docs](https://docs.jsonata.org/simple) state that "Field references containing whitespace or reserved tokens can be enclosed in backticks":
```
movies.`The Shining`.releaseYear
```

**Comment by ryanmerolle** [comment]
Ah missed that!  Thanks!
