### ISSUE TITLE
JSON dictionary to CSV

### ISSUE THREAD

**Issue by grosch-intl** [jsonata-js/jsonata#604]
My result set looks like this:

```json
{
   "result": [
       { "serial_number": "abc", "qdf": "xyz" },
       ...
    ]
}
```

I want to get back the value of the serial number, a comma, and then the value of the qdf.  So the output would be

> abc,xyz

for example.  Is there a way to do that?

**Comment by markmelville** [comment]
Yes.
```
result.(serial_number & ',' & qdf)
```
https://try.jsonata.org/1jR4TCizB

**Comment by grosch-intl** [comment]
Thanks!
