### ISSUE TITLE
Query Array element

### ISSUE THREAD

**Issue by urbanisierung** [jsonata-js/jsonata#608]
Hi!

One quick question: I'm trying to access an array element with a index  as an expression. Using a number element from the json is **not** working, using it within a `sum` function is working. Is that correct?

Example JSON:

```json
{
  "counter": 1,
  "array": [
    {
      "id": 1
    },
    {
      "id": 2
    },
    {
      "id": 3
    }
  ]
}
```

Not working query:

```
array[counter]
```

Working query:

```
array[$sum([counter])]
```

You can try it out on the playground at https://try.jsonata.org/

Thanks!

**Comment by markmelville** [comment]
within the `[]` the context is no longer the root json doc, so even with `sum([counter])` counter is undefined, and sum of [undefined] is 0, returns the first item.

Using the actual value of counter (using root operator) returns 1, so that is the second item in the array:
```
array[$$.counter]
```

**Comment by urbanisierung** [comment]
Oh wow, thanks a lot for the fast response!!
