### ISSUE TITLE
What license is the jsonata logo

### ISSUE THREAD

**Issue by lublak** [jsonata-js/jsonata#613]
Hi :)

i'm currently building a n8n node for jsonata.
My question here is what license is the logo? Also MIT? Because its in the same repo under websites.
I would like to use it as an icon for the node if I am allowed.

**Comment by andrew-coleman** [comment]
Hi @lublak, thanks for asking.  I'd never given it any thought, but I guess it ought to be one of the creative commons licenses.  Anyway, you have my permission to use it in your n8n node.

**Comment by lublak** [comment]
@andrew-coleman thanks for the answer :)

And I am of the opinion that such a thing must be asked and should not simply be used without questions.
The graphic does not belong to me.
