### ISSUE TITLE
Release version 2.0.2 - Unreleased type declaration fixes

### ISSUE THREAD

**Issue by soof-golan** [jsonata-js/jsonata#619]
Hey awesome maintainers, Is there a possibility to issue a release of the latest code in this project.

A project I'm working on is using Typescript and the [recently added promise type declaration](https://github.com/jsonata-js/jsonata/blob/9fe64acefcd138f67f8519c5b927cf06e52292ec/jsonata.d.ts#L40) would make our upgrade to jsonata 2.0 much smoother!

Many thanks for your awesome work ❤️

**Comment by sebastianrothe** [comment]
We have been running into this problem too.
