### ISSUE TITLE
The lexer for a regex terminating character doesn't handle escapes correctly

### ISSUE THREAD

**Issue by Ben-Steele** [jsonata-js/jsonata#624]
JSONata version: 2.0.2
node version: 16.18.0

The Regex lexer does not properly determine if the terminating "/" of a regex is escaped.  It does not consider escaped escape characters.
example:
jsonata expression - `$match("test escape \\", /\\/)`
result - `No terminating / in regular expression`
expected result - `{ match: "\", index: 12, groups: []}`

See proposed fix in this PR: https://github.com/jsonata-js/jsonata/pull/623/files

**Comment by andrew-coleman** [comment]
Resolved by #623 

Many thanks.
