### ISSUE TITLE
How to remove duplicate element in data 

### ISSUE THREAD

**Issue by durgashree1** [jsonata-js/jsonata#626]
{"Account ":{"order":[
{
"Product":
{"Name":ram
},
{"Name ":ram},
]}},
{"Name":abi}
}

Code
Account.oder . product.(Name)
I am getting output as 
[Ram,
Ram,
Abi
]
 But I need output as 
[Ram,
Abi]
If duplicate element occurs it should remove the element

**Comment by markmelville** [comment]
`$distinct` was added a few years ago ([docs](https://docs.jsonata.org/array-functions#distinct)), but I can't give you the expression you need because your JSON is malformed. it might be something like:
```
$distinct(Account.order.Product.Name)
```
