### ISSUE TITLE
"Non-wildcard multiple selection" not working on the demo site as documented

### ISSUE THREAD

**Issue by mosbasik** [jsonata-js/jsonata#63]
(Aside: this is an awesome project; I'm enjoying using it in Node-RED!)

## Description

In the docs, on the [page about result structures](http://docs.jsonata.org/construction.html), in the section on array constructors, the third example (non-wildcard multiple selection) doesn't seem to be working as described when run against http://try.jsonata.org/ 's `Address` dataset.

## Current Behavior:

Input | Output
---- | ----
`Address.City` | `"Winchester"`
`Other.'Alternative.Address'.City` | `"London"`
`[Address, Other.'Alternative.Address'].City` | `** no match **`

## Desired Behavior:

Input | Output
---- | ----
`Address.City` | `"Winchester"`
`Other.'Alternative.Address'.City` | `"London"`
`[Address, Other.'Alternative.Address'].City` | `[ "Winchester", "London" ]`

**Comment by andrew-coleman** [comment]
Thanks for raising this.  
The fix is now in master, and pushed to NPM in v1.2.6
