### ISSUE TITLE
Unable to filter object based on a matching attribute in another object

### ISSUE THREAD

**Issue by raj-work** [jsonata-js/jsonata#64]
Hi,
We are stuck with a problem and am not sure if I missed something. I am trying to filter an array by matching an attribute in another array but it doesnt seem to work.
For eg., 
Accounts.Order[OrderID = Account.Shipping.OrderID] should result in the Order array filtered by matching orderID. In this example, Shipping is an object as well. I tried to use the $filter function as well with no success. Any help on how to solve this would be helpful. If this is a known limitation, please suggest a workaround.

**Comment by andrew-coleman** [comment]
This is failing because it is trying to find `Account` as a property of `Order`.  Everything within the square brackets is evaluated in the context of each Order.  So you need to tell it that `Account` is a property of the root of the JSON structure.  You do this using the `$$` syntax (see http://docs.jsonata.org/programming.html#built-in-variables).  The following expression should do what you need:
`Accounts.Order[OrderID = $$.Account.Shipping.OrderID]`

**Comment by raj-work** [comment]
@andrew-coleman  thanks for the quick response. Thanks helped.
I was earlier trying with $ and not the $$ which was my mistake.

**Comment by raj-work** [comment]
@andrew-coleman it looks like i had some cached response. when i tried what you suggested, it still is not working. I am getting no match even though i have the same OrderID in both.

**Comment by mattbaileyuk** [comment]
@raj-work Not sure if the difference between `Accounts` and `Account` both in your example and @andrew-coleman's suggestion is the key here. I added a `shipping` object with an `orderID` and used `Account.Order[OrderID=$$.Account.Shipping.OrderID]` to successfully match only the order which was listed in the `shipping` object, which is what I'd interpreted your original query to be. See http://try.jsonata.org/rkEXhYt4b

If that's not what you're looking for, could you please share the structure of your data via the try.jsonata.org exerciser.

**Comment by raj-work** [comment]
@mattbaileyuk it works if there is only one Shipping object. But if I have more than one Shipping object, it doesnt work. So, I was not sure if that is something which is not supported.

**Comment by andrew-coleman** [comment]
In that case, use
`Accounts.Order[OrderID in $$.Account.Shipping.OrderID]`

See http://docs.jsonata.org/operators.html#in

**Comment by raj-work** [comment]
@andrew-coleman That worked!! Seems like I was missing the "in" eventually. Thanks for all your support. Happy 4th 👍
