### ISSUE TITLE
JSONATA Excersiser can't be shared

### ISSUE THREAD

**Issue by mickym2** [jsonata-js/jsonata#649]
I can no longer share the JSONATA Exerciser window. I have to confirm that i am not a robot - but after that this window does not disappear and provide a link, which can be shared

**Comment by mattbaileyuk** [comment]
Unfortunately there's an issue with the database that underpins that functionality that we're trying to get resolved.

**Comment by mattbaileyuk** [comment]
This has now been fixed.
