### ISSUE TITLE
Jsonata with J2V8

### ISSUE THREAD

**Issue by vtec11001** [jsonata-js/jsonata#65]
Hi I am currently in a situation where I need to run the Jsonata script under a Java environment. Currently we are using nashorn to do this but we heard that a new library called J2V8 is much faster in running JS inside Java. I was wondering if anybody here has any experience running J2V8 with the JSONATA.js script. I ask this because I am currently trying to run jsontata.js with j2v8 but keep getting a  "java is not defined error". Any input would be great. I have also taken the time to provide our current nashorn code and j2v8 code in case anybody is familiar with the 2. 

Nashorn:

`

        Invocable inv = (Invocable) scriptEngine;
        scriptEngine.put("input", jsonString);
        Object inputjson = scriptEngine.eval("JSON.parse(input);");

        // query the data
        Object expr = inv.invokeFunction("jsonata", jsonPath);
        Object resultjson = inv.invokeMethod(expr, "evaluate", inputjson);

        // JSON.stringify the result
        scriptEngine.put("resultjson", resultjson);
        result = scriptEngine.eval("JSON.stringify(resultjson);");

`

J2V8

`
                runtime.executeScript(provided_js_script); 
		V8Function jsonataFunction = (V8Function)runtime.getObject("jsonata"); 
				
		V8Array arrayJsonata = new V8Array(runtime).push(jsonPath[0]); 		

		V8Object jsonataResult = (V8Object) jsonataFunction.call(null, arrayJsonata);

`

**Comment by andrew-coleman** [comment]
@raj-work has also been looking at J2V8 (see https://github.com/jsonata-js/jsonata/issues/47#issuecomment-304311828).  @raj-work - anything you can share with us on this?  It's not something I have looked at yet.

**Comment by vtec11001** [comment]
hi I just wanted to note that I was finally able to get j2v8 to work with jsonata. The key seems to be to create a wrapper function that calls jsonata and the evaluate functions and in the j2v8 you would simply call that wrapper function which then calls the respective jsonata and then evaluates your input expression.

**Comment by andrew-coleman** [comment]
@vtec11001 - cool, that's great to hear.  Any chance you could share some code and examples with a little explanation of how you made this all work?  This would be really useful for others (including me) to get started.  Perhaps in the form of a blog post in a forum of your choice, or a markdown file that I could link to from this repo.  Any contributions like this would be highly appreciated.
Thanks!

**Comment by vtec11001** [comment]
@andrew-coleman yes I can! I apologize for the delay. I can provide a rough outline here and then provide a more formal write-up as I currently do not have a formal blog to post to...

QUICK OVERVIEW

My current implementation is made up of vanilla JS code and the J2V8 code. The core idea is under the jsonata function in the jsonata.js file, create a wrapper/runner function that calls the jsonata function and the resultant evaluate code. An example is provided below:

`
//MUST PLACE BELOW JSONATA FUNCTION IN JS FILE

function runJsonata(inputData, expressionInput)
{
     //the inputData is the JSON File and the expressionInput is the jsonata expression. 

    if (expressionInput != null)
    {
        var functionResult = "";
        inputData = JSON.parse(inputData);
        //set the data to valid format.

        var expression = jsonata(expressionInput);
        functionResult = expression.evaluate(inputData); 
        return functionResult; 

}`

With this function written all the user has to do in the J2V8 (as a side note J2V8 is perhaps the fastest method for calling JS code in Java)  is execute the following lines of code:


`      	V8 v8 = V8.createV8Runtime(); 
        String result = null; 
        result = v8.executeJSFunction("runJsonata", jsonFile, jsonExpression).toString(); 
        return result; `

Key Points:  The function params are mirrored in the jsonFile and jsonExpression and the function call/function name is reflected in the "runJsonata" string input. The variable result is the result of your jsonata and resultant expression.evaluation function. I will provide a more formal write up soon but I hope this helps in the meantime. I would recommend taking a look at J2V8 Github as well to see the library in more detail https://github.com/eclipsesource/J2V8. Thanks!

**Comment by andrew-coleman** [comment]
closing as resolved
