### ISSUE TITLE
Unsupported escape sequence

### ISSUE THREAD

**Issue by ericwood73** [jsonata-js/jsonata#66]
There seems to be an issue with jsonata transforms that have a literal \T in them (such as a value for a JSON attribute that is a windows path C:\Test\test.txt.  Interestingly this works correctly in the JSONata exerciser using a transform like
```
(
  $path := "\"C:\\Test\\test.txt\"";
  {
    "path": $path
  }
)
```

But it fails when I pass that transform as a string to the transformer

```
const transform = "{\"foo\": \"C:\\Test\\test.txt\"}";
// Compile the transform
  let transformer;
  try {
    transformer = jsonata(transform);
  }
  catch(error) {
    // Compile error.  Try to provide more useful information abut the error
    if (error.position) {
      throw new Error(`Transform compilation error: ${error.message} around "${transform.substring(error.position - 20, error.position + 20)}"`)
    }
  }
```

with Error: Transform compilation error: Unsupported escape sequence: \"T" around "{"foo": "C:\Test\test.txt"}"

It also fails with C:\pest and C:\sest, but not with C:\fest, so it appears it is trying to treat \t, \s, and \p (case insensitive) as escape sequences.

**Comment by andrew-coleman** [comment]
I think the problem here is that the Javascript string constructor is interpreting those escape sequences before they are being passed to JSONata.  So you will either need to double escape them using 
`const transform = "{\"foo\": \"C:\\\\Test\\\\test.txt\"}";`
(if you surround the whole string in single quotes, you won't need to escape the double quotes)

or if you are using ES6, use [raw strings](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Template_literals#Raw_strings):
``const transform = String.raw`{"foo": "C:\\Test\\test.txt"}`;``

**Comment by andrew-coleman** [comment]
Closing this issue.  Please re-open if you are still having problems.

**Comment by yerol** [comment]
I'm having the same problem with single quotes in strings in the exerciser. I tried the following but none worked. Back tick doesn't work at all. What's the right way of using single quotes for strings?

$speak := 'There isn\'t enough data to provide any insight';
$speak := 'There isn\\'t enough data to provide any insight';
$speak := 'There isn\\'t enough data to provide any insight';
$speak := `There isn't enough data to provide any insight`;

**Comment by yerol** [comment]
I can't use double quotes as I need to store this as stringified json. Can you think of another way?

**Comment by andrew-coleman** [comment]
`$speak := 'There isn\u0027t enough data to provide any insight'`

**Comment by yerol** [comment]
yep, that works, thanks a lot!

**Comment by yerol** [comment]
Ok, it works on the exerciser but fails when evaluation the code: 

"Expected ")", got "t""

**Comment by ijavidilo** [comment]
Hello @yerol,
If you need the single quote with JSONata you could try this:

`$speak := 'There isn' & $decodeUrlComponent("%C2%B4") &'t enough data to provide any insight'`

Hope it works for you!
Regards!
