### ISSUE TITLE
JSONATA $map with conditional statement

### ISSUE THREAD

**Issue by vtec11001** [jsonata-js/jsonata#67]
Hello I am currently trying to use the JSONATA $map statement that contains a conditional statement with my json path. An example of the code I am working with is provided below. 

`$map(--somejsonpath--, function($v, $k) {($v.example.value = "test" and $v.example.value.data = "device" and $v.example.value.valueInt  > 1) ? $k})`
Currently when I run this code I get an error that notes:

`"Error\n    at validate (<anonymous>:1881:29)\n    at evaluateComparisonExpression (<anonymous>:1904:17)\n    at evaluateBinary (<anonymous>:1604:30)\n    at next (native)\n    at evaluate (<anonymous>:1332:26)\n    at next (native)\n    at evaluateBinary (<anonymous>:1586:19)\n    at next (native)\n    at evaluate (<anonymous>:1332:26)\n    at next (native)","value":"32","value2":1,"position":5,"token":"map","message":"The values \"32\" and 1 either side of operator \"map\" must be of the same data type"}`

With the expression $v.example.value.valueInt I am essentially trying to acces the valueInt and see if it is greater than 1. The issue is however that it is in a set of nested arrays. I understand the params for the $map function are an array but for some reason I cannot get it to work with nested arrays. Is there any way I could get it to work with the current nested arrays I have now? Any help is appreciated, thanks.

**Comment by andrew-coleman** [comment]
It seems to be trying to compare the number 1 with the string "32".  
It would be really helpful if you could share your test data.  Please could you put the data and expression into the JSONata exerciser (try.jsonata.org), click the 'save and share' button then paste the link into this issue?  Thanks.

**Comment by vtec11001** [comment]
Thank you for your response. I actually think I may have found the problem. When we run the comparison tenure (in this case is written as "32" in the JSON) we are trying to compare the string "32" against int/number 1. I was able to solve this issue by simply making the 1 into a "1". I will however provide my extra test data. tryjsonata is currently blocked for some reason on my end.

**Comment by vtec11001** [comment]
So I am currently blocked from tryjsonata in my current setting but here is a rough sketch of the data I have if it helps....


`      "orderLineCollection": {
        "orderLines": [
          {
            "promotions": [
              {
                "discount": {"tenure": "30"}
              },
              {
                "discount":{"tenure" : "54"}
              }
            ],
}]
}`

and here is the current code we have:

`var expression = jsonata("$map({--parent json path--}, function($v, $k) {($v.promotions.discount.tenure > '1')})");`

we get the error the moment we add another discount object under promotions. If we were to remove the extra discount object it works fine. I will again try to send a link directly to the tryjsonata sit if I can but it is currently blocked. Any help is appreciated, thank you.

**Comment by andrew-coleman** [comment]
If there is more than one discount object, then it will error because it will be trying to compare an array of strings with a single string.  A solution to this would be to map the function to each discount  within each orderLine like this:
```
$map(orderLineCollection.orderLines.promotions.discount, 
     function($v, $k) {
       $v.tenure > '1'
     })
```
but it depends on what exactly you want to achieve.  I suspect from the original question above you want to return the name of each property whose value matches a certain condition.  If you can give more information on the scenario you want to solve, I'll be very happy to help further.

Another thing to be aware of -  the comparison operators when applied to strings will compare their unicode codepoints (in other words compare by alphabetical order) which is probably not what you want here.  If you have numbers stored in JSON strings and want to do numeric comparison, then you need to explicitly cast it to a number first using the `$number` function.  E.g. `$number($v.tenure) > 1`

**Comment by vtec11001** [comment]
Thank you, I apologize for not posting this earlier but we did get it and this was the solution we used. 

I was wondering however if there was any way we could compare non array elements in the map function or similar higher-order-functions. I ask this because in the current code above (in the example you provided me) that code will evaluate into an array of Boolean and we just want to check if the array includes at least one true but currently $map dosent seem to allow us to do that as the return value would be a single boolean. We could create a new array from the result that just containts it, but that would already add a lot of complexity to an already complex expression.

**Comment by andrew-coleman** [comment]
The [in](http://docs.jsonata.org/operators.html#in) operator tests for inclusivity of a value in an array, so `true in [false, false, true, false]` will return `true`.
Also, the [$boolean()](http://docs.jsonata.org/boolean-functions.html#booleanarg) function will cast an array to `true` if it includes a value that casts to `true`.

If you are using the `$map` function purely for the purpose of filtering, then you might be able to use a filtered path expression.  Consider the following (using your sample data):
```
orderLineCollection.orderLines[promotions.discount.($number(tenure) > 1)]
```
The sub-expression within the square brackets will get applied to each object in `orderLines`.  It will get evaluated then cast to Boolean using the same rules as the `$boolean` function above.  You can play with this example in the exerciser here -> http://try.jsonata.org/rkatXg3rW 
If you increase the number on the right of `>` from `1` to `54` or more, then the result no longer contains that object in `orderLines`.  If you have multiple objects in orderLines, then this expression will filter it down to only those that contain a discount tenure that matches the condition.

Hope that makes sense, and again I'm happy to refine this example further if it doesn't quite match your scenario.

**Comment by vtec11001** [comment]
Thank you this makes things clearer. Sorry for the delay in response, as my issues with $map have been fixed for now I will close this issue. Thank you.
