### ISSUE TITLE
is 2.0.4 a fake release?

### ISSUE THREAD

**Issue by khera** [jsonata-js/jsonata#680]
On npmjs (and `npm outdated` in my project) it is showing version 2.0.4 was released a few minutes ago. I came to this github project to see what was changed and find that the latest release is still 2.0.3. From where would a newer version get pushed to the npm registry? This seems a little suspicious. The official site still links to this repo, so I think that should be authoritative.

<img width="821" alt="Screenshot 2024-02-29 at 12 41 24" src="https://github.com/jsonata-js/jsonata/assets/367424/b0bc9b45-e624-4670-8bb0-401fb9bee460">

**Comment by mattbaileyuk** [comment]
Yes, it's a real release 🙂 You can see the commit to publish it at https://github.com/jsonata-js/jsonata/commit/ea8fb852be7d62de353af2fb90f92d47aafd22ac - there just hasn't been a "Release" created in GitHub yet (it's a separate process which just tags commits from a branch, so isn't tied directly to npm)

**Comment by mattbaileyuk** [comment]
There is now a GitHub Release for `2.0.4` with the details at https://github.com/jsonata-js/jsonata/releases/tag/v2.0.4, although the release commit did include a `CHANGELOG` update.

**Comment by khera** [comment]
Thanks for following up. I'm curious why you don't drive the publishing GitHub actions triggered by tagging a release?

**Comment by mattbaileyuk** [comment]
I didn't configure the initial workflow, but I suspect it was just following on from how the previous Travis configuration was working. It might be worth us switching over to the Release approach at some point.
