### ISSUE TITLE
a better way of calling evaluate 

### ISSUE THREAD

**Issue by vtec11001** [jsonata-js/jsonata#69]
Hello I was wondering if there was a better way of calling evaluate. To expand, currently in Jsonata to evaluate on a set of data we execute the following code: 

`

var jsonata = require("jsonata");

var data = {
  example: [
    {value: 4},
    {value: 7},
    {value: 13}
  ]
};
var expression = jsonata("$sum(example.value)");
var result = expression.evaluate(data);  // returns 24

`

As we can see in this code, when we call expression.evaluate we are calling it on a set of js/json data. Currently I am writing an internal script which calls the expression.evalute on a set of the same data each time a new expression is put in the jsonata function to get the expression. I was wondering if there was perhaps a way to simple call our expression.evaluate on a set of data once, and then call jsonata(--some expression--) multiple times as our data is never changing and only are input expressions are. If further clarification is needed I can provide it. 

I should note I understand I can assign variables to certain values and hold it in memory, but was wondering if I could do this similar thing to entire json files. Again if this is confusing I can provide examples of my issue.

**Comment by blgm** [comment]
The design of JSONata is to build the expressions once and evaluate the same expression against different data, for example:
```js
const expr = jsonata('foo.bar')
expr.evaluate(data1)
expr.evaluate(data2)
expr.evaluate(data3)
```
This is because parsing the expression can be computationally costly, and you might want to cache built expressions.

As I understand it, your case is the reverse: you want to evaluate different expressions against the same data.  One way to achieve this would be to simply make your expression more complete, so instead of:
```javascript
const result1 = jsonata('foo.bar').evaluate(data)
const result2 = jsonata('foo.baz').evaluate(data)
const result3 = jsonata('bax.bar').evaluate(data)
```
You could have an expression that evaluates all three at the same time, such as:
```javascript
// Must be a string
const expression = `{
  "part1": foo.bar,
  "part2": foo.baz,
  "part3": bax.bar
}`
const result = jsonata(expression).evaluate(data)
const result1 = result.part1
const result2 = result.part2
const result3 = result.part3
```
Check out an example: http://try.jsonata.org/ryuVA5PU-

Does this help with your use case?

**Comment by vtec11001** [comment]
Hi! I would first like to say thank you for your response. In terms of our case, we actually implement something similar to the solution you posted, but this is in a different implementation than the one I am working on. In terms of the one I am working on I believe your solution may actually work, as currrently I essentially have to evaluate expressions at certain repeating points in a giant JSON document. I currenlty do this by calling jsonata one at a time at each point. I will now try your implementation by collecting these expressions and evaluating them at once. Thanks for your help!

**Comment by vtec11001** [comment]
@blgm actually as I work though this for my specific project/task it seems your approach not might work in my case...The issue I have is that I have a giant JSON that I need to call jsonata on as I traverse down the JSON I need to contantly call jsonata and use the same input file for each call. I was wondering if there was any way I could just load my respective JSON file (the one I put as the params for the evaluate function) and then freely call jsonata function with different expressions without having to constantly call the same file for the evaluate params. If further clarification is required, I am happy to provide. Thank you!

**Comment by blgm** [comment]
@vtec11001, as JSONata requires all the JSON to have been parsed into a JavaScript object, there is no computing efficiency to be gained by calling `evaluate()` only once.  However this touches on the limitation that JSONata acts on JavaScript objects, and therefore cannot be used on a JSON structure that is too large to be held in memory.  See https://github.com/jsonata-js/jsonata/issues/45 for a discussion on that.  If your giant JSON can be be held in a JavaScript object then calling `evaluate()` multiple times should work reasonably efficiently.   If the JSON object is too large to be held in memory, then you could consider combining it with a partial JSON parser such as [JSONStream](https://www.npmjs.com/package/JSONStream) which will break the JSON object into a series of smaller JavaScript objects which JSONata can act on.  We don't have any experience of doing that, but are keen to understand the use cases for handling large JSON objects and JSON streams.

**Comment by andrew-coleman** [comment]
@vtec11001, another idea.  If you are looking to apply lots of expressions to a single JSON input, you could combine all of your expressions into a single object containing name/expression pairs and evaluate that once.  For example, if you have the following 3 expressions:
`Account.Order[0].OrderID`   -->  `"order103"`
`$sum(Account.Order.Product.(Price * Quantity))`  --> `336.36`
`$count(Account.Order.Product)`  --> `4`
you could combine them and evaluate the following once:
```
{
  'expr1': Account.Order[0].OrderID,
  'expr2': $sum(Account.Order.Product.(Price * Quantity)),
  'expr3': $count(Account.Order.Product)
}
```
to produce the combined result:
```
{
  "expr1": "order103",
  "expr2": 336.36,
  "expr3": 4
}
```
See this example in the exerciser: http://try.jsonata.org/ByVyuGl9Z

**Comment by vtec11001** [comment]
@andrew-coleman thank you for mentioning this implementation. I wasn't aware that the expressions could be contained in json itself.

**Comment by andrew-coleman** [comment]
Closing this issue, as I think it is now resolved.  Feel free to re-open if you have any follow on questions.
