### ISSUE TITLE
$sort fails for >6000-element arrays

### ISSUE THREAD

**Issue by Gonosz94** [jsonata-js/jsonata#696]
Unfortunately the title says it all. I'm using jsonata in Grafana Infinity datasource, and I need to sort larger datasets (3500-4000 elements for now but will be more in the future). I experimented with sorting, and 5000-5100 element arrays are good, but anything above that will fail.

**Comment by CommanderStorm** [comment]
Failing can mean a lot of things.
What do you mean specifically?

**Comment by mattbaileyuk** [comment]
Closing as inactive; agree I don't know what failing means here, I suspect large data sets may run into performance issues but I've not seen evidence of it falling over.
