### ISSUE TITLE
Why is jsonata async/await?

### ISSUE THREAD

**Issue by dakhnod** [jsonata-js/jsonata#697]
Hi, thanks for your work! The following question is purely, educational:

Why is the jsonata API asynchronous?
After all, there is no networking or FS involved, right?
Isn't jsonata purely CPU computation? 

Thanks!

**Comment by markmelville** [comment]
take a look at the PR for the reasons given straight from the horse's mouth: https://github.com/jsonata-js/jsonata/pull/583

**Comment by dakhnod** [comment]
Ah, thanks!
