### ISSUE TITLE
how to access the key value in a object which is outside of the object.

### ISSUE THREAD

**Issue by Sujata-060** [jsonata-js/jsonata#709]
{
      "isVisibleCondition": true,
      "Questions": [
        {
          "QuestionChoices": [
            {
              "choiceTextInDefaultLanguage": "YES",
              "isDefault": false,
              "scoringValue": 0
            },
          ],
          "textDataType": 0
        }
      ],
      "visibleCondition": {
        "filterConditions": [
          {
            "fieldCondition": {
              "answerCode": "NO",
              "questionCode": "Q3"
            },
          
          }
        ]
      }
    }, in this how to access isVisibleCondition" inside the answercode of visibleCondition

**Comment by markmelville** [comment]
This expression demos 3 ways to do it. https://try.jsonata.org/vusDWtfWM
```
$.(
    $isViz:=isVisibleCondition;
    visibleCondition.{
        "filters": filterConditions,
        "isViz": $$.isVisibleCondition,   /* root input variable */
        "isViz2" : %.isVisibleCondition, /* parent operator */
        "isViz3": $isViz                            /* captured in variable */
    }
)
```
BTW, you could have made this a lot easier with a well-formatted JSON.

**Comment by Sujata-060** [comment]
Thank you for the response @markmelville

**Comment by Sujata-060** [comment]
Hi,  @markmelville ,my issue is not resolved, please can i connect with you, it will be a great help, Kindly reply sir

**Comment by markmelville** [comment]
On the exerciser page, there is a button to get an invite to the slack group. I suggest you join that to get more help.

**Comment by mattbaileyuk** [comment]
Thanks for helping out here, @markmelville :+1:
