### ISSUE TITLE
how can i combine objects

### ISSUE THREAD

**Issue by nick121212** [jsonata-js/jsonata#71]
"skus":[{"a":1,"c":3},{"b":2}]  
to
skus:{ "a":1,"b":2,"c":3 }

**Comment by andrew-coleman** [comment]
Hmm - looks like we are missing a simple `$merge()` function.  I'll add one to the next release.
Thanks!

**Comment by andrew-coleman** [comment]
Function `$merge()` has been added to branch `1.3`.  This function takes an array of objects as its first (and only) argument, and returns a single object containing all the key/value pairs from each of the objects in the input array.  For clashing keys, the last one in the array wins.  A type error is thrown if the input array contains any values that are not objects.

**Comment by andrew-coleman** [comment]
`$merge()` is now in the master branch and published to npm in v1.3.
Closing as fixed.
