### ISSUE TITLE
Support for embedded comments within expressions

### ISSUE THREAD

**Issue by andrew-coleman** [jsonata-js/jsonata#75]
During discussion of [another issue](https://github.com/jsonata-js/jsonata/issues/70#issuecomment-326428722), it became clear there is a desire to be able to embed comments within multiline expressions.

Options discussed included aligning with other scripting languages that use `#` to indicate the start of a comment, or Javascript/Java/C that use `//` or `/* ... */` for comments.

This issue can be used to host any further discussion on this requirement.

**Comment by Allam76** [comment]
Hello there, what happened with this issue? I'm working on the code completion and comments would greatly help there.

**Comment by andyh3930** [comment]
Being able to leave comments would be greatly appreciated. Is there any update on this issue?

**Comment by nabeelz6** [comment]
Agreed. Having comments within a long expression string would be very helpful.

**Comment by janvda** [comment]
It would be great to be able to add comments.  
Not only in multiline expressions but also in single line expressions.

E.g. I am using jsonata in node-red to parse unix command line output.  Being able to add comments would make is much clearer what the purpose of the jsonata expression is.

**Comment by ryanlunka** [comment]
I'll +1 this feature request as well.

We make very heavy use of JSONata to transform retail/eCommerce business documents (like orders or retail items), often doing so with JSONata transformation documents that are hundreds of lines long, and make heavy use of variables and other complex logic.

Having commenting built in would make dealing with large JSONata documents much easier.

**Comment by natcl** [comment]
+1
