### ISSUE TITLE
Code completion

### ISSUE THREAD

**Issue by Allam76** [jsonata-js/jsonata#76]
Hello there.

Is there any plans for code completion? Maybe based on source and target json schemas?

If you have a grammar for jsonata, I could maybe start working on one using peg.js?

**Comment by andrew-coleman** [comment]
Hi - this is an interesting topic.  I briefly looked at this a while back for the jsonata [exerciser](http://try.jsonata.org/), which uses [CodeMirror](https://codemirror.net/doc/manual.html#modeapi) for the editor panels.  Although it wouldn't be part of the core jsonata runtime, a component that supports code completion would be a really useful addition, especially if written in a way that could be plugged into different editor frameworks.

It would be great if you are interested in working on this.  I'm not familiar with peg.js, although I do have some experience with BNF grammars.  However, the JSONata parser is not generated from a BNF grammar but rather hand coded using [Pratt's](https://en.wikipedia.org/wiki/Pratt_parser) top-down operator precedence algorithm (see [here](http://javascript.crockford.com/tdop/tdop.html) for an excellent description).  The code for it is [here](https://github.com/jsonata-js/jsonata/blob/master/jsonata.js#L603) and the relative operator precedences are defined [here](https://github.com/jsonata-js/jsonata/blob/master/jsonata.js#L21).  I imagine a grammar could be derived from this.  Let me know if you need anything.

**Comment by Allam76** [comment]
Hmm, as I expected, the code and operator precedences are a bit too off to make a grammar file from. That leaves me two options:

1) Modify the jsonata source particularly in the evaluateVariable and evaluateLiteral functions and somehow lookup the schemas from there. I have some experience building a code completion this way and found that it is quite intrusive:-(

2) Use the JMESpath grammar, which should be similar, add the missing pieces on top. Much less intrusive but unsure how to organize the output structuring.

Give me a hint if you have any of these sounds better.
Cheers
Martin

**Comment by Allam76** [comment]
I added a simple code completion that can be seen in this repo: [github](https://github.com/Allam76/jsonata-code-completion). The error messages are enhanced with a proposal object. Check out the tests.

It uses a framework object to decide how the proposals are used. In this case it is a json schema. Only the source has code completion, for target we can use a normal json schema tool, there are plenty of these.

Not all is there, we should have support both for variables and function parameters. However, I'm not sure how to extract the assigned variables. Same for the functions and then the function parameter types. Also the global variable should be addressed.

If someone could point out how to get the assigned variables and functions, then I could continue with the rest.

/Martin

**Comment by andrew-coleman** [comment]
All variables are held in the `environment` which is a stack of `frame` objects created here:
https://github.com/jsonata-js/jsonata/blob/master/jsonata.js#L4048
This `environment` is passed around the variable evaluate functions during expression evaluation.
The frames all link back to a global `staticFrame` object which contains all the built in functions (note that functions are just variables that bind to function bodies).  The frame object contains methods `bind` and `lookup`.  We might need to add an `entries` method to list all of the in-scope bindings in order to support what you need.

**Comment by Allam76** [comment]
Super! That should point me in the right direction. We would also have to deal with scopes and that can be a bit tricky... I'll see what makes sense.

**Comment by andrew-coleman** [comment]
Closing this issue since I think there is no more work here.  Re-open if you disagree.
