### ISSUE TITLE
Proposal: Mixins?

### ISSUE THREAD

**Issue by Allam76** [jsonata-js/jsonata#82]
Hello Andrew.

I open a new issue regarding mixins.

Currently with a few lines of code, I can extend jsonata to fetch missing data from a database with orm relations. Other data sources could also be possible. 

I would like a standardized way of these extensions, typically by the way of mixin. 
Example.
Instanciation:
```  js      var mixins = {
            "orm": function(input, expr){
                const Model = require('objection').Model;
                // If input is a model class instance and has orm relation
                if(input instanceof Model && input.constructor.$$relations[expr.value]){
                    //load relation from db
                    return input.$relatedQuery(expr.value);
                }
            }            else{
                for(var mixinName in mixin){
                    mixin[mixinName](input,expr);
                }
            }
        }
        expression.evaluate(data, bindings, callback, mixins);
```

In jsonata, method evaluateName, if nothing found:
```   js         else{
                for(var mixinName in mixins){
                    mixins[mixinName](input,expr);
                }
            }
```
 
What do you think?

Cheers
Martin

**Comment by xogeny** [comment]
It isn't entirely clear to me what the semantics of what you propose would be.  Is there some reason you can't simply bind this function and use it in your expressions directly?

**Comment by Allam76** [comment]
In my understanding a mixin is supposed to replace the standard code without altering the code itself. The purpose is to have custom extensions to standard code without having to worry every time the standard code gets upgraded.

If I changed something inside jsonata, then I would have to modify every time I upgrade. This concept is supposed to avoid that propblem. So a simple function can't do it since I want to change standard code.

Hope this is clear.
Martin

Example use in jsonata:
```
    function evaluateName(expr, input, environment) {
        // lookup the 'name' item in the input
        var result;
        var mixins = environment.lookup('mixins');
        
        if(mixins && mixins.evaluateName) return mixins.evaluateName(expr, input, environment);
```
If mixin exist, it is called instead of the default implementation.

usage:
```
        expression.evaluate(input,{},(rej,res)=>{
          if(rej) reject(rej);
          resolve(res);
        },mixins);
```

**Comment by xogeny** [comment]
I think I understand what you mean here.  I had some similar use cases which is what brought me here.  I think the best approach here would be to actually implement some kind of API for developers to override the various tree walking functions.  I've initiated a discussion with @mattbaileyuk and @andrew-coleman about this to get their feedback.  If they are not opposed to the idea, I could write a prototype of what I have in mind.

**Comment by Allam76** [comment]
Great! Wonderful idea! A central approach would be fantastic.

I also have a minimal approach that works for my limited needs. In fact, that is the one you see above. Might be useful as an inspiration.

Many thanks for your effort!

**Comment by xogeny** [comment]
@Allam76 Glad you like the idea.  No need to thank me for my effort since I haven't actually made any effort yet.  That's going to depend on the feedback I get from @mattbaileyuk and @andrew-coleman. 😃

**Comment by andrew-coleman** [comment]
Closing this issue. Sounds like @xogeny's implementation might address this which will hopefully be the basis for the next major version of JSONata.
