### ISSUE TITLE
Class in path

### ISSUE THREAD

**Issue by Allam76** [jsonata-js/jsonata#84]
Hello Andrew,

If a ES6 class definition is in the path, it is not picked up.

In the code 1800:
```js
        } else if (input !== null && typeof input === 'object') {
```
This means that classes cannot be used. I propose the following addition:
```js
} else if (input !== null && ( typeof input === 'object' || isClass(input))) {
```
where isClass is defined as:
```js
    function isClass(func) {
        return typeof func === 'function' 
            && /^class\s/.test(Function.prototype.toString.call(func));
    }
```

/Martin

**Comment by andrew-coleman** [comment]
JSONata operates on *JSON* input data.  JSON has no concept of classes.  As a general rule, if the input cannot survive a cycle of JSON.stringify() / JSON.parse(), then it's not a suitable input for JSONata.

**Comment by Allam76** [comment]
I'm a bit sad to hear that. Jsonata could be used for so much more....

Anyway, could then the "mixin" concept be supported, so that I can override the functions I need with custom code without breaking every time you update the release?

**Comment by andrew-coleman** [comment]
Closing this issue.  Sounds like @xogeny's implementation might address this which will hopefully be the basis for the next major version of JSONata.
