### ISSUE TITLE
$lookup() function throws an error when the property has a null value

### ISSUE THREAD

**Issue by shrickus** [jsonata-js/jsonata#85]
The incoming weather data object may contain some fields with null values -- like this:
```
{
  "temp": 22.7,
  "wind": 7,
  "gust": null,
  "timestamp": 1508971317377
}
```

I'm using the `$lookup()` function to find the "gust" value, with this expression:
```
{
	"x": $$.timestamp,
	"y": $lookup($$, "gust")
}
```

Instead of getting the property `"y": null` in the output object, this error is thrown instead:
`Invalid operand to 'in': Object expected`

Since I can use `$$.gust` to return the value `null`, this error is inconsistent and probably should be caught. I would prefer the null value to be returned, but it would also be acceptable to not create that field on the output object at all -- and would be consistent with the current behavior when trying to lookup a field that does not exist.

**Comment by andrew-coleman** [comment]
Thanks for raising this.  Now fixed in v1.3.3
