### ISSUE TITLE
Enhancement Request: Function to retrieve Environment Variables

### ISSUE THREAD

**Issue by TotallyInformation** [jsonata-js/jsonata#88]
It would be terribly helpful if we were able to access environment variables from within JSONata.

That would make it easier to mix in environmental settings such as the calling user's home folder or whether we are in a Dev/Prod environment. 

The former is particularly challenging in a cross-platform environment since some OS's use the HOME environment variable but a Windows cmd shell uses HOMEPATH.

Working within JSONata would let us easily and automatically choose between them.

**Comment by andrew-coleman** [comment]
Hi Julian, many thanks for raising this.  JSONata was designed to run in the browser (as it does in the exerciser) as well as in node.js.  Access to environment varariables makes sense in node.js (and hence node-red), but it’s not allowed in the browser (for security reasons).  So I don't think this would be appropriate as a built-in function.  However, this is an excellent candidate as an extension function that could be provided by Node-RED.  E.g. `$envvar()`.  /cc @knolleary @dceejay

**Comment by knolleary** [comment]
Hi - yes, this is something we can look as part of a wider review of how env-vars are exposed in node-red generally.

**Comment by andrew-coleman** [comment]
Thanks Nick.  Given that, I'll close off this issue.
