### ISSUE TITLE
String is passing as an array for function processing

### ISSUE THREAD

**Issue by wnm3** [jsonata-js/jsonata#89]
Using this object:
{
  "input": {
    "text": "get weather at jfk"
  }
}

If I call a function that expects an array as input:
$reverse(input.text)

it works, returning:
[
  "get weather at jfk"
]

But, I would have expected it to reject the input as it is not an array (Array.isArray(input.text) is false. Interesting enough, because the function expects an array as input, it gets converted to an array somehow.

I ran across this trying to add a function to allow assignment of a value to an array cell by passing in the array and index and value and attempting: function assignCell(array,index,value)
 {array[index]=value;return array;} and hadn't realized the input being sent to this function was a String by mistake. Of course the assignment failed (but no errors where thrown because the input had been transformed into an array, but the returned updated array was not accepted back.

I had used <anx:a> as the signature for the assignCell function above.

**Comment by andrew-coleman** [comment]
What you are observing here is one of the fundamental design points of JSONata whereby a singleton array containing a value is equivalent to that value standalone, and can be used interchangeably.  See http://docs.jsonata.org/complex.html#singleton-array-and-value-equivalence.  This equivalence is inspired by the XPath/XQuery properties of a [singleton sequence](https://www.w3.org/TR/xpath-31/#dt-singleton) and allows composite queries to be written that can match one or more results without having to cast between them

**Comment by mattbaileyuk** [comment]
Closing as I believe the original query has been answered. Please reopen if there are follow ups.
