### ISSUE TITLE
Attempting transform didn't work for Account.Order ...

### ISSUE THREAD

**Issue by wnm3** [jsonata-js/jsonata#94]
Even after setting the exerciser to use J:use 1.4

This fails:
Account.Order~>|Product.Description|{'Weight':(Weight * 16)}|

However this works:
Account~>|Order.Product.Description|{'Weight':(Weight * 16)}|

From the closed issue #70 I was hoping what was shown in the example image below was supported in the new 1.4 release:

![image](https://user-images.githubusercontent.com/1359024/32671845-ecbb5eba-c616-11e7-8310-5b3241a1d922.png)

Maybe the Exerciser use of the 1.4 branch didn't pick up the released 1.4 code yet?

**Comment by shrickus** [comment]
I believe the way to switch the exerciser to the new branch is the type "J:branch 1.4" in the input window. When I do that, I see the alternate version shown as ** 1.4 ** underneath the word JSONata in the upper right window.

That being said, I'd much rather see a version pulldown selection list in the title bar of the exerciser page. Switching versions by typing some cryptic string in the input window is a bit of a kludge, and requires the user to know what versions are available. Also, before typing in the branch to use, there is no feedback on the page to show what version is currently running by default. Both of these issues could be handled with a simple select list, I believe.

**Comment by andrew-coleman** [comment]
Hmm.  As a workaround, use this:
`Account.Order.($ ~> |Product.Description|{'Weight':(Weight * 16)}|)`

I need to fixup the generated function to work with an array of objects.  I'll do that in a maintenance release next week.

Thanks for reporting!

**Comment by wnm3** [comment]
Thanks @shrickus -- I had done the J:branch 1.4 but forgot that syntax when typing the issue.
Thanks @andrew-coleman for the workaround.

**Comment by andrew-coleman** [comment]
@shrickus you're right, it is a kludge; it was a quick hack I'd put in for myself to switch to a local dev branch.  Originally, the exerciser was a tool that I knocked up to help me develop and test the language.  But it took on a life of its own.  It's now on github, so any improvements anyone wishes to make, please raise an issue & send a PR :)
Thanks!

**Comment by mattbaileyuk** [comment]
Should also mention that as part of the version switch changes the exerciser will now pick up the latest version from npm as the default.

**Comment by mattbaileyuk** [comment]
This has now been resolved in the newly published 1.4.1 which the exerciser has automatically picked up: http://try.jsonata.org/SyAfdqwkM

If you have any further problems with this, please reopen the issue.
