### ISSUE TITLE
Slack invitation issue

### ISSUE THREAD

**Issue by skellock** [jsonata-js/jsonata#98]
If you go to [https://jsonata.slack.com/signup](https://jsonata.slack.com/signup) it is hardcoding `@ibm.com` as a domain.

![image](https://user-images.githubusercontent.com/68273/32815350-a19565ac-c981-11e7-94c2-45f9d2596eae.png)

Feel free to close this issue if it's working as intended.  😃 

Also, thank you so much for a wonderful library. It is working out really well so far.

**Comment by andrew-coleman** [comment]
Slack seems to insist on there being a domain or set of domains preconfigured.  I'll need to set up an invite age on jsonata.org and use the slack API to request invitations.  In the meantime, I've sent you a invitation.

Thanks for the feedback.

**Comment by skellock** [comment]
Cheers!
